MOCK_SEARCH_PLAYER = {"tag": "#JY9J2Y99", "name": "Mathsman", "townHallLevel": 18, "expLevel": 234, "trophies": 39, "bestTrophies": 5895,
    "warStars": 2420, "attackWins": 0, "defenseWins": 0, "builderHallLevel": 10, "builderBaseTrophies": 4888,
    "bestBuilderBaseTrophies": 5230, "role": "admin", "warPreference": "in", "donations": 463, "donationsReceived": 286,
    "clanCapitalContributions": 2172446, "clan": {"tag": "#G88CYQP", "name": "Reddit", "clanLevel": 29,
        "badgeUrls": {"small": "https://api-assets.clashofclans.com/badges/70/FFz74B0EIkdzUokq306WUkIG98FirmeZt_huGNGDuXc.png",
            "large": "https://api-assets.clashofclans.com/badges/512/FFz74B0EIkdzUokq306WUkIG98FirmeZt_huGNGDuXc.png",
            "medium": "https://api-assets.clashofclans.com/badges/200/FFz74B0EIkdzUokq306WUkIG98FirmeZt_huGNGDuXc.png"}},
    "leagueTier": {"id": 105000033, "name": "Electro League 33",
        "iconUrls": {"small": "https://api-assets.clashofclans.com/leaguetiers/125/VFqkaQimExWtSmIf9PC8WEpj4Vd58oLjPWyZqfVb5VE.png",
            "large": "https://api-assets.clashofclans.com/leaguetiers/326/VFqkaQimExWtSmIf9PC8WEpj4Vd58oLjPWyZqfVb5VE.png"}},
    "builderBaseLeague": {"id": 44000034, "name": "Platinum League I"},
    "legendStatistics": {"legendTrophies": 22, "previousSeason": {"id": "2025-11-03", "rank": 82967, "trophies": 5022},
        "bestSeason": {"id": "2025-11-03", "rank": 82967, "trophies": 5022},
        "bestBuilderBaseSeason": {"id": "2025-01", "rank": 141209, "trophies": 5001}, "currentSeason": {"trophies": 39}}, "achievements": [
        {"name": "Bigger Coffers", "stars": 3, "value": 18, "target": 10, "info": "Upgrade a Gold Storage to level 10",
            "completionInfo": "Highest Gold Storage level: 18", "village": "home"},
        {"name": "Get those Goblins!", "stars": 3, "value": 207, "target": 150, "info": "Win 150 Stars on the Campaign Map",
            "completionInfo": "Stars in Campaign Map: 207", "village": "home"},
        {"name": "Bigger & Better", "stars": 3, "value": 18, "target": 8, "info": "Upgrade Town Hall to level 8",
            "completionInfo": "Current Town Hall level: 18", "village": "home"},
        {"name": "Nice and Tidy", "stars": 3, "value": 3078, "target": 500, "info": "Remove 500 obstacles (trees, rocks, bushes)",
            "completionInfo": "Total obstacles removed: 3078", "village": "home"},
        {"name": "Discover New Troops", "stars": 3, "value": 1, "target": 1, "info": "Unlock Dragon in the Barracks",
            "completionInfo": None, "village": "home"},
        {"name": "Gold Grab", "stars": 3, "value": 2000000000, "target": 100000000, "info": "Steal 100000000 Gold",
            "completionInfo": "Total Gold looted: 2000000000", "village": "home"},
        {"name": "Elixir Escapade", "stars": 3, "value": 2000000000, "target": 100000000, "info": "Steal 100000000 elixir",
            "completionInfo": "Total Elixir looted: 2000000000", "village": "home"},
        {"name": "Sweet Victory!", "stars": 3, "value": 5895, "target": 1250,
            "info": "Achieve a total of 1250 trophies in Multiplayer battles", "completionInfo": "Trophy record: 5895", "village": "home"},
        {"name": "Empire Builder", "stars": 3, "value": 13, "target": 4, "info": "Upgrade Clan Castle to level 4",
            "completionInfo": "Current Clan Castle level: 13", "village": "home"},
        {"name": "Wall Buster", "stars": 3, "value": 141198, "target": 2000, "info": "Destroy 2000 Walls in Multiplayer battles",
            "completionInfo": "Total Walls destroyed: 141198", "village": "home"},
        {"name": "Humiliator", "stars": 3, "value": 5959, "target": 2000, "info": "Destroy 2000 Town Halls in Multiplayer battles",
            "completionInfo": "Total Town Halls destroyed: 5959", "village": "home"},
        {"name": "Union Buster", "stars": 3, "value": 35959, "target": 2500, "info": "Destroy 2500 Builder's Huts in Multiplayer battles",
            "completionInfo": "Total Builder's Huts destroyed: 35959", "village": "home"},
        {"name": "Conqueror", "stars": 3, "value": 8876, "target": 5000, "info": "Win 5000 Multiplayer battles",
            "completionInfo": "Total multiplayer battles won: 8876", "village": "home"},
        {"name": "Unbreakable", "stars": 2, "value": 1971, "target": 5000, "info": "Successfully defend against 5000 attacks",
            "completionInfo": "Total defenses won: 1971", "village": "home"},
        {"name": "Friend in Need", "stars": 3, "value": 65297, "target": 25000,
            "info": "Donate 25000 capacity worth of reinforcements to Clanmates", "completionInfo": "Total capacity donated: 65297",
            "village": "home"},
        {"name": "Mortar Mauler", "stars": 3, "value": 21208, "target": 5000, "info": "Destroy 5000 Mortars in Multiplayer battles",
            "completionInfo": "Total Mortars destroyed: 21208", "village": "home"},
        {"name": "Heroic Heist", "stars": 3, "value": 36981586, "target": 1000000, "info": "Steal 1000000 Dark Elixir",
            "completionInfo": "Total Dark Elixir looted: 36981586", "village": "home"},
        {"name": "League All-Star", "stars": 3, "value": 22, "target": 1, "info": "Become a Champion!", "completionInfo": None,
            "village": "home"},
        {"name": "X-Bow Exterminator", "stars": 3, "value": 13824, "target": 2500, "info": "Destroy 2500 X-Bows in Multiplayer battles",
            "completionInfo": "Total X-Bows destroyed: 13824", "village": "home"},
        {"name": "Firefighter", "stars": 3, "value": 8642, "target": 5000, "info": "Destroy 5000 Inferno Towers in Multiplayer battles",
            "completionInfo": "Total Inferno Towers destroyed: 8642", "village": "home"},
        {"name": "War Hero", "stars": 3, "value": 2420, "target": 1000, "info": "Score 1000 Stars for your clan in Clan War battles",
            "completionInfo": "Total Stars scored for clan in Clan War battles: 2420", "village": "home"},
        {"name": "Clan War Wealth", "stars": 3, "value": 2000000000, "target": 100000000,
            "info": "Collect 100000000 Gold from the Clan Castle", "completionInfo": "Total Gold collected in Clan War bonuses: 2000000000",
            "village": "home"}, {"name": "Anti-Artillery", "stars": 3, "value": 2890, "target": 2000,
            "info": "Destroy 2000 Eagle or Inferno Artilleries in Multiplayer battles",
            "completionInfo": "Total Eagle or Inferno Artilleries destroyed: 2890", "village": "home"},
        {"name": "Sharing is caring", "stars": 2, "value": 2105, "target": 10000,
            "info": "Donate 10000 Spell storage capacity worth of Spells", "completionInfo": "Total Spell capacity donated: 2105",
            "village": "home"}, {"name": "Keep Your Account Safe!", "stars": 0, "value": 0, "target": 1,
            "info": "Protect your Village by connecting to a social network", "completionInfo": "Completed!", "village": "home"},
        {"name": "Master Engineering", "stars": 3, "value": 10, "target": 8, "info": "Upgrade Builder Hall to level 8",
            "completionInfo": "Current Builder Hall level: 10", "village": "builderBase"},
        {"name": "Next Generation Model", "stars": 3, "value": 1, "target": 1, "info": "Unlock Power P.E.K.K.A in the Builder Barracks",
            "completionInfo": None, "village": "builderBase"},
        {"name": "Un-Build It", "stars": 3, "value": 2050, "target": 2000, "info": "Destroy 2000 Builder Halls in Builder Battles",
            "completionInfo": "Total Builder Halls destroyed: 2050", "village": "builderBase"},
        {"name": "Champion Builder", "stars": 3, "value": 5230, "target": 3000,
            "info": "Achieve a total of 3000 trophies in Builder Battles", "completionInfo": "Builder Trophy record: 5230",
            "village": "builderBase"},
        {"name": "High Gear", "stars": 3, "value": 3, "target": 3, "info": "Gear Up 3 buildings using the Master Builder",
            "completionInfo": "Total buildings geared up: 3", "village": "builderBase"},
        {"name": "Hidden Treasures", "stars": 3, "value": 1, "target": 1, "info": "Rebuild Battle Machine", "completionInfo": None,
            "village": "builderBase"},
        {"name": "Games Champion", "stars": 3, "value": 190895, "target": 100000, "info": "Earn 100000 points in Clan Games",
            "completionInfo": "Total Clan Games points: 190895", "village": "home"},
        {"name": "Dragon Slayer", "stars": 1, "value": 1, "target": 1, "info": "Slay the Giant Dragon on the Campaign Map",
            "completionInfo": None, "village": "home"}, {"name": "War League Legend", "stars": 3, "value": 930, "target": 250,
            "info": "Score 250 Stars for your clan in War League battles",
            "completionInfo": "Total Stars scored for clan in War League battles: 930", "village": "home"},
        {"name": "Keep Your Account Safe!", "stars": 0, "value": 0, "target": 1,
            "info": "Connect your account to Supercell ID for safe keeping.", "completionInfo": "Completed!", "village": "home"},
        {"name": "Well Seasoned", "stars": 3, "value": 172540, "target": 50000, "info": "Earn 50000 points in Season Challenges",
            "completionInfo": "Total Season Challenges points: 172540", "village": "home"},
        {"name": "Shattered and Scattered", "stars": 3, "value": 4155, "target": 4000,
            "info": "Destroy 4000 Scattershots in Multiplayer battles", "completionInfo": "Total Scattershots destroyed: 4155",
            "village": "home"}, {"name": "Not So Easy This Time", "stars": 3, "value": 2216, "target": 2000,
            "info": "Destroy 2000 weaponized Town Halls in Multiplayer battles", "completionInfo": "Weaponized Town Halls destroyed: 2216",
            "village": "home"}, {"name": "Bust This!", "stars": 3, "value": 9333, "target": 2500,
            "info": "Destroy 2500 weaponized Builder's Huts in Multiplayer battles",
            "completionInfo": "Total weaponized Builder's Huts destroyed: 9333", "village": "home"},
        {"name": "Superb Work", "stars": 0, "value": 19, "target": 20, "info": "Boost a Super Troop 20 times",
            "completionInfo": "Total times Super Troops boosted: 19", "village": "home"},
        {"name": "Siege Sharer", "stars": 1, "value": 305, "target": 1000, "info": "Donate 1000 Siege Machines",
            "completionInfo": "Total Siege Machines donated: 305", "village": "home"},
        {"name": "Aggressive Capitalism", "stars": 3, "value": 3096565, "target": 1000000,
            "info": "Loot 1000000 Capital Gold during Raid attacks", "completionInfo": "Total Capital Gold looted: 3096565",
            "village": "clanCapital"}, {"name": "Most Valuable Clanmate", "stars": 3, "value": 2172446, "target": 2000000,
            "info": "Contribute 2000000 Capital Gold to upgrades in the Clan Capital",
            "completionInfo": "Total Capital Gold contributed: 2172446", "village": "clanCapital"},
        {"name": "Counterspell", "stars": 2, "value": 3334, "target": 4000, "info": "Destroy 4000 Spell Towers in Multiplayer Battles",
            "completionInfo": "Total Spell Towers Destroyed: 3334", "village": "home"},
        {"name": "Monolith Masher", "stars": 2, "value": 1587, "target": 2000, "info": "Destroy 2000 Monoliths in Multiplayer Battles",
            "completionInfo": "Total Monoliths Destroyed: 1587", "village": "home"},
        {"name": "Ungrateful Child", "stars": 0, "value": 0, "target": 1, "info": "Defeat M.O.M.M.A on the Campaign Map",
            "completionInfo": None, "village": "home"},
        {"name": "Supercharger", "stars": 0, "value": 0, "target": 5, "info": "Supercharge buildings 5 times",
            "completionInfo": "Total Supercharges: 0", "village": "home"},
        {"name": "Multi-Archer Tower Terminator", "stars": 2, "value": 1829, "target": 5000,
            "info": "Destroy 5000 Multi-Archer Towers in Multiplayer Battles",
            "completionInfo": "Total Multi-Archer Towers Destroyed: 1829", "village": "home"},
        {"name": "Ricochet Cannon Crusher", "stars": 2, "value": 1799, "target": 5000,
            "info": "Destroy 5000 Ricochet Cannons in Multiplayer Battles", "completionInfo": "Total Ricochet Cannons Destroyed: 1799",
            "village": "home"}, {"name": "Firespitter Finisher", "stars": 2, "value": 1125, "target": 4000,
            "info": "Destroy 4000 Firespitters in Multiplayer Battles", "completionInfo": "Total Firespitters Destroyed: 1125",
            "village": "home"}, {"name": "Multi-Gear Tower Trampler", "stars": 2, "value": 500, "target": 2000,
            "info": "Destroy 2000 Multi-Gear Towers in Multiplayer Battles", "completionInfo": "Total Multi-Gear Towers Destroyed: 500",
            "village": "home"},
        {"name": "Crafting Connoisseur", "stars": 0, "value": 0, "target": 5, "info": "Upgrade Crafted Defenses 5 times",
            "completionInfo": "Total Crafted Defense upgrades: 0", "village": "home"},
        {"name": "Crafter’s Nightmare", "stars": 2, "value": 320, "target": 2000,
            "info": "Destroy 2000 Crafted Defenses in Multiplayer Battles", "completionInfo": "Total Crafted Defenses Destroyed: 320",
            "village": "home"},
        {"name": "League Follower", "stars": 3, "value": 34, "target": 12, "info": "Reach League Wizard 12", "completionInfo": None,
            "village": "home"}], "playerHouse": {
        "elements": [{"type": "ground", "id": 82000004}, {"type": "walls", "id": 82000052}, {"type": "roof", "id": 82000081},
            {"type": "decoration", "id": 82000066}]}, "labels": [{"id": 57000000, "name": "Clan Wars",
        "iconUrls": {"small": "https://api-assets.clashofclans.com/labels/64/ZxJp9606Vl1sa0GHg5JmGp8TdHS4l0jE4WFuil1ENvA.png",
            "medium": "https://api-assets.clashofclans.com/labels/128/ZxJp9606Vl1sa0GHg5JmGp8TdHS4l0jE4WFuil1ENvA.png"}},
        {"id": 57000001, "name": "Clan War League",
            "iconUrls": {"small": "https://api-assets.clashofclans.com/labels/64/JOzAO4r91eVaJELAPB-iuAx6f_zBbRPCLM_ag5mpK4s.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/JOzAO4r91eVaJELAPB-iuAx6f_zBbRPCLM_ag5mpK4s.png"}},
        {"id": 57000015, "name": "Veteran",
            "iconUrls": {"small": "https://api-assets.clashofclans.com/labels/64/u-VKK5y0hj0U8B1xdawjxNcXciv-fwMK3VqEBWCn1oM.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/u-VKK5y0hj0U8B1xdawjxNcXciv-fwMK3VqEBWCn1oM.png"}}],
    "troops": [{"name": "Barbarian", "level": 12, "maxLevel": 12, "village": "home"},
        {"name": "Archer", "level": 13, "maxLevel": 13, "village": "home"},
        {"name": "Goblin", "level": 9, "maxLevel": 9, "village": "home"}, {"name": "Giant", "level": 13, "maxLevel": 14, "village": "home"},
        {"name": "Wall Breaker", "level": 13, "maxLevel": 14, "village": "home"},
        {"name": "Balloon", "level": 12, "maxLevel": 12, "village": "home"},
        {"name": "Wizard", "level": 13, "maxLevel": 14, "village": "home"},
        {"name": "Healer", "level": 10, "maxLevel": 11, "village": "home"},
        {"name": "Dragon", "level": 12, "maxLevel": 12, "village": "home"},
        {"name": "P.E.K.K.A", "level": 12, "maxLevel": 13, "village": "home"},
        {"name": "Minion", "level": 13, "maxLevel": 14, "village": "home"},
        {"name": "Hog Rider", "level": 14, "maxLevel": 14, "village": "home"},
        {"name": "Valkyrie", "level": 11, "maxLevel": 11, "village": "home"},
        {"name": "Golem", "level": 14, "maxLevel": 14, "village": "home"}, {"name": "Witch", "level": 7, "maxLevel": 7, "village": "home"},
        {"name": "Lava Hound", "level": 7, "maxLevel": 7, "village": "home"},
        {"name": "Bowler", "level": 9, "maxLevel": 10, "village": "home"},
        {"name": "Baby Dragon", "level": 11, "maxLevel": 11, "village": "home"},
        {"name": "Miner", "level": 11, "maxLevel": 12, "village": "home"},
        {"name": "Super Barbarian", "level": 1, "maxLevel": 8, "village": "home"},
        {"name": "Super Archer", "level": 1, "maxLevel": 9, "village": "home"},
        {"name": "Super Wall Breaker", "level": 1, "maxLevel": 10, "village": "home"},
        {"name": "Super Giant", "level": 1, "maxLevel": 10, "village": "home"},
        {"name": "Raged Barbarian", "level": 20, "maxLevel": 20, "village": "builderBase"},
        {"name": "Sneaky Archer", "level": 20, "maxLevel": 20, "village": "builderBase"},
        {"name": "Beta Minion", "level": 20, "maxLevel": 20, "village": "builderBase"},
        {"name": "Boxer Giant", "level": 20, "maxLevel": 20, "village": "builderBase"},
        {"name": "Bomber", "level": 20, "maxLevel": 20, "village": "builderBase"},
        {"name": "Power P.E.K.K.A", "level": 20, "maxLevel": 20, "village": "builderBase"},
        {"name": "Cannon Cart", "level": 20, "maxLevel": 20, "village": "builderBase"},
        {"name": "Drop Ship", "level": 20, "maxLevel": 20, "village": "builderBase"},
        {"name": "Baby Dragon", "level": 20, "maxLevel": 20, "village": "builderBase"},
        {"name": "Night Witch", "level": 20, "maxLevel": 20, "village": "builderBase"},
        {"name": "Wall Wrecker", "level": 5, "maxLevel": 6, "village": "home"},
        {"name": "Battle Blimp", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Yeti", "level": 7, "maxLevel": 7, "village": "home"},
        {"name": "Sneaky Goblin", "level": 1, "maxLevel": 5, "superTroopIsActive": True, "village": "home"},
        {"name": "Super Miner", "level": 1, "maxLevel": 12, "village": "home"},
        {"name": "Rocket Balloon", "level": 1, "maxLevel": 8, "village": "home"},
        {"name": "Ice Golem", "level": 9, "maxLevel": 9, "village": "home"},
        {"name": "Electro Dragon", "level": 8, "maxLevel": 9, "village": "home"},
        {"name": "Stone Slammer", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Inferno Dragon", "level": 1, "maxLevel": 11, "village": "home"},
        {"name": "Super Valkyrie", "level": 1, "maxLevel": 11, "village": "home"},
        {"name": "Dragon Rider", "level": 5, "maxLevel": 6, "village": "home"},
        {"name": "Super Witch", "level": 1, "maxLevel": 7, "village": "home"},
        {"name": "Hog Glider", "level": 20, "maxLevel": 20, "village": "builderBase"},
        {"name": "Siege Barracks", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Ice Hound", "level": 1, "maxLevel": 7, "village": "home"},
        {"name": "Super Bowler", "level": 1, "maxLevel": 10, "village": "home"},
        {"name": "Super Dragon", "level": 1, "maxLevel": 10, "village": "home"},
        {"name": "Headhunter", "level": 3, "maxLevel": 3, "village": "home"},
        {"name": "Super Wizard", "level": 1, "maxLevel": 10, "village": "home"},
        {"name": "Super Minion", "level": 1, "maxLevel": 11, "village": "home"},
        {"name": "Log Launcher", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Flame Flinger", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Battle Drill", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Electro Titan", "level": 4, "maxLevel": 4, "village": "home"},
        {"name": "Apprentice Warden", "level": 4, "maxLevel": 4, "village": "home"},
        {"name": "Super Hog Rider", "level": 1, "maxLevel": 11, "village": "home"},
        {"name": "Electrofire Wizard", "level": 20, "maxLevel": 20, "village": "builderBase"},
        {"name": "Root Rider", "level": 3, "maxLevel": 3, "village": "home"},
        {"name": "Druid", "level": 5, "maxLevel": 5, "village": "home"}, {"name": "Thrower", "level": 3, "maxLevel": 4, "village": "home"},
        {"name": "Troop Launcher", "level": 4, "maxLevel": 4, "village": "home"},
        {"name": "Super Yeti", "level": 1, "maxLevel": 7, "village": "home"},
        {"name": "Furnace", "level": 4, "maxLevel": 4, "village": "home"},
        {"name": "L.A.S.S.I", "level": 5, "maxLevel": 15, "village": "home"},
        {"name": "Mighty Yak", "level": 11, "maxLevel": 15, "village": "home"},
        {"name": "Electro Owl", "level": 15, "maxLevel": 15, "village": "home"},
        {"name": "Unicorn", "level": 15, "maxLevel": 15, "village": "home"},
        {"name": "Phoenix", "level": 10, "maxLevel": 10, "village": "home"},
        {"name": "Poison Lizard", "level": 10, "maxLevel": 15, "village": "home"},
        {"name": "Diggy", "level": 10, "maxLevel": 10, "village": "home"},
        {"name": "Frosty", "level": 15, "maxLevel": 15, "village": "home"},
        {"name": "Spirit Fox", "level": 10, "maxLevel": 10, "village": "home"},
        {"name": "Angry Jelly", "level": 10, "maxLevel": 10, "village": "home"},
        {"name": "Sneezy", "level": 5, "maxLevel": 10, "village": "home"}], "heroes": [
        {"name": "Barbarian King", "level": 100, "maxLevel": 105,
            "equipment": [{"name": "Spiky Ball", "level": 27, "maxLevel": 27, "village": "home"},
                {"name": "Earthquake Boots", "level": 18, "maxLevel": 18, "village": "home"}], "village": "home"},
        {"name": "Archer Queen", "level": 100, "maxLevel": 105,
            "equipment": [{"name": "Giant Arrow", "level": 18, "maxLevel": 18, "village": "home"},
                {"name": "Frozen Arrow", "level": 27, "maxLevel": 27, "village": "home"}], "village": "home"},
        {"name": "Grand Warden", "level": 75, "maxLevel": 80,
            "equipment": [{"name": "Rage Gem", "level": 18, "maxLevel": 18, "village": "home"},
                {"name": "Healing Tome", "level": 18, "maxLevel": 18, "village": "home"}], "village": "home"},
        {"name": "Battle Machine", "level": 35, "maxLevel": 35, "village": "builderBase"},
        {"name": "Royal Champion", "level": 50, "maxLevel": 55,
            "equipment": [{"name": "Rocket Spear", "level": 27, "maxLevel": 27, "village": "home"},
                {"name": "Electro Boots", "level": 27, "maxLevel": 27, "village": "home"}], "village": "home"},
        {"name": "Battle Copter", "level": 35, "maxLevel": 35, "village": "builderBase"},
        {"name": "Minion Prince", "level": 90, "maxLevel": 95,
            "equipment": [{"name": "Metal Pants", "level": 18, "maxLevel": 18, "village": "home"},
                {"name": "Dark Orb", "level": 18, "maxLevel": 18, "village": "home"}], "village": "home"}],
    "heroEquipment": [{"name": "Giant Gauntlet", "level": 27, "maxLevel": 27, "village": "home"},
        {"name": "Rocket Spear", "level": 27, "maxLevel": 27, "village": "home"},
        {"name": "Spiky Ball", "level": 27, "maxLevel": 27, "village": "home"},
        {"name": "Frozen Arrow", "level": 27, "maxLevel": 27, "village": "home"},
        {"name": "Heroic Torch", "level": 1, "maxLevel": 27, "village": "home"},
        {"name": "Fireball", "level": 26, "maxLevel": 27, "village": "home"},
        {"name": "Snake Bracelet", "level": 2, "maxLevel": 27, "village": "home"},
        {"name": "Dark Crown", "level": 2, "maxLevel": 27, "village": "home"},
        {"name": "Magic Mirror", "level": 20, "maxLevel": 27, "village": "home"},
        {"name": "Electro Boots", "level": 27, "maxLevel": 27, "village": "home"},
        {"name": "Lavaloon Puppet", "level": 5, "maxLevel": 27, "village": "home"},
        {"name": "Action Figure", "level": 23, "maxLevel": 27, "village": "home"},
        {"name": "Meteor Staff", "level": 14, "maxLevel": 27, "village": "home"},
        {"name": "Barbarian Puppet", "level": 17, "maxLevel": 18, "village": "home"},
        {"name": "Rage Vial", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Archer Puppet", "level": 17, "maxLevel": 18, "village": "home"},
        {"name": "Invisibility Vial", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Eternal Tome", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Life Gem", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Seeking Shield", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Royal Gem", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Earthquake Boots", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Hog Rider Puppet", "level": 2, "maxLevel": 18, "village": "home"},
        {"name": "Vampstache", "level": 2, "maxLevel": 18, "village": "home"},
        {"name": "Haste Vial", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Giant Arrow", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Healer Puppet", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Rage Gem", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Healing Tome", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Henchmen Puppet", "level": 14, "maxLevel": 18, "village": "home"},
        {"name": "Dark Orb", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Metal Pants", "level": 18, "maxLevel": 18, "village": "home"},
        {"name": "Noble Iron", "level": 18, "maxLevel": 18, "village": "home"}],
    "spells": [{"name": "Lightning Spell", "level": 12, "maxLevel": 13, "village": "home"},
        {"name": "Healing Spell", "level": 11, "maxLevel": 12, "village": "home"},
        {"name": "Rage Spell", "level": 6, "maxLevel": 6, "village": "home"},
        {"name": "Jump Spell", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Freeze Spell", "level": 7, "maxLevel": 7, "village": "home"},
        {"name": "Poison Spell", "level": 11, "maxLevel": 12, "village": "home"},
        {"name": "Earthquake Spell", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Haste Spell", "level": 6, "maxLevel": 7, "village": "home"},
        {"name": "Clone Spell", "level": 8, "maxLevel": 8, "village": "home"},
        {"name": "Skeleton Spell", "level": 8, "maxLevel": 8, "village": "home"},
        {"name": "Bat Spell", "level": 6, "maxLevel": 8, "village": "home"},
        {"name": "Invisibility Spell", "level": 4, "maxLevel": 4, "village": "home"},
        {"name": "Recall Spell", "level": 6, "maxLevel": 6, "village": "home"},
        {"name": "Overgrowth Spell", "level": 4, "maxLevel": 4, "village": "home"},
        {"name": "Revive Spell", "level": 4, "maxLevel": 4, "village": "home"},
        {"name": "Ice Block Spell", "level": 5, "maxLevel": 5, "village": "home"}]}

MOCK_CLAN_MEMBER = {"tag": "#2QJVVYRRU", "name": "xanada3", "role": "coLeader", "expLevel": 237,
    "league": {"id": 29000022, "name": "Legend League",
        "iconUrls": {"small": "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
            "tiny": "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
            "medium": "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png", }, },
    "trophies": 5357, "versusTrophies": 5084, "clanRank": 1, "previousClanRank": 1, "donations": 12638, "donationsReceived": 11157, }
