MOCK_SEARCH_PLAYER = {
    "tag": "#JY9J2Y99",
    "name": "Mathsman",
    "townHallLevel": 12,
    "townHallWeaponLevel": 5,
    "expLevel": 162,
    "trophies": 3065,
    "bestTrophies": 3668,
    "warStars": 898,
    "attackWins": 36,
    "defenseWins": 18,
    "builderHallLevel": 7,
    "versusTrophies": 2804,
    "bestVersusTrophies": 2968,
    "versusBattleWins": 782,
    "role": "member",
    "donations": 375,
    "donationsReceived": 647,
    "clan": {
        "tag": "#G88CYQP",
        "name": "Reddit",
        "clanLevel": 19,
        "badgeUrls": {
            "small": "https://api-assets.clashofclans.com/badges/70/gF1wdSrH72cPmAc9LG41nRZoUdI1apsF0ZxxEXtxVoA.png",
            "large": "https://api-assets.clashofclans.com/badges/512/gF1wdSrH72cPmAc9LG41nRZoUdI1apsF0ZxxEXtxVoA.png",
            "medium": "https://api-assets.clashofclans.com/badges/200/gF1wdSrH72cPmAc9LG41nRZoUdI1apsF0ZxxEXtxVoA.png",
        },
    },
    "league": {
        "id": 29000015,
        "name": "Master League I",
        "iconUrls": {
            "small": "https://api-assets.clashofclans.com/leagues/72/olUfFb1wscIH8hqECAdWbdB6jPm9R8zzEyHIzyBgRXc.png",
            "tiny": "https://api-assets.clashofclans.com/leagues/36/olUfFb1wscIH8hqECAdWbdB6jPm9R8zzEyHIzyBgRXc.png",
            "medium": "https://api-assets.clashofclans.com/leagues/288/olUfFb1wscIH8hqECAdWbdB6jPm9R8zzEyHIzyBgRXc.png",
        },
    },
    "achievements": [
        {
            "name": "Bigger Coffers",
            "stars": 3,
            "value": 13,
            "target": 10,
            "info": "Upgrade a Gold Storage to level 10",
            "completionInfo": "Highest Gold Storage level: 13",
            "village": "home",
        },
        {
            "name": "Get those Goblins!",
            "stars": 3,
            "value": 150,
            "target": 150,
            "info": "Win 150 Stars on the Campaign Map",
            "completionInfo": "Stars in Campaign Map: 150",
            "village": "home",
        },
        {
            "name": "Bigger & Better",
            "stars": 3,
            "value": 12,
            "target": 8,
            "info": "Upgrade Town Hall to level 8",
            "completionInfo": "Current Town Hall level: 12",
            "village": "home",
        },
        {
            "name": "Nice and Tidy",
            "stars": 3,
            "value": 2735,
            "target": 500,
            "info": "Remove 500 obstacles (trees, rocks, bushes)",
            "completionInfo": "Total obstacles removed: 2735",
            "village": "home",
        },
        {
            "name": "Release the Beasts",
            "stars": 3,
            "value": 1,
            "target": 1,
            "info": "Unlock Dragon in the Barracks",
            "completionInfo": None,
            "village": "home",
        },
        {
            "name": "Gold Grab",
            "stars": 3,
            "value": 1973665572,
            "target": 100000000,
            "info": "Steal 100000000 gold",
            "completionInfo": "Total Gold looted: 1973665572",
            "village": "home",
        },
        {
            "name": "Elixir Escapade",
            "stars": 3,
            "value": 2000000000,
            "target": 100000000,
            "info": "Steal 100000000 elixir",
            "completionInfo": "Total Elixir looted: 2000000000",
            "village": "home",
        },
        {
            "name": "Sweet Victory!",
            "stars": 3,
            "value": 3668,
            "target": 1250,
            "info": "Achieve a total of 1250 trophies in Multiplayer battles",
            "completionInfo": "Trophy record: 3668",
            "village": "home",
        },
        {
            "name": "Empire Builder",
            "stars": 3,
            "value": 8,
            "target": 4,
            "info": "Upgrade Clan Castle to level 4",
            "completionInfo": "Current Clan Castle level: 8",
            "village": "home",
        },
        {
            "name": "Wall Buster",
            "stars": 3,
            "value": 32237,
            "target": 2000,
            "info": "Destroy 2000 Walls in Multiplayer battles",
            "completionInfo": "Total walls destroyed: 32237",
            "village": "home",
        },
        {
            "name": "Humiliator",
            "stars": 3,
            "value": 3464,
            "target": 2000,
            "info": "Destroy 2000 Town Halls in Multiplayer battles",
            "completionInfo": "Total Town Halls destroyed: 3464",
            "village": "home",
        },
        {
            "name": "Union Buster",
            "stars": 3,
            "value": 23807,
            "target": 2500,
            "info": "Destroy 2500 Builder's Huts in Multiplayer battles",
            "completionInfo": "Total Builder's Huts destroyed: 23807",
            "village": "home",
        },
        {
            "name": "Conqueror",
            "stars": 3,
            "value": 6086,
            "target": 5000,
            "info": "Win 5000 Multiplayer battles",
            "completionInfo": "Total multiplayer battles won: 6086",
            "village": "home",
        },
        {
            "name": "Unbreakable",
            "stars": 2,
            "value": 1021,
            "target": 5000,
            "info": "Successfully defend against 5000 attacks",
            "completionInfo": "Total defenses won: 1021",
            "village": "home",
        },
        {
            "name": "Friend in Need",
            "stars": 3,
            "value": 42750,
            "target": 25000,
            "info": "Donate 25000 Clan Castle capacity worth of reinforcements",
            "completionInfo": "Total capacity donated: 42750",
            "village": "home",
        },
        {
            "name": "Mortar Mauler",
            "stars": 3,
            "value": 11510,
            "target": 5000,
            "info": "Destroy 5000 Mortars in Multiplayer battles",
            "completionInfo": "Total Mortars destroyed: 11510",
            "village": "home",
        },
        {
            "name": "Heroic Heist",
            "stars": 3,
            "value": 11664777,
            "target": 1000000,
            "info": "Steal 1000000 Dark Elixir",
            "completionInfo": "Total Dark Elixir looted: 11664777",
            "village": "home",
        },
        {
            "name": "League All-Star",
            "stars": 3,
            "value": 17,
            "target": 1,
            "info": "Become a Champion!",
            "completionInfo": None,
            "village": "home",
        },
        {
            "name": "X-Bow Exterminator",
            "stars": 3,
            "value": 4600,
            "target": 2500,
            "info": "Destroy 2500 X-Bows in Multiplayer battles",
            "completionInfo": "Total X-Bows destroyed: 4600",
            "village": "home",
        },
        {
            "name": "Firefighter",
            "stars": 2,
            "value": 1937,
            "target": 5000,
            "info": "Destroy 5000 Inferno Towers in Multiplayer battles",
            "completionInfo": "Total Inferno Towers destroyed: 1937",
            "village": "home",
        },
        {
            "name": "War Hero",
            "stars": 2,
            "value": 898,
            "target": 1000,
            "info": "Score 1000 Stars for your clan in Clan War battles",
            "completionInfo": "Total Stars scored for clan in Clan War battles: 898",
            "village": "home",
        },
        {
            "name": "Treasurer",
            "stars": 3,
            "value": 593252135,
            "target": 100000000,
            "info": "Collect 100000000 gold from the Treasury",
            "completionInfo": "Total gold collected in Clan War bonuses: 593252135",
            "village": "home",
        },
        {
            "name": "Anti-Artillery",
            "stars": 2,
            "value": 537,
            "target": 2000,
            "info": "Destroy 2000 Eagle Artilleries in Multiplayer battles",
            "completionInfo": "Total Eagle Artilleries destroyed: 537",
            "village": "home",
        },
        {
            "name": "Sharing is caring",
            "stars": 1,
            "value": 996,
            "target": 2000,
            "info": "Donate 2000 spell storage capacity worth of spells",
            "completionInfo": "Total spell capacity donated: 996",
            "village": "home",
        },
        {
            "name": "Keep your village safe",
            "stars": 0,
            "value": 0,
            "target": 1,
            "info": "Connect your account to a social network for safe keeping.",
            "completionInfo": "Completed!",
            "village": "home",
        },
        {
            "name": "Master Engineering",
            "stars": 2,
            "value": 7,
            "target": 8,
            "info": "Upgrade Builder Hall to level 8",
            "completionInfo": "Current Builder Hall level: 7",
            "village": "builderBase",
        },
        {
            "name": "Next Generation Model",
            "stars": 2,
            "value": 1,
            "target": 1,
            "info": "Unlock Cannon Cart in the Builder Barracks",
            "completionInfo": None,
            "village": "builderBase",
        },
        {
            "name": "Un-Build It",
            "stars": 2,
            "value": 870,
            "target": 2000,
            "info": "Destroy 2000 Builder Halls in Versus battles",
            "completionInfo": "Total Builder Halls destroyed: 870",
            "village": "builderBase",
        },
        {
            "name": "Champion Builder",
            "stars": 2,
            "value": 2968,
            "target": 3000,
            "info": "Achieve a total of 3000 trophies in Versus battles",
            "completionInfo": "Versus Trophy record: 2968",
            "village": "builderBase",
        },
        {
            "name": "High Gear",
            "stars": 2,
            "value": 2,
            "target": 3,
            "info": "Gear Up 3 buildings using the Master Builder",
            "completionInfo": "Total buildings geared up: 2",
            "village": "builderBase",
        },
        {
            "name": "Hidden Treasures",
            "stars": 3,
            "value": 1,
            "target": 1,
            "info": "Rebuild Battle Machine",
            "completionInfo": None,
            "village": "builderBase",
        },
        {
            "name": "Games Champion",
            "stars": 2,
            "value": 56995,
            "target": 100000,
            "info": "Earn 100000 points in Clan Games",
            "completionInfo": "Total Clan Games points: 56995",
            "village": "home",
        },
        {
            "name": "Dragon Slayer",
            "stars": 0,
            "value": 0,
            "target": 1,
            "info": "Slay the Giant Dragon",
            "completionInfo": None,
            "village": "home",
        },
        {
            "name": "War League Legend",
            "stars": 2,
            "value": 161,
            "target": 250,
            "info": "Score 250 Stars for your clan in War League battles",
            "completionInfo": "Total Stars scored for clan in War League battles: 161",
            "village": "home",
        },
        {
            "name": "Keep your village safe",
            "stars": 0,
            "value": 0,
            "target": 1,
            "info": "Connect your account to Supercell ID for safe keeping.",
            "completionInfo": "Completed!",
            "village": "home",
        },
        {
            "name": "Well Seasoned",
            "stars": 2,
            "value": 21610,
            "target": 50000,
            "info": "Earn 50000 points in Season Challenges",
            "completionInfo": "Total Season Challenges points: 21610",
            "village": "home",
        },
        {
            "name": "Shattered and Scattered",
            "stars": 0,
            "value": 8,
            "target": 40,
            "info": "Destroy 40 Scattershots in Multiplayer battles",
            "completionInfo": "Total Scattershots destroyed: 8",
            "village": "home",
        },
    ],
    "versusBattleWinCount": 782,
    "labels": [
        {
            "id": 57000000,
            "name": "Clan Wars",
            "iconUrls": {
                "small": "https://api-assets.clashofclans.com/labels/64/ZxJp9606Vl1sa0GHg5JmGp8TdHS4l0jE4WFuil1ENvA.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/ZxJp9606Vl1sa0GHg5JmGp8TdHS4l0jE4WFuil1ENvA.png",
            },
        },
        {
            "id": 57000001,
            "name": "Clan War League",
            "iconUrls": {
                "small": "https://api-assets.clashofclans.com/labels/64/JOzAO4r91eVaJELAPB-iuAx6f_zBbRPCLM_ag5mpK4s.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/JOzAO4r91eVaJELAPB-iuAx6f_zBbRPCLM_ag5mpK4s.png",
            },
        },
        {
            "id": 57000015,
            "name": "Veteran",
            "iconUrls": {
                "small": "https://api-assets.clashofclans.com/labels/64/u-VKK5y0hj0U8B1xdawjxNcXciv-fwMK3VqEBWCn1oM.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/u-VKK5y0hj0U8B1xdawjxNcXciv-fwMK3VqEBWCn1oM.png",
            },
        },
    ],
    "troops": [
        {"name": "Barbarian", "level": 9, "maxLevel": 9, "village": "home"},
        {"name": "Archer", "level": 8, "maxLevel": 8, "village": "home"},
        {"name": "Goblin", "level": 7, "maxLevel": 8, "village": "home"},
        {"name": "Giant", "level": 9, "maxLevel": 9, "village": "home"},
        {"name": "Wall Breaker", "level": 8, "maxLevel": 9, "village": "home"},
        {"name": "Balloon", "level": 8, "maxLevel": 9, "village": "home"},
        {"name": "Wizard", "level": 8, "maxLevel": 9, "village": "home"},
        {"name": "Healer", "level": 5, "maxLevel": 6, "village": "home"},
        {"name": "Dragon", "level": 7, "maxLevel": 8, "village": "home"},
        {"name": "P.E.K.K.A", "level": 8, "maxLevel": 8, "village": "home"},
        {"name": "Minion", "level": 7, "maxLevel": 9, "village": "home"},
        {"name": "Hog Rider", "level": 7, "maxLevel": 10, "village": "home"},
        {"name": "Valkyrie", "level": 6, "maxLevel": 8, "village": "home"},
        {"name": "Golem", "level": 7, "maxLevel": 9, "village": "home"},
        {"name": "Witch", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Lava Hound", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Bowler", "level": 4, "maxLevel": 5, "village": "home"},
        {"name": "Baby Dragon", "level": 5, "maxLevel": 6, "village": "home"},
        {"name": "Miner", "level": 3, "maxLevel": 7, "village": "home"},
        {"name": "Super Barbarian", "level": 1, "maxLevel": 2, "village": "home"},
        {"name": "Super Wall Breaker", "level": 1, "maxLevel": 3, "village": "home"},
        {"name": "Super Giant", "level": 1, "maxLevel": 1, "village": "home"},
        {"name": "Raged Barbarian", "level": 14, "maxLevel": 18, "village": "builderBase"},
        {"name": "Sneaky Archer", "level": 10, "maxLevel": 18, "village": "builderBase"},
        {"name": "Beta Minion", "level": 14, "maxLevel": 18, "village": "builderBase"},
        {"name": "Boxer Giant", "level": 14, "maxLevel": 18, "village": "builderBase"},
        {"name": "Bomber", "level": 14, "maxLevel": 18, "village": "builderBase"},
        {"name": "Cannon Cart", "level": 14, "maxLevel": 18, "village": "builderBase"},
        {"name": "Drop Ship", "level": 3, "maxLevel": 18, "village": "builderBase"},
        {"name": "Baby Dragon", "level": 10, "maxLevel": 18, "village": "builderBase"},
        {"name": "Night Witch", "level": 1, "maxLevel": 18, "village": "builderBase"},
        {"name": "Wall Wrecker", "level": 1, "maxLevel": 3, "village": "home"},
        {"name": "Battle Blimp", "level": 1, "maxLevel": 3, "village": "home"},
        {"name": "Yeti", "level": 1, "maxLevel": 3, "village": "home"},
        {"name": "Sneaky Goblin", "level": 1, "maxLevel": 2, "village": "home"},
        {"name": "Ice Golem", "level": 3, "maxLevel": 5, "village": "home"},
        {"name": "Electro Dragon", "level": 3, "maxLevel": 4, "village": "home"},
        {"name": "Stone Slammer", "level": 1, "maxLevel": 3, "village": "home"},
    ],
    "heroes": [
        {"name": "Barbarian King", "level": 52, "maxLevel": 70, "village": "home"},
        {"name": "Archer Queen", "level": 65, "maxLevel": 70, "village": "home"},
        {"name": "Grand Warden", "level": 31, "maxLevel": 50, "village": "home"},
        {"name": "Battle Machine", "level": 20, "maxLevel": 30, "village": "builderBase"},
    ],
    "spells": [
        {"name": "Lightning Spell", "level": 7, "maxLevel": 7, "village": "home"},
        {"name": "Healing Spell", "level": 7, "maxLevel": 8, "village": "home"},
        {"name": "Rage Spell", "level": 6, "maxLevel": 6, "village": "home"},
        {"name": "Jump Spell", "level": 3, "maxLevel": 4, "village": "home"},
        {"name": "Freeze Spell", "level": 6, "maxLevel": 7, "village": "home"},
        {"name": "Poison Spell", "level": 5, "maxLevel": 7, "village": "home"},
        {"name": "Earthquake Spell", "level": 4, "maxLevel": 5, "village": "home"},
        {"name": "Haste Spell", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Clone Spell", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Skeleton Spell", "level": 4, "maxLevel": 7, "village": "home"},
        {"name": "Bat Spell", "level": 5, "maxLevel": 5, "village": "home"},
    ],
}

MOCK_CLAN_MEMBER = {
    "tag": "#2QJVVYRRU",
    "name": "xanada3",
    "role": "coLeader",
    "expLevel": 237,
    "league": {
        "id": 29000022,
        "name": "Legend League",
        "iconUrls": {
            "small": "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
            "tiny": "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
            "medium": "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
        },
    },
    "trophies": 5357,
    "versusTrophies": 5084,
    "clanRank": 1,
    "previousClanRank": 1,
    "donations": 12638,
    "donationsReceived": 11157,
}
