MOCK_CURRENT_WAR_IN_WAR = {
    "state": "inWar",
    "teamSize": 25,
    "preparationStartTime": "20200522T051229.000Z",
    "startTime": "20200523T043025.000Z",
    "endTime": "20200524T043025.000Z",
    "clan": {
        "tag": "#8J8QJ2LV",
        "name": "Reddit Ace",
        "badgeUrls": {
            "small": "https://api-assets.clashofclans.com/badges/70/V9EFxkaQ0GfKonWyn3gjimsnAMh3SPXFQeIkpKnNP7Y.png",
            "large": "https://api-assets.clashofclans.com/badges/512/V9EFxkaQ0GfKonWyn3gjimsnAMh3SPXFQeIkpKnNP7Y.png",
            "medium": "https://api-assets.clashofclans.com/badges/200/V9EFxkaQ0GfKonWyn3gjimsnAMh3SPXFQeIkpKnNP7Y.png",
        },
        "clanLevel": 19,
        "attacks": 43,
        "stars": 57,
        "destructionPercentage": 84.12,
        "members": [
            {
                "tag": "#8LY2YRJR",
                "name": "Sham",
                "townhallLevel": 13,
                "mapPosition": 1,
                "attacks": [
                    {
                        "attackerTag": "#8LY2YRJR",
                        "defenderTag": "#8LUL2Y90",
                        "stars": 2,
                        "destructionPercentage": 86,
                        "order": 69,
                    },
                    {
                        "attackerTag": "#8LY2YRJR",
                        "defenderTag": "#URRJQ8Y",
                        "stars": 1,
                        "destructionPercentage": 90,
                        "order": 72,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#9V8PUQLU",
                    "defenderTag": "#8LY2YRJR",
                    "stars": 2,
                    "destructionPercentage": 78,
                    "order": 38,
                },
            },
            {
                "tag": "#LL20PJ2V",
                "name": "Ze RenRen",
                "townhallLevel": 13,
                "mapPosition": 2,
                "attacks": [
                    {
                        "attackerTag": "#LL20PJ2V",
                        "defenderTag": "#2QGY0U0J2",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 1,
                    },
                    {
                        "attackerTag": "#LL20PJ2V",
                        "defenderTag": "#8LUL2Y90",
                        "stars": 2,
                        "destructionPercentage": 77,
                        "order": 17,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#298G2GVJ",
                    "defenderTag": "#LL20PJ2V",
                    "stars": 2,
                    "destructionPercentage": 86,
                    "order": 61,
                },
            },
            {
                "tag": "#2GR2RQ0YL",
                "name": "Cain Hubris 7",
                "townhallLevel": 13,
                "mapPosition": 3,
                "attacks": [
                    {
                        "attackerTag": "#2GR2RQ0YL",
                        "defenderTag": "#UJUGL8V8",
                        "stars": 1,
                        "destructionPercentage": 82,
                        "order": 42,
                    },
                    {
                        "attackerTag": "#2GR2RQ0YL",
                        "defenderTag": "#YLPYR8GL",
                        "stars": 1,
                        "destructionPercentage": 56,
                        "order": 51,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#298G2GVJ",
                    "defenderTag": "#2GR2RQ0YL",
                    "stars": 2,
                    "destructionPercentage": 93,
                    "order": 7,
                },
            },
            {
                "tag": "#GY2V9LLL",
                "name": "cole",
                "townhallLevel": 13,
                "mapPosition": 17,
                "attacks": [
                    {
                        "attackerTag": "#GY2V9LLL",
                        "defenderTag": "#2C2PV2RQP",
                        "stars": 2,
                        "destructionPercentage": 83,
                        "order": 28,
                    }
                ],
                "opponentAttacks": 7,
                "bestOpponentAttack": {
                    "attackerTag": "#G8VUYCG9",
                    "defenderTag": "#GY2V9LLL",
                    "stars": 2,
                    "destructionPercentage": 82,
                    "order": 39,
                },
            },
            {
                "tag": "#RJY2L8VV",
                "name": "Tyler Durden",
                "townhallLevel": 12,
                "mapPosition": 19,
                "attacks": [
                    {
                        "attackerTag": "#RJY2L8VV",
                        "defenderTag": "#JCVL2JPL",
                        "stars": 2,
                        "destructionPercentage": 60,
                        "order": 41,
                    },
                    {
                        "attackerTag": "#RJY2L8VV",
                        "defenderTag": "#C2QGL98U",
                        "stars": 1,
                        "destructionPercentage": 75,
                        "order": 79,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#2C2PV2RQP",
                    "defenderTag": "#RJY2L8VV",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 64,
                },
            },
            {
                "tag": "#JQLVJQUG",
                "name": "dylan",
                "townhallLevel": 11,
                "mapPosition": 24,
                "attacks": [
                    {
                        "attackerTag": "#JQLVJQUG",
                        "defenderTag": "#PVRCRV0R",
                        "stars": 2,
                        "destructionPercentage": 90,
                        "order": 20,
                    },
                    {
                        "attackerTag": "#JQLVJQUG",
                        "defenderTag": "#QCGQUR8P",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 60,
                    },
                ],
                "opponentAttacks": 3,
                "bestOpponentAttack": {
                    "attackerTag": "#JCVL2JPL",
                    "defenderTag": "#JQLVJQUG",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 26,
                },
            },
            {
                "tag": "#LLC2YYUL0",
                "name": "John BrawlSAQ",
                "townhallLevel": 5,
                "mapPosition": 25,
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#QCGQUR8P",
                    "defenderTag": "#LLC2YYUL0",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 3,
                },
            },
            {
                "tag": "#2LQQ0GC0Q",
                "name": "Cain Hubris 11",
                "townhallLevel": 13,
                "mapPosition": 12,
                "attacks": [
                    {
                        "attackerTag": "#2LQQ0GC0Q",
                        "defenderTag": "#URRJQ8Y",
                        "stars": 2,
                        "destructionPercentage": 98,
                        "order": 77,
                    },
                    {
                        "attackerTag": "#2LQQ0GC0Q",
                        "defenderTag": "#8LVG8RG8",
                        "stars": 2,
                        "destructionPercentage": 94,
                        "order": 78,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#YLPYR8GL",
                    "defenderTag": "#2LQQ0GC0Q",
                    "stars": 2,
                    "destructionPercentage": 90,
                    "order": 11,
                },
            },
            {
                "tag": "#YUPQ8UVPC",
                "name": "Quigonvodka",
                "townhallLevel": 13,
                "mapPosition": 13,
                "attacks": [
                    {
                        "attackerTag": "#YUPQ8UVPC",
                        "defenderTag": "#298G2GVJ",
                        "stars": 2,
                        "destructionPercentage": 64,
                        "order": 90,
                    }
                ],
                "opponentAttacks": 3,
                "bestOpponentAttack": {
                    "attackerTag": "#UJUGL8V8",
                    "defenderTag": "#YUPQ8UVPC",
                    "stars": 2,
                    "destructionPercentage": 66,
                    "order": 81,
                },
            },
            {
                "tag": "#YQ8J8LG2",
                "name": "MadDawg_123",
                "townhallLevel": 13,
                "mapPosition": 11,
                "attacks": [
                    {
                        "attackerTag": "#YQ8J8LG2",
                        "defenderTag": "#8GQ9LC0Q",
                        "stars": 2,
                        "destructionPercentage": 78,
                        "order": 55,
                    },
                    {
                        "attackerTag": "#YQ8J8LG2",
                        "defenderTag": "#JCVL2JPL",
                        "stars": 2,
                        "destructionPercentage": 97,
                        "order": 86,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#9RQLQ20U",
                    "defenderTag": "#YQ8J8LG2",
                    "stars": 2,
                    "destructionPercentage": 88,
                    "order": 14,
                },
            },
            {
                "tag": "#JQPP0RUV",
                "name": "_jazzy$$$",
                "townhallLevel": 11,
                "mapPosition": 23,
                "attacks": [
                    {
                        "attackerTag": "#JQPP0RUV",
                        "defenderTag": "#JCVL2JPL",
                        "stars": 1,
                        "destructionPercentage": 46,
                        "order": 91,
                    }
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#JCVL2JPL",
                    "defenderTag": "#JQPP0RUV",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 31,
                },
            },
            {
                "tag": "#8LCL80CJ8",
                "name": "Cain Hubris 5",
                "townhallLevel": 13,
                "mapPosition": 4,
                "attacks": [
                    {
                        "attackerTag": "#8LCL80CJ8",
                        "defenderTag": "#9V8PUQLU",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 40,
                    },
                    {
                        "attackerTag": "#8LCL80CJ8",
                        "defenderTag": "#22RR8V9VP",
                        "stars": 2,
                        "destructionPercentage": 84,
                        "order": 46,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#YLPYR8GL",
                    "defenderTag": "#8LCL80CJ8",
                    "stars": 2,
                    "destructionPercentage": 67,
                    "order": 12,
                },
            },
            {
                "tag": "#YQV8VJLC",
                "name": "TyWebb",
                "townhallLevel": 13,
                "mapPosition": 5,
                "attacks": [
                    {
                        "attackerTag": "#YQV8VJLC",
                        "defenderTag": "#2Y2G8YUJV",
                        "stars": 2,
                        "destructionPercentage": 72,
                        "order": 65,
                    },
                    {
                        "attackerTag": "#YQV8VJLC",
                        "defenderTag": "#8GQ9LC0Q",
                        "stars": 2,
                        "destructionPercentage": 73,
                        "order": 74,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#G8VUYCG9",
                    "defenderTag": "#YQV8VJLC",
                    "stars": 2,
                    "destructionPercentage": 63,
                    "order": 29,
                },
            },
            {
                "tag": "#8QRJGG0L",
                "name": "Cain Hubris 3",
                "townhallLevel": 13,
                "mapPosition": 6,
                "attacks": [
                    {
                        "attackerTag": "#8QRJGG0L",
                        "defenderTag": "#9P9PCL9V",
                        "stars": 2,
                        "destructionPercentage": 61,
                        "order": 48,
                    },
                    {
                        "attackerTag": "#8QRJGG0L",
                        "defenderTag": "#G8VUYCG9",
                        "stars": 1,
                        "destructionPercentage": 95,
                        "order": 59,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#9P9PCL9V",
                    "defenderTag": "#8QRJGG0L",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 35,
                },
            },
            {
                "tag": "#20LJLGQQG",
                "name": "Cain Hubris",
                "townhallLevel": 13,
                "mapPosition": 7,
                "attacks": [
                    {
                        "attackerTag": "#20LJLGQQG",
                        "defenderTag": "#UJUGL8V8",
                        "stars": 2,
                        "destructionPercentage": 74,
                        "order": 43,
                    },
                    {
                        "attackerTag": "#20LJLGQQG",
                        "defenderTag": "#G8VUYCG9",
                        "stars": 2,
                        "destructionPercentage": 71,
                        "order": 76,
                    },
                ],
                "opponentAttacks": 3,
                "bestOpponentAttack": {
                    "attackerTag": "#299RQQGC9",
                    "defenderTag": "#20LJLGQQG",
                    "stars": 2,
                    "destructionPercentage": 65,
                    "order": 70,
                },
            },
            {
                "tag": "#9J8QJVYVQ",
                "name": "Cain Hubris 2",
                "townhallLevel": 13,
                "mapPosition": 8,
                "attacks": [
                    {
                        "attackerTag": "#9J8QJVYVQ",
                        "defenderTag": "#22RR8V9VP",
                        "stars": 2,
                        "destructionPercentage": 64,
                        "order": 44,
                    },
                    {
                        "attackerTag": "#9J8QJVYVQ",
                        "defenderTag": "#YLPYR8GL",
                        "stars": 2,
                        "destructionPercentage": 54,
                        "order": 52,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#9RQLQ20U",
                    "defenderTag": "#9J8QJVYVQ",
                    "stars": 2,
                    "destructionPercentage": 94,
                    "order": 32,
                },
            },
            {
                "tag": "#Q2U2YVYG",
                "name": "SAQ",
                "townhallLevel": 13,
                "mapPosition": 15,
                "attacks": [
                    {
                        "attackerTag": "#Q2U2YVYG",
                        "defenderTag": "#9RQLQ20U",
                        "stars": 2,
                        "destructionPercentage": 79,
                        "order": 87,
                    }
                ],
                "opponentAttacks": 4,
                "bestOpponentAttack": {
                    "attackerTag": "#22RR8V9VP",
                    "defenderTag": "#Q2U2YVYG",
                    "stars": 2,
                    "destructionPercentage": 98,
                    "order": 92,
                },
            },
            {
                "tag": "#Y908UVP0",
                "name": "ProneToBone",
                "townhallLevel": 13,
                "mapPosition": 9,
                "attacks": [
                    {
                        "attackerTag": "#Y908UVP0",
                        "defenderTag": "#299RQQGC9",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 45,
                    },
                    {
                        "attackerTag": "#Y908UVP0",
                        "defenderTag": "#8LVG8RG8",
                        "stars": 2,
                        "destructionPercentage": 76,
                        "order": 54,
                    },
                ],
                "opponentAttacks": 3,
                "bestOpponentAttack": {
                    "attackerTag": "#2QGY0U0J2",
                    "defenderTag": "#Y908UVP0",
                    "stars": 2,
                    "destructionPercentage": 93,
                    "order": 63,
                },
            },
            {
                "tag": "#YJ0CPC9L",
                "name": "xNegotiator",
                "townhallLevel": 13,
                "mapPosition": 10,
                "attacks": [
                    {
                        "attackerTag": "#YJ0CPC9L",
                        "defenderTag": "#YUPQCL88",
                        "stars": 2,
                        "destructionPercentage": 72,
                        "order": 89,
                    }
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#9P9PCL9V",
                    "defenderTag": "#YJ0CPC9L",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 30,
                },
            },
            {
                "tag": "#8JYJGLQ09",
                "name": "Mini SAQ",
                "townhallLevel": 12,
                "mapPosition": 18,
                "attacks": [
                    {
                        "attackerTag": "#8JYJGLQ09",
                        "defenderTag": "#CPPUR22C",
                        "stars": 2,
                        "destructionPercentage": 78,
                        "order": 6,
                    },
                    {
                        "attackerTag": "#8JYJGLQ09",
                        "defenderTag": "#29YPGQ88",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 34,
                    },
                ],
                "opponentAttacks": 3,
                "bestOpponentAttack": {
                    "attackerTag": "#2C2PV2RQP",
                    "defenderTag": "#8JYJGLQ09",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 67,
                },
            },
            {
                "tag": "#28YUCG9V2",
                "name": "KraigBalla",
                "townhallLevel": 13,
                "mapPosition": 16,
                "attacks": [
                    {
                        "attackerTag": "#28YUCG9V2",
                        "defenderTag": "#2QRPCGJVC",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 62,
                    },
                    {
                        "attackerTag": "#28YUCG9V2",
                        "defenderTag": "#C2QGL98U",
                        "stars": 2,
                        "destructionPercentage": 84,
                        "order": 82,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#8GQ9LC0Q",
                    "defenderTag": "#28YUCG9V2",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 9,
                },
            },
            {
                "tag": "#L8LYUP9QJ",
                "name": "Noonan",
                "townhallLevel": 11,
                "mapPosition": 21,
                "attacks": [
                    {
                        "attackerTag": "#L8LYUP9QJ",
                        "defenderTag": "#PVRCRV0R",
                        "stars": 2,
                        "destructionPercentage": 84,
                        "order": 24,
                    },
                    {
                        "attackerTag": "#L8LYUP9QJ",
                        "defenderTag": "#QCGQUR8P",
                        "stars": 2,
                        "destructionPercentage": 74,
                        "order": 47,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#CPPUR22C",
                    "defenderTag": "#L8LYUP9QJ",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 23,
                },
            },
            {
                "tag": "#G9VYUVP9",
                "name": "Sham 2.0",
                "townhallLevel": 11,
                "mapPosition": 20,
                "attacks": [
                    {
                        "attackerTag": "#G9VYUVP9",
                        "defenderTag": "#PVRCRV0R",
                        "stars": 2,
                        "destructionPercentage": 75,
                        "order": 16,
                    },
                    {
                        "attackerTag": "#G9VYUVP9",
                        "defenderTag": "#QCGQUR8P",
                        "stars": 2,
                        "destructionPercentage": 98,
                        "order": 19,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#CPPUR22C",
                    "defenderTag": "#G9VYUVP9",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 18,
                },
            },
            {
                "tag": "#CJQV828U",
                "name": "Sturv",
                "townhallLevel": 13,
                "mapPosition": 14,
                "attacks": [
                    {
                        "attackerTag": "#CJQV828U",
                        "defenderTag": "#20L2P8RPC",
                        "stars": 2,
                        "destructionPercentage": 74,
                        "order": 50,
                    },
                    {
                        "attackerTag": "#CJQV828U",
                        "defenderTag": "#9RQLQ20U",
                        "stars": 2,
                        "destructionPercentage": 55,
                        "order": 80,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#2QGY0U0J2",
                    "defenderTag": "#CJQV828U",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 66,
                },
            },
            {
                "tag": "#GL0ULJ80",
                "name": "lil hubb",
                "townhallLevel": 11,
                "mapPosition": 22,
                "attacks": [
                    {
                        "attackerTag": "#GL0ULJ80",
                        "defenderTag": "#QCGQUR8P",
                        "stars": 2,
                        "destructionPercentage": 98,
                        "order": 13,
                    },
                    {
                        "attackerTag": "#GL0ULJ80",
                        "defenderTag": "#PVRCRV0R",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 58,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#2QRPCGJVC",
                    "defenderTag": "#GL0ULJ80",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 27,
                },
            },
        ],
    },
    "opponent": {
        "tag": "#P09YGYU2",
        "name": "TheDonkeyShow",
        "badgeUrls": {
            "small": "https://api-assets.clashofclans.com/badges/70/qBg4i0AbINbfJdanTA8TciCV3jw5RS33DMM94pw9mFU.png",
            "large": "https://api-assets.clashofclans.com/badges/512/qBg4i0AbINbfJdanTA8TciCV3jw5RS33DMM94pw9mFU.png",
            "medium": "https://api-assets.clashofclans.com/badges/200/qBg4i0AbINbfJdanTA8TciCV3jw5RS33DMM94pw9mFU.png",
        },
        "clanLevel": 20,
        "attacks": 49,
        "stars": 62,
        "destructionPercentage": 90.52,
        "members": [
            {
                "tag": "#2QGY0U0J2",
                "name": "jerry",
                "townhallLevel": 13,
                "mapPosition": 1,
                "attacks": [
                    {
                        "attackerTag": "#2QGY0U0J2",
                        "defenderTag": "#Y908UVP0",
                        "stars": 2,
                        "destructionPercentage": 93,
                        "order": 63,
                    },
                    {
                        "attackerTag": "#2QGY0U0J2",
                        "defenderTag": "#CJQV828U",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 66,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#LL20PJ2V",
                    "defenderTag": "#2QGY0U0J2",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 1,
                },
            },
            {
                "tag": "#YUPQCL88",
                "name": "100%vl that vl",
                "townhallLevel": 13,
                "mapPosition": 14,
                "attacks": [
                    {
                        "attackerTag": "#YUPQCL88",
                        "defenderTag": "#CJQV828U",
                        "stars": 2,
                        "destructionPercentage": 58,
                        "order": 22,
                    },
                    {
                        "attackerTag": "#YUPQCL88",
                        "defenderTag": "#GY2V9LLL",
                        "stars": 1,
                        "destructionPercentage": 54,
                        "order": 37,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#YJ0CPC9L",
                    "defenderTag": "#YUPQCL88",
                    "stars": 2,
                    "destructionPercentage": 72,
                    "order": 89,
                },
            },
            {
                "tag": "#UJUGL8V8",
                "name": "goPokesAJ",
                "townhallLevel": 13,
                "mapPosition": 11,
                "attacks": [
                    {
                        "attackerTag": "#UJUGL8V8",
                        "defenderTag": "#Q2U2YVYG",
                        "stars": 2,
                        "destructionPercentage": 57,
                        "order": 56,
                    },
                    {
                        "attackerTag": "#UJUGL8V8",
                        "defenderTag": "#YUPQ8UVPC",
                        "stars": 2,
                        "destructionPercentage": 66,
                        "order": 81,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#20LJLGQQG",
                    "defenderTag": "#UJUGL8V8",
                    "stars": 2,
                    "destructionPercentage": 74,
                    "order": 43,
                },
            },
            {
                "tag": "#2C2PV2RQP",
                "name": "kyle",
                "townhallLevel": 13,
                "mapPosition": 18,
                "attacks": [
                    {
                        "attackerTag": "#2C2PV2RQP",
                        "defenderTag": "#RJY2L8VV",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 64,
                    },
                    {
                        "attackerTag": "#2C2PV2RQP",
                        "defenderTag": "#8JYJGLQ09",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 67,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#GY2V9LLL",
                    "defenderTag": "#2C2PV2RQP",
                    "stars": 2,
                    "destructionPercentage": 83,
                    "order": 28,
                },
            },
            {
                "tag": "#8GQ9LC0Q",
                "name": "Soup",
                "townhallLevel": 13,
                "mapPosition": 17,
                "attacks": [
                    {
                        "attackerTag": "#8GQ9LC0Q",
                        "defenderTag": "#GY2V9LLL",
                        "stars": 1,
                        "destructionPercentage": 60,
                        "order": 8,
                    },
                    {
                        "attackerTag": "#8GQ9LC0Q",
                        "defenderTag": "#28YUCG9V2",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 9,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#YQ8J8LG2",
                    "defenderTag": "#8GQ9LC0Q",
                    "stars": 2,
                    "destructionPercentage": 78,
                    "order": 55,
                },
            },
            {
                "tag": "#CPPUR22C",
                "name": "Limiting Factor",
                "townhallLevel": 12,
                "mapPosition": 20,
                "attacks": [
                    {
                        "attackerTag": "#CPPUR22C",
                        "defenderTag": "#G9VYUVP9",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 18,
                    },
                    {
                        "attackerTag": "#CPPUR22C",
                        "defenderTag": "#L8LYUP9QJ",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 23,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#8JYJGLQ09",
                    "defenderTag": "#CPPUR22C",
                    "stars": 2,
                    "destructionPercentage": 78,
                    "order": 6,
                },
            },
            {
                "tag": "#8LUL2Y90",
                "name": "deisauce",
                "townhallLevel": 13,
                "mapPosition": 2,
                "attacks": [
                    {
                        "attackerTag": "#8LUL2Y90",
                        "defenderTag": "#20LJLGQQG",
                        "stars": 0,
                        "destructionPercentage": 40,
                        "order": 53,
                    },
                    {
                        "attackerTag": "#8LUL2Y90",
                        "defenderTag": "#GY2V9LLL",
                        "stars": 1,
                        "destructionPercentage": 43,
                        "order": 68,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#8LY2YRJR",
                    "defenderTag": "#8LUL2Y90",
                    "stars": 2,
                    "destructionPercentage": 86,
                    "order": 69,
                },
            },
            {
                "tag": "#9P9PCL9V",
                "name": "kernel",
                "townhallLevel": 13,
                "mapPosition": 3,
                "attacks": [
                    {
                        "attackerTag": "#9P9PCL9V",
                        "defenderTag": "#YJ0CPC9L",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 30,
                    },
                    {
                        "attackerTag": "#9P9PCL9V",
                        "defenderTag": "#8QRJGG0L",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 35,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#8QRJGG0L",
                    "defenderTag": "#9P9PCL9V",
                    "stars": 2,
                    "destructionPercentage": 61,
                    "order": 48,
                },
            },
            {
                "tag": "#G8VUYCG9",
                "name": "$tonecoldki11@",
                "townhallLevel": 13,
                "mapPosition": 4,
                "attacks": [
                    {
                        "attackerTag": "#G8VUYCG9",
                        "defenderTag": "#YQV8VJLC",
                        "stars": 2,
                        "destructionPercentage": 63,
                        "order": 29,
                    },
                    {
                        "attackerTag": "#G8VUYCG9",
                        "defenderTag": "#GY2V9LLL",
                        "stars": 2,
                        "destructionPercentage": 82,
                        "order": 39,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#20LJLGQQG",
                    "defenderTag": "#G8VUYCG9",
                    "stars": 2,
                    "destructionPercentage": 71,
                    "order": 76,
                },
            },
            {
                "tag": "#298G2GVJ",
                "name": "ILC01",
                "townhallLevel": 13,
                "mapPosition": 5,
                "attacks": [
                    {
                        "attackerTag": "#298G2GVJ",
                        "defenderTag": "#2GR2RQ0YL",
                        "stars": 2,
                        "destructionPercentage": 93,
                        "order": 7,
                    },
                    {
                        "attackerTag": "#298G2GVJ",
                        "defenderTag": "#LL20PJ2V",
                        "stars": 2,
                        "destructionPercentage": 86,
                        "order": 61,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#YUPQ8UVPC",
                    "defenderTag": "#298G2GVJ",
                    "stars": 2,
                    "destructionPercentage": 64,
                    "order": 90,
                },
            },
            {
                "tag": "#9RQLQ20U",
                "name": "KTM380Rider",
                "townhallLevel": 13,
                "mapPosition": 6,
                "attacks": [
                    {
                        "attackerTag": "#9RQLQ20U",
                        "defenderTag": "#YQ8J8LG2",
                        "stars": 2,
                        "destructionPercentage": 88,
                        "order": 14,
                    },
                    {
                        "attackerTag": "#9RQLQ20U",
                        "defenderTag": "#9J8QJVYVQ",
                        "stars": 2,
                        "destructionPercentage": 94,
                        "order": 32,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#Q2U2YVYG",
                    "defenderTag": "#9RQLQ20U",
                    "stars": 2,
                    "destructionPercentage": 79,
                    "order": 87,
                },
            },
            {
                "tag": "#2QRPCGJVC",
                "name": "Walter White™",
                "townhallLevel": 12,
                "mapPosition": 22,
                "attacks": [
                    {
                        "attackerTag": "#2QRPCGJVC",
                        "defenderTag": "#8JYJGLQ09",
                        "stars": 2,
                        "destructionPercentage": 64,
                        "order": 2,
                    },
                    {
                        "attackerTag": "#2QRPCGJVC",
                        "defenderTag": "#GL0ULJ80",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 27,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#28YUCG9V2",
                    "defenderTag": "#2QRPCGJVC",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 62,
                },
            },
            {
                "tag": "#29YPGQ88",
                "name": "DiceyDonkey",
                "townhallLevel": 12,
                "mapPosition": 23,
                "attacks": [
                    {
                        "attackerTag": "#29YPGQ88",
                        "defenderTag": "#JQLVJQUG",
                        "stars": 2,
                        "destructionPercentage": 98,
                        "order": 25,
                    },
                    {
                        "attackerTag": "#29YPGQ88",
                        "defenderTag": "#YUPQ8UVPC",
                        "stars": 1,
                        "destructionPercentage": 41,
                        "order": 33,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#8JYJGLQ09",
                    "defenderTag": "#29YPGQ88",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 34,
                },
            },
            {
                "tag": "#9V8PUQLU",
                "name": "Treks",
                "townhallLevel": 13,
                "mapPosition": 10,
                "attacks": [
                    {
                        "attackerTag": "#9V8PUQLU",
                        "defenderTag": "#8LY2YRJR",
                        "stars": 2,
                        "destructionPercentage": 78,
                        "order": 38,
                    },
                    {
                        "attackerTag": "#9V8PUQLU",
                        "defenderTag": "#YUPQ8UVPC",
                        "stars": 2,
                        "destructionPercentage": 65,
                        "order": 49,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#8LCL80CJ8",
                    "defenderTag": "#9V8PUQLU",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 40,
                },
            },
            {
                "tag": "#URRJQ8Y",
                "name": "DangerDonkey",
                "townhallLevel": 13,
                "mapPosition": 15,
                "attacks": [
                    {
                        "attackerTag": "#URRJQ8Y",
                        "defenderTag": "#Y908UVP0",
                        "stars": 2,
                        "destructionPercentage": 70,
                        "order": 73,
                    },
                    {
                        "attackerTag": "#URRJQ8Y",
                        "defenderTag": "#YQ8J8LG2",
                        "stars": 1,
                        "destructionPercentage": 49,
                        "order": 75,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#2LQQ0GC0Q",
                    "defenderTag": "#URRJQ8Y",
                    "stars": 2,
                    "destructionPercentage": 98,
                    "order": 77,
                },
            },
            {
                "tag": "#JCVL2JPL",
                "name": "DireDonkey",
                "townhallLevel": 12,
                "mapPosition": 21,
                "attacks": [
                    {
                        "attackerTag": "#JCVL2JPL",
                        "defenderTag": "#JQLVJQUG",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 26,
                    },
                    {
                        "attackerTag": "#JCVL2JPL",
                        "defenderTag": "#JQPP0RUV",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 31,
                    },
                ],
                "opponentAttacks": 3,
                "bestOpponentAttack": {
                    "attackerTag": "#YQ8J8LG2",
                    "defenderTag": "#JCVL2JPL",
                    "stars": 2,
                    "destructionPercentage": 97,
                    "order": 86,
                },
            },
            {
                "tag": "#22RR8V9VP",
                "name": "Yeth",
                "townhallLevel": 13,
                "mapPosition": 12,
                "attacks": [
                    {
                        "attackerTag": "#22RR8V9VP",
                        "defenderTag": "#GY2V9LLL",
                        "stars": 2,
                        "destructionPercentage": 60,
                        "order": 88,
                    },
                    {
                        "attackerTag": "#22RR8V9VP",
                        "defenderTag": "#Q2U2YVYG",
                        "stars": 2,
                        "destructionPercentage": 98,
                        "order": 92,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#8LCL80CJ8",
                    "defenderTag": "#22RR8V9VP",
                    "stars": 2,
                    "destructionPercentage": 84,
                    "order": 46,
                },
            },
            {
                "tag": "#C2QGL98U",
                "name": "SandBaggin’",
                "townhallLevel": 12,
                "mapPosition": 19,
                "attacks": [
                    {
                        "attackerTag": "#C2QGL98U",
                        "defenderTag": "#8JYJGLQ09",
                        "stars": 0,
                        "destructionPercentage": 48,
                        "order": 4,
                    },
                    {
                        "attackerTag": "#C2QGL98U",
                        "defenderTag": "#RJY2L8VV",
                        "stars": 1,
                        "destructionPercentage": 82,
                        "order": 5,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#28YUCG9V2",
                    "defenderTag": "#C2QGL98U",
                    "stars": 2,
                    "destructionPercentage": 84,
                    "order": 82,
                },
            },
            {
                "tag": "#8LVG8RG8",
                "name": "DreadfulDonkey",
                "townhallLevel": 13,
                "mapPosition": 13,
                "attacks": [
                    {
                        "attackerTag": "#8LVG8RG8",
                        "defenderTag": "#Q2U2YVYG",
                        "stars": 2,
                        "destructionPercentage": 74,
                        "order": 71,
                    },
                    {
                        "attackerTag": "#8LVG8RG8",
                        "defenderTag": "#GY2V9LLL",
                        "stars": 2,
                        "destructionPercentage": 69,
                        "order": 84,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#2LQQ0GC0Q",
                    "defenderTag": "#8LVG8RG8",
                    "stars": 2,
                    "destructionPercentage": 94,
                    "order": 78,
                },
            },
            {
                "tag": "#20L2P8RPC",
                "name": "Titeo",
                "townhallLevel": 13,
                "mapPosition": 9,
                "attacks": [
                    {
                        "attackerTag": "#20L2P8RPC",
                        "defenderTag": "#2LQQ0GC0Q",
                        "stars": 1,
                        "destructionPercentage": 53,
                        "order": 10,
                    },
                    {
                        "attackerTag": "#20L2P8RPC",
                        "defenderTag": "#Y908UVP0",
                        "stars": 1,
                        "destructionPercentage": 71,
                        "order": 36,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#CJQV828U",
                    "defenderTag": "#20L2P8RPC",
                    "stars": 2,
                    "destructionPercentage": 74,
                    "order": 50,
                },
            },
            {
                "tag": "#2Y2G8YUJV",
                "name": "Chip2",
                "townhallLevel": 13,
                "mapPosition": 7,
                "attacks": [
                    {
                        "attackerTag": "#2Y2G8YUJV",
                        "defenderTag": "#20LJLGQQG",
                        "stars": 1,
                        "destructionPercentage": 71,
                        "order": 57,
                    },
                    {
                        "attackerTag": "#2Y2G8YUJV",
                        "defenderTag": "#Q2U2YVYG",
                        "stars": 2,
                        "destructionPercentage": 64,
                        "order": 83,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#YQV8VJLC",
                    "defenderTag": "#2Y2G8YUJV",
                    "stars": 2,
                    "destructionPercentage": 72,
                    "order": 65,
                },
            },
            {
                "tag": "#PVRCRV0R",
                "name": "ConsiderPhlebas",
                "townhallLevel": 11,
                "mapPosition": 25,
                "attacks": [
                    {
                        "attackerTag": "#PVRCRV0R",
                        "defenderTag": "#JQLVJQUG",
                        "stars": 1,
                        "destructionPercentage": 81,
                        "order": 15,
                    },
                    {
                        "attackerTag": "#PVRCRV0R",
                        "defenderTag": "#JQPP0RUV",
                        "stars": 2,
                        "destructionPercentage": 68,
                        "order": 21,
                    },
                ],
                "opponentAttacks": 4,
                "bestOpponentAttack": {
                    "attackerTag": "#GL0ULJ80",
                    "defenderTag": "#PVRCRV0R",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 58,
                },
            },
            {
                "tag": "#YLPYR8GL",
                "name": "KingOssum",
                "townhallLevel": 13,
                "mapPosition": 8,
                "attacks": [
                    {
                        "attackerTag": "#YLPYR8GL",
                        "defenderTag": "#2LQQ0GC0Q",
                        "stars": 2,
                        "destructionPercentage": 90,
                        "order": 11,
                    },
                    {
                        "attackerTag": "#YLPYR8GL",
                        "defenderTag": "#8LCL80CJ8",
                        "stars": 2,
                        "destructionPercentage": 67,
                        "order": 12,
                    },
                ],
                "opponentAttacks": 2,
                "bestOpponentAttack": {
                    "attackerTag": "#9J8QJVYVQ",
                    "defenderTag": "#YLPYR8GL",
                    "stars": 2,
                    "destructionPercentage": 54,
                    "order": 52,
                },
            },
            {
                "tag": "#QCGQUR8P",
                "name": "TeddytheYeti",
                "townhallLevel": 11,
                "mapPosition": 24,
                "attacks": [
                    {
                        "attackerTag": "#QCGQUR8P",
                        "defenderTag": "#LLC2YYUL0",
                        "stars": 3,
                        "destructionPercentage": 100,
                        "order": 3,
                    }
                ],
                "opponentAttacks": 4,
                "bestOpponentAttack": {
                    "attackerTag": "#JQLVJQUG",
                    "defenderTag": "#QCGQUR8P",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 60,
                },
            },
            {
                "tag": "#299RQQGC9",
                "name": "DanDonkey",
                "townhallLevel": 13,
                "mapPosition": 16,
                "attacks": [
                    {
                        "attackerTag": "#299RQQGC9",
                        "defenderTag": "#20LJLGQQG",
                        "stars": 2,
                        "destructionPercentage": 65,
                        "order": 70,
                    },
                    {
                        "attackerTag": "#299RQQGC9",
                        "defenderTag": "#GY2V9LLL",
                        "stars": 1,
                        "destructionPercentage": 63,
                        "order": 85,
                    },
                ],
                "opponentAttacks": 1,
                "bestOpponentAttack": {
                    "attackerTag": "#Y908UVP0",
                    "defenderTag": "#299RQQGC9",
                    "stars": 3,
                    "destructionPercentage": 100,
                    "order": 45,
                },
            },
        ],
    },
}
