SEARCH_CLAN_MOCK = {
    "tag": "#G88CYQP",
    "name": "Reddit",
    "type": "inviteOnly",
    "description": "🛡️Reddit Clan System original clan\n⚔️Password 2 join @ bit.ly/RCSpassword\n🛡️Sun/Tues/Fri war search\n⚔️Recruiting non-rushed TH10+\n🛡️Feeder: Reddit 2.0 (any TH)\n⚔️Rules, discord @ cocreddit.reddit.com",
    "location": {"id": 32000172, "name": "Niue", "isCountry": True, "countryCode": "NU"},
    "badgeUrls": {
        "small": "https://api-assets.clashofclans.com/badges/70/gF1wdSrH72cPmAc9LG41nRZoUdI1apsF0ZxxEXtxVoA.png",
        "large": "https://api-assets.clashofclans.com/badges/512/gF1wdSrH72cPmAc9LG41nRZoUdI1apsF0ZxxEXtxVoA.png",
        "medium": "https://api-assets.clashofclans.com/badges/200/gF1wdSrH72cPmAc9LG41nRZoUdI1apsF0ZxxEXtxVoA.png",
    },
    "clanLevel": 19,
    "clanPoints": 37749,
    "clanVersusPoints": 38973,
    "requiredTrophies": 0,
    "warFrequency": "always",
    "warWinStreak": 0,
    "warWins": 518,
    "warTies": 6,
    "warLosses": 245,
    "isWarLogPublic": True,
    "warLeague": {"id": 48000013, "name": "Master League III"},
    "members": 40,
    "memberList": [
        {
            "tag": "#2QJVVYRRU",
            "name": "xanada3",
            "role": "coLeader",
            "expLevel": 237,
            "league": {
                "id": 29000022,
                "name": "Legend League",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                },
            },
            "trophies": 5357,
            "versusTrophies": 5084,
            "clanRank": 1,
            "previousClanRank": 1,
            "donations": 12638,
            "donationsReceived": 11157,
        },
        {
            "tag": "#9PJPP80RR",
            "name": "gus",
            "role": "member",
            "expLevel": 209,
            "league": {
                "id": 29000022,
                "name": "Legend League",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                },
            },
            "trophies": 5232,
            "versusTrophies": 4876,
            "clanRank": 2,
            "previousClanRank": 2,
            "donations": 14475,
            "donationsReceived": 9346,
        },
        {
            "tag": "#8CVL2L9R",
            "name": "gromit",
            "role": "leader",
            "expLevel": 233,
            "league": {
                "id": 29000022,
                "name": "Legend League",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                },
            },
            "trophies": 5120,
            "versusTrophies": 4544,
            "clanRank": 3,
            "previousClanRank": 3,
            "donations": 9814,
            "donationsReceived": 10246,
        },
        {
            "tag": "#Y02RYGP2Y",
            "name": "Rakeris",
            "role": "admin",
            "expLevel": 223,
            "league": {
                "id": 29000022,
                "name": "Legend League",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                },
            },
            "trophies": 5001,
            "versusTrophies": 4086,
            "clanRank": 4,
            "previousClanRank": 4,
            "donations": 8074,
            "donationsReceived": 9545,
        },
        {
            "tag": "#JGYCPCUJ",
            "name": "MasterNate",
            "role": "member",
            "expLevel": 215,
            "league": {
                "id": 29000021,
                "name": "Titan League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/qVCZmeYH0lS7Gaa6YoB7LrNly7bfw7fV_d4Vp2CU-gk.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/qVCZmeYH0lS7Gaa6YoB7LrNly7bfw7fV_d4Vp2CU-gk.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/qVCZmeYH0lS7Gaa6YoB7LrNly7bfw7fV_d4Vp2CU-gk.png",
                },
            },
            "trophies": 4863,
            "versusTrophies": 4793,
            "clanRank": 5,
            "previousClanRank": 5,
            "donations": 3691,
            "donationsReceived": 6868,
        },
        {
            "tag": "#P2U8PVQQ",
            "name": "plnsman112",
            "role": "coLeader",
            "expLevel": 219,
            "league": {
                "id": 29000021,
                "name": "Titan League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/qVCZmeYH0lS7Gaa6YoB7LrNly7bfw7fV_d4Vp2CU-gk.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/qVCZmeYH0lS7Gaa6YoB7LrNly7bfw7fV_d4Vp2CU-gk.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/qVCZmeYH0lS7Gaa6YoB7LrNly7bfw7fV_d4Vp2CU-gk.png",
                },
            },
            "trophies": 4860,
            "versusTrophies": 3234,
            "clanRank": 6,
            "previousClanRank": 6,
            "donations": 3036,
            "donationsReceived": 6421,
        },
        {
            "tag": "#PCU2JG8VV",
            "name": "KuruVader",
            "role": "member",
            "expLevel": 181,
            "league": {
                "id": 29000020,
                "name": "Titan League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/llpWocHlOoFliwyaEx5Z6dmoZG4u4NmxwpF-Jg7su7Q.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/llpWocHlOoFliwyaEx5Z6dmoZG4u4NmxwpF-Jg7su7Q.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/llpWocHlOoFliwyaEx5Z6dmoZG4u4NmxwpF-Jg7su7Q.png",
                },
            },
            "trophies": 4549,
            "versusTrophies": 4111,
            "clanRank": 7,
            "previousClanRank": 7,
            "donations": 3046,
            "donationsReceived": 3404,
        },
        {
            "tag": "#9YJR0QCUR",
            "name": "BetaQ",
            "role": "member",
            "expLevel": 189,
            "league": {
                "id": 29000020,
                "name": "Titan League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/llpWocHlOoFliwyaEx5Z6dmoZG4u4NmxwpF-Jg7su7Q.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/llpWocHlOoFliwyaEx5Z6dmoZG4u4NmxwpF-Jg7su7Q.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/llpWocHlOoFliwyaEx5Z6dmoZG4u4NmxwpF-Jg7su7Q.png",
                },
            },
            "trophies": 4385,
            "versusTrophies": 3615,
            "clanRank": 8,
            "previousClanRank": 8,
            "donations": 877,
            "donationsReceived": 2293,
        },
        {
            "tag": "#820GG8VVR",
            "name": "BaldGuyInACanoe",
            "role": "admin",
            "expLevel": 171,
            "league": {
                "id": 29000019,
                "name": "Titan League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/L-HrwYpFbDwWjdmhJQiZiTRa_zXPPOgUTdmbsaq4meo.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/L-HrwYpFbDwWjdmhJQiZiTRa_zXPPOgUTdmbsaq4meo.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/L-HrwYpFbDwWjdmhJQiZiTRa_zXPPOgUTdmbsaq4meo.png",
                },
            },
            "trophies": 4157,
            "versusTrophies": 2656,
            "clanRank": 9,
            "previousClanRank": 9,
            "donations": 2431,
            "donationsReceived": 5784,
        },
        {
            "tag": "#P0VLGGRP",
            "name": "resnepS0",
            "role": "admin",
            "expLevel": 182,
            "league": {
                "id": 29000019,
                "name": "Titan League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/L-HrwYpFbDwWjdmhJQiZiTRa_zXPPOgUTdmbsaq4meo.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/L-HrwYpFbDwWjdmhJQiZiTRa_zXPPOgUTdmbsaq4meo.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/L-HrwYpFbDwWjdmhJQiZiTRa_zXPPOgUTdmbsaq4meo.png",
                },
            },
            "trophies": 4088,
            "versusTrophies": 4411,
            "clanRank": 10,
            "previousClanRank": 10,
            "donations": 552,
            "donationsReceived": 785,
        },
        {
            "tag": "#20G0Y8YQC",
            "name": "xanada",
            "role": "coLeader",
            "expLevel": 213,
            "league": {
                "id": 29000018,
                "name": "Champion League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                },
            },
            "trophies": 3986,
            "versusTrophies": 4341,
            "clanRank": 11,
            "previousClanRank": 11,
            "donations": 2672,
            "donationsReceived": 2606,
        },
        {
            "tag": "#20YPUG20R",
            "name": "/\\BENZIE/\\",
            "role": "member",
            "expLevel": 176,
            "league": {
                "id": 29000018,
                "name": "Champion League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                },
            },
            "trophies": 3923,
            "versusTrophies": 3432,
            "clanRank": 12,
            "previousClanRank": 12,
            "donations": 1992,
            "donationsReceived": 1302,
        },
        {
            "tag": "#2YRRQ9R8",
            "name": "Shadrach",
            "role": "admin",
            "expLevel": 198,
            "league": {
                "id": 29000018,
                "name": "Champion League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                },
            },
            "trophies": 3861,
            "versusTrophies": 4455,
            "clanRank": 13,
            "previousClanRank": 13,
            "donations": 894,
            "donationsReceived": 1436,
        },
        {
            "tag": "#JY2YJUGP",
            "name": "Mithil",
            "role": "member",
            "expLevel": 160,
            "league": {
                "id": 29000017,
                "name": "Champion League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/kLWSSyq7vJiRiCantiKCoFuSJOxief6R1ky6AyfB8q0.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/kLWSSyq7vJiRiCantiKCoFuSJOxief6R1ky6AyfB8q0.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/kLWSSyq7vJiRiCantiKCoFuSJOxief6R1ky6AyfB8q0.png",
                },
            },
            "trophies": 3624,
            "versusTrophies": 2850,
            "clanRank": 14,
            "previousClanRank": 14,
            "donations": 148,
            "donationsReceived": 2188,
        },
        {
            "tag": "#RLVG2RRL",
            "name": "Recoome",
            "role": "member",
            "expLevel": 149,
            "league": {
                "id": 29000017,
                "name": "Champion League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/kLWSSyq7vJiRiCantiKCoFuSJOxief6R1ky6AyfB8q0.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/kLWSSyq7vJiRiCantiKCoFuSJOxief6R1ky6AyfB8q0.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/kLWSSyq7vJiRiCantiKCoFuSJOxief6R1ky6AyfB8q0.png",
                },
            },
            "trophies": 3602,
            "versusTrophies": 2389,
            "clanRank": 15,
            "previousClanRank": 15,
            "donations": 1511,
            "donationsReceived": 2010,
        },
        {
            "tag": "#G008Y90J",
            "name": "Ry_Guy",
            "role": "coLeader",
            "expLevel": 222,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 3516,
            "versusTrophies": 4702,
            "clanRank": 16,
            "previousClanRank": 16,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#920QY0VPR",
            "name": "XanadaJr",
            "role": "member",
            "expLevel": 176,
            "league": {
                "id": 29000016,
                "name": "Champion League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                },
            },
            "trophies": 3353,
            "versusTrophies": 4415,
            "clanRank": 17,
            "previousClanRank": 17,
            "donations": 126,
            "donationsReceived": 1538,
        },
        {
            "tag": "#GGPC2JGP",
            "name": "Beastofawesome",
            "role": "member",
            "expLevel": 174,
            "league": {
                "id": 29000016,
                "name": "Champion League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                },
            },
            "trophies": 3171,
            "versusTrophies": 4597,
            "clanRank": 18,
            "previousClanRank": 18,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#JY9J2Y99",
            "name": "Mathsman",
            "role": "member",
            "expLevel": 162,
            "league": {
                "id": 29000016,
                "name": "Champion League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                },
            },
            "trophies": 3137,
            "versusTrophies": 2716,
            "clanRank": 19,
            "previousClanRank": 19,
            "donations": 375,
            "donationsReceived": 575,
        },
        {
            "tag": "#2JVP2V8LP",
            "name": "Brad the Great",
            "role": "coLeader",
            "expLevel": 194,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 3087,
            "versusTrophies": 3364,
            "clanRank": 20,
            "previousClanRank": 20,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#RVYRL2PY",
            "name": "NameDropper",
            "role": "member",
            "expLevel": 165,
            "league": {
                "id": 29000014,
                "name": "Master League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/4wtS1stWZQ-1VJ5HaCuDPfdhTWjeZs_jPar_YPzK6Lg.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/4wtS1stWZQ-1VJ5HaCuDPfdhTWjeZs_jPar_YPzK6Lg.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/4wtS1stWZQ-1VJ5HaCuDPfdhTWjeZs_jPar_YPzK6Lg.png",
                },
            },
            "trophies": 2947,
            "versusTrophies": 2261,
            "clanRank": 21,
            "previousClanRank": 21,
            "donations": 3182,
            "donationsReceived": 5997,
        },
        {
            "tag": "#UVJ8290U",
            "name": "Will",
            "role": "member",
            "expLevel": 187,
            "league": {
                "id": 29000014,
                "name": "Master League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/4wtS1stWZQ-1VJ5HaCuDPfdhTWjeZs_jPar_YPzK6Lg.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/4wtS1stWZQ-1VJ5HaCuDPfdhTWjeZs_jPar_YPzK6Lg.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/4wtS1stWZQ-1VJ5HaCuDPfdhTWjeZs_jPar_YPzK6Lg.png",
                },
            },
            "trophies": 2879,
            "versusTrophies": 3503,
            "clanRank": 22,
            "previousClanRank": 22,
            "donations": 3982,
            "donationsReceived": 1712,
        },
        {
            "tag": "#PV2GJCJ8V",
            "name": "Queen Cee",
            "role": "member",
            "expLevel": 188,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2820,
            "versusTrophies": 4455,
            "clanRank": 23,
            "previousClanRank": 23,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#CJVQUGRU",
            "name": "Laneo",
            "role": "member",
            "expLevel": 152,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2691,
            "versusTrophies": 2423,
            "clanRank": 24,
            "previousClanRank": 25,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#Q8PLYGCY",
            "name": "FiremanMongo",
            "role": "admin",
            "expLevel": 166,
            "league": {
                "id": 29000013,
                "name": "Master League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                },
            },
            "trophies": 2659,
            "versusTrophies": 2692,
            "clanRank": 25,
            "previousClanRank": 26,
            "donations": 211,
            "donationsReceived": 1037,
        },
        {
            "tag": "#YQ0208LCC",
            "name": "XanadaJrJr",
            "role": "member",
            "expLevel": 131,
            "league": {
                "id": 29000013,
                "name": "Master League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                },
            },
            "trophies": 2581,
            "versusTrophies": 2466,
            "clanRank": 26,
            "previousClanRank": 28,
            "donations": 126,
            "donationsReceived": 457,
        },
        {
            "tag": "#PJ0RJG00Y",
            "name": "ry_guy",
            "role": "coLeader",
            "expLevel": 164,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2569,
            "versusTrophies": 4440,
            "clanRank": 27,
            "previousClanRank": 27,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#JLP0GG9P",
            "name": "imlilstar258",
            "role": "member",
            "expLevel": 130,
            "league": {
                "id": 29000012,
                "name": "Crystal League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/kSfTyNNVSvogX3dMvpFUTt72VW74w6vEsEFuuOV4osQ.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/kSfTyNNVSvogX3dMvpFUTt72VW74w6vEsEFuuOV4osQ.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/kSfTyNNVSvogX3dMvpFUTt72VW74w6vEsEFuuOV4osQ.png",
                },
            },
            "trophies": 2547,
            "versusTrophies": 2231,
            "clanRank": 28,
            "previousClanRank": 30,
            "donations": 40,
            "donationsReceived": 423,
        },
        {
            "tag": "#98QC2RP29",
            "name": "Giggawattz",
            "role": "member",
            "expLevel": 165,
            "league": {
                "id": 29000012,
                "name": "Crystal League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/kSfTyNNVSvogX3dMvpFUTt72VW74w6vEsEFuuOV4osQ.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/kSfTyNNVSvogX3dMvpFUTt72VW74w6vEsEFuuOV4osQ.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/kSfTyNNVSvogX3dMvpFUTt72VW74w6vEsEFuuOV4osQ.png",
                },
            },
            "trophies": 2540,
            "versusTrophies": 2596,
            "clanRank": 29,
            "previousClanRank": 29,
            "donations": 2491,
            "donationsReceived": 3315,
        },
        {
            "tag": "#8UQ90208R",
            "name": "thisBirdyBoi",
            "role": "member",
            "expLevel": 150,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2518,
            "versusTrophies": 3605,
            "clanRank": 30,
            "previousClanRank": 31,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#GRCUJG8Y",
            "name": "Kirigakure",
            "role": "member",
            "expLevel": 130,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2474,
            "versusTrophies": 2511,
            "clanRank": 31,
            "previousClanRank": 32,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#CJVY0PY9",
            "name": "Madz",
            "role": "member",
            "expLevel": 150,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2311,
            "versusTrophies": 2249,
            "clanRank": 32,
            "previousClanRank": 33,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#JPQR0C2J",
            "name": "CodLoverX",
            "role": "member",
            "expLevel": 121,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2209,
            "versusTrophies": 2210,
            "clanRank": 33,
            "previousClanRank": 34,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#88QPUVY2U",
            "name": "TooMuchZack",
            "role": "member",
            "expLevel": 131,
            "league": {
                "id": 29000010,
                "name": "Crystal League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/Hyqco7bHh0Q81xB8mSF_ZhjKnKcTmJ9QEq9QGlsxiKE.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/Hyqco7bHh0Q81xB8mSF_ZhjKnKcTmJ9QEq9QGlsxiKE.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/Hyqco7bHh0Q81xB8mSF_ZhjKnKcTmJ9QEq9QGlsxiKE.png",
                },
            },
            "trophies": 2131,
            "versusTrophies": 2487,
            "clanRank": 34,
            "previousClanRank": 35,
            "donations": 95,
            "donationsReceived": 0,
        },
        {
            "tag": "#QJ0JR2P9",
            "name": "Morpheus",
            "role": "admin",
            "expLevel": 173,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2122,
            "versusTrophies": 3609,
            "clanRank": 35,
            "previousClanRank": 36,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#202JVUGG2",
            "name": "ShadowKnight",
            "role": "member",
            "expLevel": 139,
            "league": {
                "id": 29000010,
                "name": "Crystal League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/Hyqco7bHh0Q81xB8mSF_ZhjKnKcTmJ9QEq9QGlsxiKE.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/Hyqco7bHh0Q81xB8mSF_ZhjKnKcTmJ9QEq9QGlsxiKE.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/Hyqco7bHh0Q81xB8mSF_ZhjKnKcTmJ9QEq9QGlsxiKE.png",
                },
            },
            "trophies": 2087,
            "versusTrophies": 2734,
            "clanRank": 36,
            "previousClanRank": 37,
            "donations": 1482,
            "donationsReceived": 1217,
        },
        {
            "tag": "#LUGG2PVU",
            "name": "SideFX",
            "role": "member",
            "expLevel": 131,
            "league": {
                "id": 29000009,
                "name": "Gold League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/CorhMY9ZmQvqXTZ4VYVuUgPNGSHsO0cEXEL5WYRmB2Y.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/CorhMY9ZmQvqXTZ4VYVuUgPNGSHsO0cEXEL5WYRmB2Y.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/CorhMY9ZmQvqXTZ4VYVuUgPNGSHsO0cEXEL5WYRmB2Y.png",
                },
            },
            "trophies": 1902,
            "versusTrophies": 1615,
            "clanRank": 37,
            "previousClanRank": 38,
            "donations": 0,
            "donationsReceived": 571,
        },
        {
            "tag": "#8Y8CU9U0",
            "name": "kara92",
            "role": "member",
            "expLevel": 133,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 1624,
            "versusTrophies": 2469,
            "clanRank": 38,
            "previousClanRank": 39,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#P9RURJ8VY",
            "name": "darek_V2.0",
            "role": "member",
            "expLevel": 135,
            "league": {
                "id": 29000007,
                "name": "Gold League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/vd4Lhz5b2I1P0cLH25B6q63JN3Wt1j2NTMhOYpMPQ4M.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/vd4Lhz5b2I1P0cLH25B6q63JN3Wt1j2NTMhOYpMPQ4M.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/vd4Lhz5b2I1P0cLH25B6q63JN3Wt1j2NTMhOYpMPQ4M.png",
                },
            },
            "trophies": 1357,
            "versusTrophies": 3165,
            "clanRank": 39,
            "previousClanRank": 40,
            "donations": 256,
            "donationsReceived": 938,
        },
        {
            "tag": "#2GCJ2QPU",
            "name": "darek",
            "role": "coLeader",
            "expLevel": 238,
            "league": {
                "id": 29000005,
                "name": "Silver League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/8OhXcwDJkenBH2kPH73eXftFOpHHRF-b32n0yrTqC44.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/8OhXcwDJkenBH2kPH73eXftFOpHHRF-b32n0yrTqC44.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/8OhXcwDJkenBH2kPH73eXftFOpHHRF-b32n0yrTqC44.png",
                },
            },
            "trophies": 1123,
            "versusTrophies": 5064,
            "clanRank": 40,
            "previousClanRank": 41,
            "donations": 15841,
            "donationsReceived": 2661,
        },
    ],
    "labels": [
        {
            "id": 56000000,
            "name": "Clan Wars",
            "iconUrls": {
                "small": "https://api-assets.clashofclans.com/labels/64/lXaIuoTlfoNOY5fKcQGeT57apz1KFWkN9-raxqIlMbE.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/lXaIuoTlfoNOY5fKcQGeT57apz1KFWkN9-raxqIlMbE.png",
            },
        },
        {
            "id": 56000001,
            "name": "Clan War League",
            "iconUrls": {
                "small": "https://api-assets.clashofclans.com/labels/64/5w60_3bdtYUe9SM6rkxBRyV_8VvWw_jTlDS5ieU3IsI.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/5w60_3bdtYUe9SM6rkxBRyV_8VvWw_jTlDS5ieU3IsI.png",
            },
        },
        {
            "id": 56000004,
            "name": "Clan Games",
            "iconUrls": {
                "small": "https://api-assets.clashofclans.com/labels/64/7qU7tQGERiVITVG0CPFov1-BnFldu4bMN2gXML5bLIU.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/7qU7tQGERiVITVG0CPFov1-BnFldu4bMN2gXML5bLIU.png",
            },
        },
    ],
    "_response_retry": 56,
}
