player_data = {
    "tag": "#28C80JQ20",
    "name": "jamie",
    "townHallLevel": 13,
    "townHallWeaponLevel": 5,
    "expLevel": 186,
    "trophies": 4982,
    "bestTrophies": 5043,
    "warStars": 1463,
    "attackWins": 59,
    "defenseWins": 5,
    "builderHallLevel": 9,
    "versusTrophies": 3035,
    "bestVersusTrophies": 3153,
    "versusBattleWins": 698,
    "role": "leader",
    "donations": 17578,
    "donationsReceived": 5437,
    "clan": {
        "tag": "#9VLLL2JV",
        "name": "Pigs Attack",
        "clanLevel": 14,
        "badgeUrls": {
            "small": "https://api-assets.clashofclans.com/badges/70/GbOaVZa-ImMfjicuh2ZYqiOyY-_PFbfACsAQsKcKgDE.png",
            "large": "https://api-assets.clashofclans.com/badges/512/GbOaVZa-ImMfjicuh2ZYqiOyY-_PFbfACsAQsKcKgDE.png",
            "medium": "https://api-assets.clashofclans.com/badges/200/GbOaVZa-ImMfjicuh2ZYqiOyY-_PFbfACsAQsKcKgDE.png",
        },
    },
    "league": {
        "id": 29000022,
        "name": "Legend League",
        "iconUrls": {
            "small": "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
            "tiny": "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
            "medium": "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
        },
    },
    "legendStatistics": {
        "legendTrophies": 23,
        "bestSeason": {"id": "2019-09", "rank": 330538, "trophies": 5004},
        "currentSeason": {"rank": 54, "trophies": 4982},
    },
    "achievements": [
        {
            "name": "Bigger Coffers",
            "stars": 3,
            "value": 13,
            "target": 10,
            "info": "Upgrade a Gold Storage to level 10",
            "completionInfo": "Highest Gold Storage level: 13",
            "village": "home",
        },
        {
            "name": "Get those Goblins!",
            "stars": 3,
            "value": 215,
            "target": 150,
            "info": "Win 150 Stars on the Campaign Map",
            "completionInfo": "Stars in Campaign Map: 215",
            "village": "home",
        },
        {
            "name": "Bigger & Better",
            "stars": 3,
            "value": 13,
            "target": 8,
            "info": "Upgrade Town Hall to level 8",
            "completionInfo": "Current Town Hall level: 13",
            "village": "home",
        },
        {
            "name": "Nice and Tidy",
            "stars": 3,
            "value": 4369,
            "target": 500,
            "info": "Remove 500 obstacles (trees, rocks, bushes)",
            "completionInfo": "Total obstacles removed: 4369",
            "village": "home",
        },
        {
            "name": "Release the Beasts",
            "stars": 3,
            "value": 1,
            "target": 1,
            "info": "Unlock Dragon in the Barracks",
            "completionInfo": None,
            "village": "home",
        },
        {
            "name": "Gold Grab",
            "stars": 3,
            "value": 738575624,
            "target": 100000000,
            "info": "Steal 100000000 gold",
            "completionInfo": "Total Gold looted: 738575624",
            "village": "home",
        },
        {
            "name": "Elixir Escapade",
            "stars": 3,
            "value": 717828020,
            "target": 100000000,
            "info": "Steal 100000000 elixir",
            "completionInfo": "Total Elixir looted: 717828020",
            "village": "home",
        },
        {
            "name": "Sweet Victory!",
            "stars": 3,
            "value": 5043,
            "target": 1250,
            "info": "Achieve a total of 1250 trophies in Multiplayer battles",
            "completionInfo": "Trophy record: 5043",
            "village": "home",
        },
        {
            "name": "Empire Builder",
            "stars": 3,
            "value": 9,
            "target": 4,
            "info": "Upgrade Clan Castle to level 4",
            "completionInfo": "Current Clan Castle level: 9",
            "village": "home",
        },
        {
            "name": "Wall Buster",
            "stars": 3,
            "value": 18268,
            "target": 2000,
            "info": "Destroy 2000 Walls in Multiplayer battles",
            "completionInfo": "Total walls destroyed: 18268",
            "village": "home",
        },
        {
            "name": "Humiliator",
            "stars": 3,
            "value": 4095,
            "target": 2000,
            "info": "Destroy 2000 Town Halls in Multiplayer battles",
            "completionInfo": "Total Town Halls destroyed: 4095",
            "village": "home",
        },
        {
            "name": "Union Buster",
            "stars": 3,
            "value": 8949,
            "target": 2500,
            "info": "Destroy 2500 Builder's Huts in Multiplayer battles",
            "completionInfo": "Total Builder's Huts destroyed: 8949",
            "village": "home",
        },
        {
            "name": "Conqueror",
            "stars": 2,
            "value": 4649,
            "target": 5000,
            "info": "Win 5000 Multiplayer battles",
            "completionInfo": "Total multiplayer battles won: 4649",
            "village": "home",
        },
        {
            "name": "Unbreakable",
            "stars": 2,
            "value": 1918,
            "target": 5000,
            "info": "Successfully defend against 5000 attacks",
            "completionInfo": "Total defenses won: 1918",
            "village": "home",
        },
        {
            "name": "Friend in Need",
            "stars": 3,
            "value": 190141,
            "target": 25000,
            "info": "Donate 25000 Clan Castle capacity worth of reinforcements",
            "completionInfo": "Total capacity donated: 190141",
            "village": "home",
        },
        {
            "name": "Mortar Mauler",
            "stars": 3,
            "value": 5741,
            "target": 5000,
            "info": "Destroy 5000 Mortars in Multiplayer battles",
            "completionInfo": "Total Mortars destroyed: 5741",
            "village": "home",
        },
        {
            "name": "Heroic Heist",
            "stars": 3,
            "value": 4756521,
            "target": 1000000,
            "info": "Steal 1000000 Dark Elixir",
            "completionInfo": "Total Dark Elixir looted: 4756521",
            "village": "home",
        },
        {
            "name": "League All-Star",
            "stars": 3,
            "value": 22,
            "target": 1,
            "info": "Become a Champion!",
            "completionInfo": None,
            "village": "home",
        },
        {
            "name": "X-Bow Exterminator",
            "stars": 3,
            "value": 4505,
            "target": 2500,
            "info": "Destroy 2500 X-Bows in Multiplayer battles",
            "completionInfo": "Total X-Bows destroyed: 4505",
            "village": "home",
        },
        {
            "name": "Firefighter",
            "stars": 2,
            "value": 2692,
            "target": 5000,
            "info": "Destroy 5000 Inferno Towers in Multiplayer battles",
            "completionInfo": "Total Inferno Towers destroyed: 2692",
            "village": "home",
        },
        {
            "name": "War Hero",
            "stars": 3,
            "value": 1463,
            "target": 1000,
            "info": "Score 1000 Stars for your clan in Clan War battles",
            "completionInfo": "Total Stars scored for clan in Clan War battles: 1463",
            "village": "home",
        },
        {
            "name": "Treasurer",
            "stars": 3,
            "value": 564936907,
            "target": 100000000,
            "info": "Collect 100000000 gold from the Treasury",
            "completionInfo": "Total gold collected in Clan War bonuses: 564936907",
            "village": "home",
        },
        {
            "name": "Anti-Artillery",
            "stars": 2,
            "value": 1056,
            "target": 2000,
            "info": "Destroy 2000 Eagle Artilleries in Multiplayer battles",
            "completionInfo": "Total Eagle Artilleries destroyed: 1056",
            "village": "home",
        },
        {
            "name": "Sharing is caring",
            "stars": 2,
            "value": 4053,
            "target": 10000,
            "info": "Donate 10000 spell storage capacity worth of spells",
            "completionInfo": "Total spell capacity donated: 4053",
            "village": "home",
        },
        {
            "name": "Keep your village safe",
            "stars": 0,
            "value": 0,
            "target": 1,
            "info": "Connect your account to a social network for safe keeping.",
            "completionInfo": "Completed!",
            "village": "home",
        },
        {
            "name": "Master Engineering",
            "stars": 3,
            "value": 9,
            "target": 8,
            "info": "Upgrade Builder Hall to level 8",
            "completionInfo": "Current Builder Hall level: 9",
            "village": "builderBase",
        },
        {
            "name": "Next Generation Model",
            "stars": 3,
            "value": 1,
            "target": 1,
            "info": "Unlock Super P.E.K.K.A in the Builder Barracks",
            "completionInfo": None,
            "village": "builderBase",
        },
        {
            "name": "Un-Build It",
            "stars": 2,
            "value": 691,
            "target": 2000,
            "info": "Destroy 2000 Builder Halls in Versus battles",
            "completionInfo": "Total Builder Halls destroyed: 691",
            "village": "builderBase",
        },
        {
            "name": "Champion Builder",
            "stars": 3,
            "value": 3153,
            "target": 3000,
            "info": "Achieve a total of 3000 trophies in Versus battles",
            "completionInfo": "Versus Trophy record: 3153",
            "village": "builderBase",
        },
        {
            "name": "High Gear",
            "stars": 3,
            "value": 3,
            "target": 3,
            "info": "Gear Up 3 buildings using the Master Builder",
            "completionInfo": "Total buildings geared up: 3",
            "village": "builderBase",
        },
        {
            "name": "Hidden Treasures",
            "stars": 3,
            "value": 1,
            "target": 1,
            "info": "Rebuild Battle Machine",
            "completionInfo": None,
            "village": "builderBase",
        },
        {
            "name": "Games Champion",
            "stars": 1,
            "value": 46935,
            "target": 50000,
            "info": "Earn 50000 points in Clan Games",
            "completionInfo": "Total Clan Games points: 46935",
            "village": "home",
        },
        {
            "name": "Dragon Slayer",
            "stars": 1,
            "value": 1,
            "target": 1,
            "info": "Slay the Giant Dragon",
            "completionInfo": None,
            "village": "home",
        },
        {
            "name": "War League Legend",
            "stars": 2,
            "value": 164,
            "target": 250,
            "info": "Score 250 Stars for your clan in War League battles",
            "completionInfo": "Total Stars scored for clan in War League battles: 164",
            "village": "home",
        },
        {
            "name": "Keep your village safe",
            "stars": 0,
            "value": 0,
            "target": 1,
            "info": "Connect your account to Supercell ID for safe keeping.",
            "completionInfo": "Completed!",
            "village": "home",
        },
        {
            "name": "Well Seasoned",
            "stars": 2,
            "value": 21320,
            "target": 50000,
            "info": "Earn 50000 points in Season Challenges",
            "completionInfo": "Total Season Challenges points: 21320",
            "village": "home",
        },
        {
            "name": "Shattered and Scattered",
            "stars": 1,
            "value": 243,
            "target": 400,
            "info": "Destroy 400 Scattershots in Multiplayer battles",
            "completionInfo": "Total Scattershots destroyed: 243",
            "village": "home",
        },
    ],
    "versusBattleWinCount": 698,
    "labels": [
        {
            "id": 57000008,
            "name": "Active Donator",
            "iconUrls": {
                "small": "https://api-assets.clashofclans.com/labels/64/MvL0LDt0yv9AI-Vevpu8yE5NAJUIV05Ofpsr4IfGRxQ.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/MvL0LDt0yv9AI-Vevpu8yE5NAJUIV05Ofpsr4IfGRxQ.png",
            },
        },
        {
            "id": 57000009,
            "name": "Active Daily",
            "iconUrls": {
                "small": "https://api-assets.clashofclans.com/labels/64/mcWhk0ii7CyjiiHOidhRofrSulpVrxjDu24cQtGCQbE.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/mcWhk0ii7CyjiiHOidhRofrSulpVrxjDu24cQtGCQbE.png",
            },
        },
        {
            "id": 57000011,
            "name": "Friendly",
            "iconUrls": {
                "small": "https://api-assets.clashofclans.com/labels/64/t0KZ4173i9vJFrD5F06-2TFNFk9UwJXxPjfutcG-dig.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/t0KZ4173i9vJFrD5F06-2TFNFk9UwJXxPjfutcG-dig.png",
            },
        },
    ],
    "troops": [
        {"name": "Barbarian", "level": 8, "maxLevel": 9, "village": "home"},
        {"name": "Archer", "level": 8, "maxLevel": 8, "village": "home"},
        {"name": "Goblin", "level": 6, "maxLevel": 8, "village": "home"},
        {"name": "Giant", "level": 9, "maxLevel": 9, "village": "home"},
        {"name": "Wall Breaker", "level": 5, "maxLevel": 9, "village": "home"},
        {"name": "Balloon", "level": 9, "maxLevel": 9, "village": "home"},
        {"name": "Wizard", "level": 9, "maxLevel": 9, "village": "home"},
        {"name": "Healer", "level": 4, "maxLevel": 6, "village": "home"},
        {"name": "Dragon", "level": 8, "maxLevel": 8, "village": "home"},
        {"name": "P.E.K.K.A", "level": 8, "maxLevel": 8, "village": "home"},
        {"name": "Minion", "level": 8, "maxLevel": 9, "village": "home"},
        {"name": "Hog Rider", "level": 7, "maxLevel": 10, "village": "home"},
        {"name": "Valkyrie", "level": 5, "maxLevel": 8, "village": "home"},
        {"name": "Golem", "level": 5, "maxLevel": 9, "village": "home"},
        {"name": "Witch", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Lava Hound", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Bowler", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Baby Dragon", "level": 4, "maxLevel": 6, "village": "home"},
        {"name": "Miner", "level": 1, "maxLevel": 7, "village": "home"},
        {"name": "Super Barbarian", "level": 1, "maxLevel": 2, "village": "home"},
        {"name": "Super Wall Breaker", "level": 1, "maxLevel": 3, "village": "home"},
        {"name": "Super Giant", "level": 1, "maxLevel": 1, "village": "home"},
        {"name": "Raged Barbarian", "level": 12, "maxLevel": 18, "village": "builderBase"},
        {"name": "Sneaky Archer", "level": 12, "maxLevel": 18, "village": "builderBase"},
        {"name": "Beta Minion", "level": 6, "maxLevel": 18, "village": "builderBase"},
        {"name": "Boxer Giant", "level": 8, "maxLevel": 18, "village": "builderBase"},
        {"name": "Bomber", "level": 4, "maxLevel": 18, "village": "builderBase"},
        {"name": "Super P.E.K.K.A", "level": 4, "maxLevel": 18, "village": "builderBase"},
        {"name": "Cannon Cart", "level": 18, "maxLevel": 18, "village": "builderBase"},
        {"name": "Drop Ship", "level": 2, "maxLevel": 18, "village": "builderBase"},
        {"name": "Baby Dragon", "level": 4, "maxLevel": 18, "village": "builderBase"},
        {"name": "Night Witch", "level": 6, "maxLevel": 18, "village": "builderBase"},
        {"name": "Wall Wrecker", "level": 1, "maxLevel": 3, "village": "home"},
        {"name": "Battle Blimp", "level": 1, "maxLevel": 3, "village": "home"},
        {"name": "Yeti", "level": 3, "maxLevel": 3, "village": "home"},
        {"name": "Sneaky Goblin", "level": 1, "maxLevel": 2, "village": "home"},
        {"name": "Ice Golem", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Electro Dragon", "level": 4, "maxLevel": 4, "village": "home"},
        {"name": "Stone Slammer", "level": 1, "maxLevel": 3, "village": "home"},
        {"name": "Hog Glider", "level": 1, "maxLevel": 18, "village": "builderBase"},
        {"name": "Siege Barracks", "level": 1, "maxLevel": 4, "village": "home"},
    ],
    "heroes": [
        {"name": "Barbarian King", "level": 21, "maxLevel": 70, "village": "home"},
        {"name": "Archer Queen", "level": 37, "maxLevel": 70, "village": "home"},
        {"name": "Grand Warden", "level": 17, "maxLevel": 50, "village": "home"},
        {"name": "Battle Machine", "level": 11, "maxLevel": 30, "village": "builderBase"},
        {"name": "Royal Champion", "level": 6, "maxLevel": 20, "village": "home"},
    ],
    "spells": [
        {"name": "Lightning Spell", "level": 5, "maxLevel": 7, "village": "home"},
        {"name": "Healing Spell", "level": 6, "maxLevel": 8, "village": "home"},
        {"name": "Rage Spell", "level": 6, "maxLevel": 6, "village": "home"},
        {"name": "Jump Spell", "level": 2, "maxLevel": 4, "village": "home"},
        {"name": "Freeze Spell", "level": 7, "maxLevel": 7, "village": "home"},
        {"name": "Poison Spell", "level": 2, "maxLevel": 7, "village": "home"},
        {"name": "Earthquake Spell", "level": 2, "maxLevel": 5, "village": "home"},
        {"name": "Haste Spell", "level": 5, "maxLevel": 5, "village": "home"},
        {"name": "Clone Spell", "level": 4, "maxLevel": 5, "village": "home"},
        {"name": "Skeleton Spell", "level": 1, "maxLevel": 7, "village": "home"},
        {"name": "Bat Spell", "level": 5, "maxLevel": 5, "village": "home"},
    ],
}

clan_data = {
    "tag": "#G88CYQP",
    "name": "Reddit",
    "type": "inviteOnly",
    "description": "🛡️Reddit Clan System original clan\n⚔️Password 2 join @ bit.ly/RCSpassword\n🛡️Sun/Tues/Fri war search\n⚔️Recruiting non-rushed TH10+\n🛡️Feeder: Reddit 2.0 (any TH)\n⚔️Rules, discord @ cocreddit.reddit.com",
    "location": {"id": 32000172, "name": "Niue", "isCountry": True, "countryCode": "NU"},
    "badgeUrls": {
        "small": "https://api-assets.clashofclans.com/badges/70/p4X6ZuNfAZ_ENKJOhy2u8og4UJJcKNYwuhr8TQkQ9Is.png",
        "large": "https://api-assets.clashofclans.com/badges/512/p4X6ZuNfAZ_ENKJOhy2u8og4UJJcKNYwuhr8TQkQ9Is.png",
        "medium": "https://api-assets.clashofclans.com/badges/200/p4X6ZuNfAZ_ENKJOhy2u8og4UJJcKNYwuhr8TQkQ9Is.png",
    },
    "clanLevel": 18,
    "clanPoints": 38960,
    "clanVersusPoints": 39006,
    "requiredTrophies": 0,
    "warFrequency": "always",
    "warWinStreak": 7,
    "warWins": 514,
    "warTies": 6,
    "warLosses": 241,
    "isWarLogPublic": True,
    "warLeague": {"id": 48000013, "name": "Master League III"},
    "members": 40,
    "memberList": [
        {
            "tag": "#2GCJ2QPU",
            "name": "darek",
            "role": "coLeader",
            "expLevel": 236,
            "league": {
                "id": 29000022,
                "name": "Legend League",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                },
            },
            "trophies": 5352,
            "versusTrophies": 5212,
            "clanRank": 1,
            "previousClanRank": 1,
            "donations": 26643,
            "donationsReceived": 15242,
        },
        {
            "tag": "#Y02RYGP2Y",
            "name": "Rakeris",
            "role": "admin",
            "expLevel": 222,
            "league": {
                "id": 29000022,
                "name": "Legend League",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                },
            },
            "trophies": 5174,
            "versusTrophies": 3908,
            "clanRank": 2,
            "previousClanRank": 2,
            "donations": 18157,
            "donationsReceived": 14255,
        },
        {
            "tag": "#9PJPP80RR",
            "name": "gus",
            "role": "member",
            "expLevel": 206,
            "league": {
                "id": 29000022,
                "name": "Legend League",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                },
            },
            "trophies": 5142,
            "versusTrophies": 4556,
            "clanRank": 3,
            "previousClanRank": 3,
            "donations": 2464,
            "donationsReceived": 1816,
        },
        {
            "tag": "#8CVL2L9R",
            "name": "gromit",
            "role": "leader",
            "expLevel": 231,
            "league": {
                "id": 29000022,
                "name": "Legend League",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                },
            },
            "trophies": 5106,
            "versusTrophies": 4576,
            "clanRank": 4,
            "previousClanRank": 4,
            "donations": 9625,
            "donationsReceived": 9901,
        },
        {
            "tag": "#2QJVVYRRU",
            "name": "xanada3",
            "role": "coLeader",
            "expLevel": 235,
            "league": {
                "id": 29000022,
                "name": "Legend League",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/R2zmhyqQ0_lKcDR5EyghXCxgyC9mm_mVMIjAbmGoZtw.png",
                },
            },
            "trophies": 5063,
            "versusTrophies": 4786,
            "clanRank": 5,
            "previousClanRank": 5,
            "donations": 10436,
            "donationsReceived": 9499,
        },
        {
            "tag": "#JGYCPCUJ",
            "name": "MasterNate",
            "role": "member",
            "expLevel": 214,
            "league": {
                "id": 29000021,
                "name": "Titan League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/qVCZmeYH0lS7Gaa6YoB7LrNly7bfw7fV_d4Vp2CU-gk.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/qVCZmeYH0lS7Gaa6YoB7LrNly7bfw7fV_d4Vp2CU-gk.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/qVCZmeYH0lS7Gaa6YoB7LrNly7bfw7fV_d4Vp2CU-gk.png",
                },
            },
            "trophies": 4789,
            "versusTrophies": 5000,
            "clanRank": 6,
            "previousClanRank": 6,
            "donations": 3340,
            "donationsReceived": 4801,
        },
        {
            "tag": "#P2U8PVQQ",
            "name": "plnsman112",
            "role": "coLeader",
            "expLevel": 217,
            "league": {
                "id": 29000021,
                "name": "Titan League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/qVCZmeYH0lS7Gaa6YoB7LrNly7bfw7fV_d4Vp2CU-gk.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/qVCZmeYH0lS7Gaa6YoB7LrNly7bfw7fV_d4Vp2CU-gk.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/qVCZmeYH0lS7Gaa6YoB7LrNly7bfw7fV_d4Vp2CU-gk.png",
                },
            },
            "trophies": 4719,
            "versusTrophies": 3284,
            "clanRank": 7,
            "previousClanRank": 7,
            "donations": 2416,
            "donationsReceived": 6486,
        },
        {
            "tag": "#9YJR0QCUR",
            "name": "BetaQ",
            "role": "member",
            "expLevel": 187,
            "league": {
                "id": 29000020,
                "name": "Titan League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/llpWocHlOoFliwyaEx5Z6dmoZG4u4NmxwpF-Jg7su7Q.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/llpWocHlOoFliwyaEx5Z6dmoZG4u4NmxwpF-Jg7su7Q.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/llpWocHlOoFliwyaEx5Z6dmoZG4u4NmxwpF-Jg7su7Q.png",
                },
            },
            "trophies": 4422,
            "versusTrophies": 3764,
            "clanRank": 8,
            "previousClanRank": 8,
            "donations": 790,
            "donationsReceived": 2490,
        },
        {
            "tag": "#PCU2JG8VV",
            "name": "KuruVader",
            "role": "member",
            "expLevel": 178,
            "league": {
                "id": 29000020,
                "name": "Titan League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/llpWocHlOoFliwyaEx5Z6dmoZG4u4NmxwpF-Jg7su7Q.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/llpWocHlOoFliwyaEx5Z6dmoZG4u4NmxwpF-Jg7su7Q.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/llpWocHlOoFliwyaEx5Z6dmoZG4u4NmxwpF-Jg7su7Q.png",
                },
            },
            "trophies": 4380,
            "versusTrophies": 4107,
            "clanRank": 9,
            "previousClanRank": 9,
            "donations": 1483,
            "donationsReceived": 233,
        },
        {
            "tag": "#P0VLGGRP",
            "name": "resnepS0",
            "role": "admin",
            "expLevel": 181,
            "league": {
                "id": 29000019,
                "name": "Titan League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/L-HrwYpFbDwWjdmhJQiZiTRa_zXPPOgUTdmbsaq4meo.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/L-HrwYpFbDwWjdmhJQiZiTRa_zXPPOgUTdmbsaq4meo.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/L-HrwYpFbDwWjdmhJQiZiTRa_zXPPOgUTdmbsaq4meo.png",
                },
            },
            "trophies": 4264,
            "versusTrophies": 4239,
            "clanRank": 10,
            "previousClanRank": 10,
            "donations": 2344,
            "donationsReceived": 2268,
        },
        {
            "tag": "#20G0Y8YQC",
            "name": "xanada",
            "role": "coLeader",
            "expLevel": 212,
            "league": {
                "id": 29000018,
                "name": "Champion League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                },
            },
            "trophies": 3923,
            "versusTrophies": 4340,
            "clanRank": 11,
            "previousClanRank": 14,
            "donations": 8100,
            "donationsReceived": 4246,
        },
        {
            "tag": "#20YPUG20R",
            "name": "/\\BENZIE/\\",
            "role": "member",
            "expLevel": 175,
            "league": {
                "id": 29000018,
                "name": "Champion League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                },
            },
            "trophies": 3923,
            "versusTrophies": 3345,
            "clanRank": 12,
            "previousClanRank": 12,
            "donations": 825,
            "donationsReceived": 122,
        },
        {
            "tag": "#820GG8VVR",
            "name": "BaldGuyInACanoe",
            "role": "admin",
            "expLevel": 168,
            "league": {
                "id": 29000018,
                "name": "Champion League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                },
            },
            "trophies": 3911,
            "versusTrophies": 2558,
            "clanRank": 13,
            "previousClanRank": 13,
            "donations": 1729,
            "donationsReceived": 4566,
        },
        {
            "tag": "#2YRRQ9R8",
            "name": "Shadrach",
            "role": "admin",
            "expLevel": 197,
            "league": {
                "id": 29000018,
                "name": "Champion League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/9v_04LHmd1LWq7IoY45dAdGhrBkrc2ZFMZVhe23PdCE.png",
                },
            },
            "trophies": 3900,
            "versusTrophies": 4016,
            "clanRank": 14,
            "previousClanRank": 11,
            "donations": 736,
            "donationsReceived": 1156,
        },
        {
            "tag": "#G008Y90J",
            "name": "Ry_Guy",
            "role": "coLeader",
            "expLevel": 222,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 3743,
            "versusTrophies": 4702,
            "clanRank": 15,
            "previousClanRank": 15,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#2JVP2V8LP",
            "name": "Brad the Great",
            "role": "coLeader",
            "expLevel": 194,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 3560,
            "versusTrophies": 3364,
            "clanRank": 16,
            "previousClanRank": 16,
            "donations": 25,
            "donationsReceived": 0,
        },
        {
            "tag": "#920QY0VPR",
            "name": "XanadaJr",
            "role": "member",
            "expLevel": 175,
            "league": {
                "id": 29000017,
                "name": "Champion League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/kLWSSyq7vJiRiCantiKCoFuSJOxief6R1ky6AyfB8q0.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/kLWSSyq7vJiRiCantiKCoFuSJOxief6R1ky6AyfB8q0.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/kLWSSyq7vJiRiCantiKCoFuSJOxief6R1ky6AyfB8q0.png",
                },
            },
            "trophies": 3439,
            "versusTrophies": 4622,
            "clanRank": 17,
            "previousClanRank": 17,
            "donations": 96,
            "donationsReceived": 2568,
        },
        {
            "tag": "#RLVG2RRL",
            "name": "Recoome",
            "role": "member",
            "expLevel": 146,
            "league": {
                "id": 29000017,
                "name": "Champion League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/kLWSSyq7vJiRiCantiKCoFuSJOxief6R1ky6AyfB8q0.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/kLWSSyq7vJiRiCantiKCoFuSJOxief6R1ky6AyfB8q0.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/kLWSSyq7vJiRiCantiKCoFuSJOxief6R1ky6AyfB8q0.png",
                },
            },
            "trophies": 3409,
            "versusTrophies": 2321,
            "clanRank": 18,
            "previousClanRank": 18,
            "donations": 619,
            "donationsReceived": 1742,
        },
        {
            "tag": "#JY9J2Y99",
            "name": "Mathsman",
            "role": "member",
            "expLevel": 161,
            "league": {
                "id": 29000016,
                "name": "Champion League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                },
            },
            "trophies": 3352,
            "versusTrophies": 2698,
            "clanRank": 19,
            "previousClanRank": 19,
            "donations": 1236,
            "donationsReceived": 1970,
        },
        {
            "tag": "#JY2YJUGP",
            "name": "Mithil",
            "role": "member",
            "expLevel": 158,
            "league": {
                "id": 29000016,
                "name": "Champion League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                },
            },
            "trophies": 3298,
            "versusTrophies": 2766,
            "clanRank": 20,
            "previousClanRank": 20,
            "donations": 139,
            "donationsReceived": 1942,
        },
        {
            "tag": "#CJVQUGRU",
            "name": "Laneo",
            "role": "member",
            "expLevel": 152,
            "league": {
                "id": 29000016,
                "name": "Champion League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/JmmTbspV86xBigM7OP5_SjsEDPuE7oXjZC9aOy8xO3s.png",
                },
            },
            "trophies": 3123,
            "versusTrophies": 2423,
            "clanRank": 21,
            "previousClanRank": 21,
            "donations": 61,
            "donationsReceived": 495,
        },
        {
            "tag": "#RVYRL2PY",
            "name": "NameDropper",
            "role": "member",
            "expLevel": 162,
            "league": {
                "id": 29000015,
                "name": "Master League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/olUfFb1wscIH8hqECAdWbdB6jPm9R8zzEyHIzyBgRXc.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/olUfFb1wscIH8hqECAdWbdB6jPm9R8zzEyHIzyBgRXc.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/olUfFb1wscIH8hqECAdWbdB6jPm9R8zzEyHIzyBgRXc.png",
                },
            },
            "trophies": 3113,
            "versusTrophies": 2302,
            "clanRank": 22,
            "previousClanRank": 22,
            "donations": 1712,
            "donationsReceived": 2482,
        },
        {
            "tag": "#8UQ90208R",
            "name": "thisBirdyBoi",
            "role": "member",
            "expLevel": 150,
            "league": {
                "id": 29000015,
                "name": "Master League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/olUfFb1wscIH8hqECAdWbdB6jPm9R8zzEyHIzyBgRXc.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/olUfFb1wscIH8hqECAdWbdB6jPm9R8zzEyHIzyBgRXc.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/olUfFb1wscIH8hqECAdWbdB6jPm9R8zzEyHIzyBgRXc.png",
                },
            },
            "trophies": 3053,
            "versusTrophies": 3605,
            "clanRank": 23,
            "previousClanRank": 23,
            "donations": 1835,
            "donationsReceived": 422,
        },
        {
            "tag": "#8V2PC0CU9",
            "name": "Lotus",
            "role": "member",
            "expLevel": 153,
            "league": {
                "id": 29000015,
                "name": "Master League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/olUfFb1wscIH8hqECAdWbdB6jPm9R8zzEyHIzyBgRXc.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/olUfFb1wscIH8hqECAdWbdB6jPm9R8zzEyHIzyBgRXc.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/olUfFb1wscIH8hqECAdWbdB6jPm9R8zzEyHIzyBgRXc.png",
                },
            },
            "trophies": 3009,
            "versusTrophies": 3657,
            "clanRank": 24,
            "previousClanRank": 25,
            "donations": 353,
            "donationsReceived": 134,
        },
        {
            "tag": "#PV2GJCJ8V",
            "name": "Queen Cee",
            "role": "member",
            "expLevel": 188,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 3000,
            "versusTrophies": 4455,
            "clanRank": 25,
            "previousClanRank": 24,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#UVJ8290U",
            "name": "Will",
            "role": "member",
            "expLevel": 186,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2905,
            "versusTrophies": 3518,
            "clanRank": 26,
            "previousClanRank": 26,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#YPL88RU0P",
            "name": "Ysera",
            "role": "member",
            "expLevel": 144,
            "league": {
                "id": 29000014,
                "name": "Master League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/4wtS1stWZQ-1VJ5HaCuDPfdhTWjeZs_jPar_YPzK6Lg.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/4wtS1stWZQ-1VJ5HaCuDPfdhTWjeZs_jPar_YPzK6Lg.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/4wtS1stWZQ-1VJ5HaCuDPfdhTWjeZs_jPar_YPzK6Lg.png",
                },
            },
            "trophies": 2822,
            "versusTrophies": 3550,
            "clanRank": 27,
            "previousClanRank": 28,
            "donations": 129,
            "donationsReceived": 0,
        },
        {
            "tag": "#GGPC2JGP",
            "name": "Beastofawesome",
            "role": "member",
            "expLevel": 172,
            "league": {
                "id": 29000014,
                "name": "Master League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/4wtS1stWZQ-1VJ5HaCuDPfdhTWjeZs_jPar_YPzK6Lg.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/4wtS1stWZQ-1VJ5HaCuDPfdhTWjeZs_jPar_YPzK6Lg.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/4wtS1stWZQ-1VJ5HaCuDPfdhTWjeZs_jPar_YPzK6Lg.png",
                },
            },
            "trophies": 2787,
            "versusTrophies": 4597,
            "clanRank": 28,
            "previousClanRank": 27,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#PJ0RJG00Y",
            "name": "ry_guy",
            "role": "coLeader",
            "expLevel": 164,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2679,
            "versusTrophies": 4440,
            "clanRank": 29,
            "previousClanRank": 29,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#98QC2RP29",
            "name": "Giggawattz",
            "role": "member",
            "expLevel": 162,
            "league": {
                "id": 29000013,
                "name": "Master League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                },
            },
            "trophies": 2647,
            "versusTrophies": 2310,
            "clanRank": 30,
            "previousClanRank": 31,
            "donations": 2790,
            "donationsReceived": 5333,
        },
        {
            "tag": "#GRCUJG8Y",
            "name": "Kirigakure",
            "role": "member",
            "expLevel": 130,
            "league": {
                "id": 29000013,
                "name": "Master League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                },
            },
            "trophies": 2642,
            "versusTrophies": 2511,
            "clanRank": 31,
            "previousClanRank": 30,
            "donations": 40,
            "donationsReceived": 70,
        },
        {
            "tag": "#YQ0208LCC",
            "name": "XanadaJrJr",
            "role": "member",
            "expLevel": 131,
            "league": {
                "id": 29000013,
                "name": "Master League III",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/pSXfKvBKSgtvfOY3xKkgFaRQi0WcE28s3X35ywbIluY.png",
                },
            },
            "trophies": 2590,
            "versusTrophies": 2458,
            "clanRank": 32,
            "previousClanRank": 32,
            "donations": 123,
            "donationsReceived": 792,
        },
        {
            "tag": "#JLP0GG9P",
            "name": "imlilstar258",
            "role": "member",
            "expLevel": 130,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2518,
            "versusTrophies": 2303,
            "clanRank": 33,
            "previousClanRank": 33,
            "donations": 12,
            "donationsReceived": 35,
        },
        {
            "tag": "#Q8PLYGCY",
            "name": "FiremanMongo",
            "role": "admin",
            "expLevel": 166,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2453,
            "versusTrophies": 2692,
            "clanRank": 34,
            "previousClanRank": 34,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#CJVY0PY9",
            "name": "Madz",
            "role": "member",
            "expLevel": 150,
            "league": {
                "id": 29000012,
                "name": "Crystal League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/kSfTyNNVSvogX3dMvpFUTt72VW74w6vEsEFuuOV4osQ.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/kSfTyNNVSvogX3dMvpFUTt72VW74w6vEsEFuuOV4osQ.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/kSfTyNNVSvogX3dMvpFUTt72VW74w6vEsEFuuOV4osQ.png",
                },
            },
            "trophies": 2396,
            "versusTrophies": 2249,
            "clanRank": 35,
            "previousClanRank": 35,
            "donations": 235,
            "donationsReceived": 167,
        },
        {
            "tag": "#JPQR0C2J",
            "name": "CodLoverX",
            "role": "member",
            "expLevel": 120,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2311,
            "versusTrophies": 2210,
            "clanRank": 36,
            "previousClanRank": 36,
            "donations": 35,
            "donationsReceived": 0,
        },
        {
            "tag": "#QJ0JR2P9",
            "name": "Morpheus",
            "role": "admin",
            "expLevel": 173,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 2122,
            "versusTrophies": 3609,
            "clanRank": 37,
            "previousClanRank": 37,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#LUGG2PVU",
            "name": "SideFX",
            "role": "member",
            "expLevel": 130,
            "league": {
                "id": 29000008,
                "name": "Gold League II",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/Y6CveuHmPM_oiOic2Yet0rYL9AFRYW0WA0u2e44-YbM.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/Y6CveuHmPM_oiOic2Yet0rYL9AFRYW0WA0u2e44-YbM.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/Y6CveuHmPM_oiOic2Yet0rYL9AFRYW0WA0u2e44-YbM.png",
                },
            },
            "trophies": 1728,
            "versusTrophies": 1615,
            "clanRank": 38,
            "previousClanRank": 38,
            "donations": 18,
            "donationsReceived": 206,
        },
        {
            "tag": "#8Y8CU9U0",
            "name": "kara92",
            "role": "member",
            "expLevel": 133,
            "league": {
                "id": 29000000,
                "name": "Unranked",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/e--YMyIexEQQhE4imLoJcwhYn6Uy8KqlgyY3_kFV6t4.png",
                },
            },
            "trophies": 1624,
            "versusTrophies": 2469,
            "clanRank": 39,
            "previousClanRank": 39,
            "donations": 0,
            "donationsReceived": 0,
        },
        {
            "tag": "#P9RURJ8VY",
            "name": "darek_V2.0",
            "role": "member",
            "expLevel": 133,
            "league": {
                "id": 29000006,
                "name": "Silver League I",
                "iconUrls": {
                    "small": "https://api-assets.clashofclans.com/leagues/72/nvrBLvCK10elRHmD1g9w5UU1flDRMhYAojMB2UbYfPs.png",
                    "tiny": "https://api-assets.clashofclans.com/leagues/36/nvrBLvCK10elRHmD1g9w5UU1flDRMhYAojMB2UbYfPs.png",
                    "medium": "https://api-assets.clashofclans.com/leagues/288/nvrBLvCK10elRHmD1g9w5UU1flDRMhYAojMB2UbYfPs.png",
                },
            },
            "trophies": 1197,
            "versusTrophies": 3104,
            "clanRank": 40,
            "previousClanRank": 40,
            "donations": 108,
            "donationsReceived": 966,
        },
    ],
    "labels": [
        {
            "id": 56000000,
            "name": "Clan Wars",
            "iconUrls": {
                "small": "https://api-assets.clashofclans.com/labels/64/lXaIuoTlfoNOY5fKcQGeT57apz1KFWkN9-raxqIlMbE.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/lXaIuoTlfoNOY5fKcQGeT57apz1KFWkN9-raxqIlMbE.png",
            },
        },
        {
            "id": 56000001,
            "name": "Clan War League",
            "iconUrls": {
                "small": "https://api-assets.clashofclans.com/labels/64/5w60_3bdtYUe9SM6rkxBRyV_8VvWw_jTlDS5ieU3IsI.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/5w60_3bdtYUe9SM6rkxBRyV_8VvWw_jTlDS5ieU3IsI.png",
            },
        },
        {
            "id": 56000004,
            "name": "Clan Games",
            "iconUrls": {
                "small": "https://api-assets.clashofclans.com/labels/64/7qU7tQGERiVITVG0CPFov1-BnFldu4bMN2gXML5bLIU.png",
                "medium": "https://api-assets.clashofclans.com/labels/128/7qU7tQGERiVITVG0CPFov1-BnFldu4bMN2gXML5bLIU.png",
            },
        },
    ],
}

from coc.clans import Clan
from coc.players import Player
from pympler import asizeof
import cProfile as profile

clan = Clan(data=clan_data, client=None)
members = clan.members[0]
# print(asizeof.asizeof(clan, above=200, stats=1))


class Player2(Player):
    def _from_data(self, data):
        self.donations = data["donations"]


def load_clan():
    return clan.members


#
# def load_player():
#     return Player(data=player_data, client=None)
import time


def load_player():
    player = Player2(data=player_data, client=None)


#  ach = player.achievements

s = time.perf_counter()
load_clan()
print((time.perf_counter() - s) * 1000)
s = time.perf_counter()
load_clan()
print((time.perf_counter() - s) * 1000)
