"""Auto-generated constants from static game data."""

ELIXIR_TROOP_ORDER = [
    'Barbarian',
    'Archer',
    'Goblin',
    'Giant',
    'Wall Breaker',
    'Balloon',
    'Wizard',
    'Healer',
    'Dragon',
    'P.E.K.K.A',
    'Baby Dragon',
    'Miner',
    'Yeti',
    'Electro Dragon',
    'Dragon Rider',
    'Electro Titan',
    'Root Rider',
    'Thrower',
    'Meteor Golem',
]

DARK_ELIXIR_TROOP_ORDER = [
    'Minion',
    'Hog Rider',
    'Valkyrie',
    'Golem',
    'Witch',
    'Lava Hound',
    'Bowler',
    'Ice Golem',
    'Headhunter',
    'Apprentice Warden',
    'Druid',
    'Furnace',
]

HV_TROOP_ORDER = ELIXIR_TROOP_ORDER + DARK_ELIXIR_TROOP_ORDER

SIEGE_MACHINE_ORDER = [
    'Wall Wrecker',
    'Battle Blimp',
    'Stone Slammer',
    'Siege Barracks',
    'Log Launcher',
    'Flame Flinger',
    'Battle Drill',
    'Troop Launcher',
]

SUPER_TROOP_ORDER = [
    {'_id': 4000026, 'name': 'Super Barbarian', 'info': 'Superior in health, power, speed and most importantly, hair, the Super Barbarians are what regular Barbarians dream of becoming!', 'TID': {'name': 'TID_CHARACTER_ELITE_BARBARIAN', 'info': 'TID_CHARACTER_INFO_ELITE_BARBARIAN'}, 'production_building': 'Barracks', 'production_building_level': 1, 'upgrade_resource': 'Elixir', 'is_flying': False, 'is_air_targeting': False, 'is_ground_targeting': True, 'movement_speed': 250, 'attack_speed': 800, 'attack_range': 60, 'housing_space': 5, 'village': 'home', 'super_troop': {'original_id': 4000000, 'original_min_level': 7}, 'levels': [{'level': 5, 'hitpoints': 700, 'dps': 120, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 6, 'required_townhall': 8}, {'level': 6, 'hitpoints': 800, 'dps': 140, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 7, 'hitpoints': 900, 'dps': 160, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 8, 'hitpoints': 1000, 'dps': 180, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 9, 'hitpoints': 1100, 'dps': 200, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 10, 'hitpoints': 1200, 'dps': 220, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 12, 'required_townhall': 14}, {'level': 11, 'hitpoints': 1300, 'dps': 240, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 12, 'hitpoints': 1350, 'dps': 250, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}]},
    {'_id': 4000027, 'name': 'Super Archer', 'info': 'Having achieved serious arm strength, the Super Archer can now threaten targets several buildings away.', 'TID': {'name': 'TID_CHARACTER_MAGIC_ARCHER', 'info': 'TID_CHARACTER_INFO_MAGIC_ARCHER'}, 'production_building': 'Barracks', 'production_building_level': 2, 'upgrade_resource': 'Elixir', 'is_flying': False, 'is_air_targeting': True, 'is_ground_targeting': True, 'movement_speed': 300, 'attack_speed': 1500, 'attack_range': 600, 'housing_space': 12, 'village': 'home', 'super_troop': {'original_id': 4000001, 'original_min_level': 7}, 'levels': [{'level': 5, 'hitpoints': 300, 'dps': 84, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 6, 'required_townhall': 8}, {'level': 6, 'hitpoints': 350, 'dps': 96, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 7, 'hitpoints': 400, 'dps': 108, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 8, 'hitpoints': 450, 'dps': 120, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 9, 'hitpoints': 510, 'dps': 132, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 10, 'hitpoints': 550, 'dps': 144, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 12, 'required_townhall': 14}, {'level': 11, 'hitpoints': 575, 'dps': 156, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 12, 'hitpoints': 600, 'dps': 162, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}, {'level': 13, 'hitpoints': 625, 'dps': 166, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 15, 'required_townhall': 17}]},
    {'_id': 4000028, 'name': 'Super Wall Breaker', 'info': 'Who knew that rolling was that much superior to running? Super Wall Breakers use pre-ignited bombs that blow up under all circumstances! No more duds!', 'TID': {'name': 'TID_CHARACTER_ELITE_WALLBREAKER', 'info': 'TID_CHARACTER_INFO_ELITE_WALLBREAKER'}, 'production_building': 'Barracks', 'production_building_level': 5, 'upgrade_resource': 'Elixir', 'is_flying': False, 'is_air_targeting': False, 'is_ground_targeting': True, 'movement_speed': 350, 'attack_speed': 1000, 'attack_range': 60, 'housing_space': 8, 'village': 'home', 'super_troop': {'original_id': 4000004, 'original_min_level': 6}, 'levels': [{'level': 5, 'hitpoints': 250, 'dps': 34, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 6, 'required_townhall': 8}, {'level': 6, 'hitpoints': 300, 'dps': 56, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 7, 'hitpoints': 350, 'dps': 78, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 8, 'hitpoints': 400, 'dps': 100, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 9, 'hitpoints': 450, 'dps': 120, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 10, 'hitpoints': 475, 'dps': 130, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 12, 'required_townhall': 14}, {'level': 11, 'hitpoints': 500, 'dps': 140, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 12, 'hitpoints': 525, 'dps': 150, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}, {'level': 13, 'hitpoints': 550, 'dps': 160, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 15, 'required_townhall': 17}, {'level': 14, 'hitpoints': 575, 'dps': 170, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 16, 'required_townhall': 18}]},
    {'_id': 4000029, 'name': 'Super Giant', 'info': 'Super Giants are bigger than their ordinary cousins and are great at punching their way through walls. The belt is from the annual Village eating contest.', 'TID': {'name': 'TID_CHARACTER_ELITE_GIANT', 'info': 'TID_CHARACTER_INFO_ELITE_GIANT'}, 'production_building': 'Barracks', 'production_building_level': 3, 'upgrade_resource': 'Elixir', 'is_flying': False, 'is_air_targeting': False, 'is_ground_targeting': True, 'movement_speed': 150, 'attack_speed': 2000, 'attack_range': 100, 'housing_space': 10, 'village': 'home', 'super_troop': {'original_id': 4000003, 'original_min_level': 8}, 'levels': [{'level': 5, 'hitpoints': 3200, 'dps': 90, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 6, 'required_townhall': 8}, {'level': 6, 'hitpoints': 3400, 'dps': 100, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 7, 'hitpoints': 3600, 'dps': 110, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 8, 'hitpoints': 3800, 'dps': 120, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 9, 'hitpoints': 4000, 'dps': 130, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 10, 'hitpoints': 4200, 'dps': 140, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 11, 'hitpoints': 4400, 'dps': 150, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 12, 'hitpoints': 4600, 'dps': 160, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}, {'level': 13, 'hitpoints': 4900, 'dps': 175, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 15, 'required_townhall': 17}, {'level': 14, 'hitpoints': 5300, 'dps': 190, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 16, 'required_townhall': 18}]},
    {'_id': 4000055, 'name': 'Sneaky Goblin', 'info': "Sneaky Goblins have a talent going unnoticed for a while after being deployed. It's usually the incredibly loud sound of resources being pilfered that gives them away.", 'TID': {'name': 'TID_CHARACTER_ELITE_GOBLIN', 'info': 'TID_CHARACTER_INFO_ELITE_GOBLIN'}, 'production_building': 'Barracks', 'production_building_level': 4, 'upgrade_resource': 'Elixir', 'is_flying': False, 'is_air_targeting': False, 'is_ground_targeting': True, 'movement_speed': 400, 'attack_speed': 1000, 'attack_range': 40, 'housing_space': 3, 'village': 'home', 'super_troop': {'original_id': 4000002, 'original_min_level': 6}, 'levels': [{'level': 5, 'hitpoints': 200, 'dps': 120, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 6, 'required_townhall': 8}, {'level': 6, 'hitpoints': 240, 'dps': 140, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 7, 'hitpoints': 270, 'dps': 155, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 8, 'hitpoints': 320, 'dps': 170, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 9, 'hitpoints': 350, 'dps': 180, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}]},
    {'_id': 4000056, 'name': 'Super Miner', 'info': 'Armed with a powerful drill and a magnificent moustache, Super Miner is ready to undermine any rival Village!', 'TID': {'name': 'TID_SUPER_MINER', 'info': 'TID_SUPER_MINER_INFO'}, 'production_building': 'Barracks', 'production_building_level': 12, 'upgrade_resource': 'Elixir', 'is_flying': False, 'is_air_targeting': False, 'is_ground_targeting': True, 'movement_speed': 400, 'attack_speed': 250, 'attack_range': 60, 'housing_space': 24, 'village': 'home', 'super_troop': {'original_id': 4000024, 'original_min_level': 6}, 'levels': [{'level': 1, 'hitpoints': 1700, 'dps': 80, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 1, 'required_townhall': 3}, {'level': 2, 'hitpoints': 1900, 'dps': 95, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 3, 'hitpoints': 2100, 'dps': 110, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 4, 'hitpoints': 2300, 'dps': 125, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 5, 'hitpoints': 2500, 'dps': 140, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 6, 'hitpoints': 2700, 'dps': 155, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 7, 'hitpoints': 3000, 'dps': 170, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 8, 'hitpoints': 3300, 'dps': 185, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 12, 'required_townhall': 14}, {'level': 9, 'hitpoints': 3600, 'dps': 205, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 10, 'hitpoints': 4000, 'dps': 225, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}, {'level': 11, 'hitpoints': 4400, 'dps': 245, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 15, 'required_townhall': 17}, {'level': 12, 'hitpoints': 5000, 'dps': 265, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 16, 'required_townhall': 18}]},
    {'_id': 4000057, 'name': 'Rocket Balloon', 'info': 'Retrofitted with two carefully safety-inspected booster rockets, the Rocket Balloon gets a flying start to every battle!', 'TID': {'name': 'TID_CHARACTER_HASTY_BALLOON', 'info': 'TID_CHARACTER_INFO_HASTY_BALLOON'}, 'production_building': 'Barracks', 'production_building_level': 6, 'upgrade_resource': 'Elixir', 'is_flying': True, 'is_air_targeting': False, 'is_ground_targeting': True, 'movement_speed': 150, 'attack_speed': 3000, 'attack_range': 0, 'housing_space': 8, 'village': 'home', 'super_troop': {'original_id': 4000005, 'original_min_level': 7}, 'levels': [{'level': 5, 'hitpoints': 390, 'dps': 170, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 6, 'required_townhall': 8}, {'level': 6, 'hitpoints': 545, 'dps': 220, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 7, 'hitpoints': 690, 'dps': 260, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 8, 'hitpoints': 840, 'dps': 270, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 9, 'hitpoints': 940, 'dps': 280, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 10, 'hitpoints': 1040, 'dps': 285, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 12, 'required_townhall': 14}, {'level': 11, 'hitpoints': 1140, 'dps': 290, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}, {'level': 12, 'hitpoints': 1240, 'dps': 304, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 15, 'required_townhall': 17}]},
    {'_id': 4000063, 'name': 'Inferno Dragon', 'info': 'Not getting upset over being alone anymore, the Inferno Dragon has learned to focus its rage into a very powerful beam that builds up over time!', 'TID': {'name': 'TID_CHARACTER_INFERNO_DRAGON', 'info': 'TID_CHARACTER_INFERNO_DRAGON_INFO'}, 'production_building': 'Barracks', 'production_building_level': 11, 'upgrade_resource': 'Elixir', 'is_flying': True, 'is_air_targeting': True, 'is_ground_targeting': True, 'movement_speed': 225, 'attack_speed': 128, 'attack_range': 350, 'housing_space': 15, 'village': 'home', 'super_troop': {'original_id': 4000023, 'original_min_level': 5}, 'levels': [{'level': 1, 'hitpoints': 1150, 'dps': 55, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 1, 'required_townhall': 3}, {'level': 2, 'hitpoints': 1300, 'dps': 59, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 3, 'hitpoints': 1450, 'dps': 63, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 4, 'hitpoints': 1600, 'dps': 67, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 5, 'hitpoints': 1750, 'dps': 71, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 6, 'hitpoints': 1900, 'dps': 75, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 7, 'hitpoints': 2050, 'dps': 79, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 8, 'hitpoints': 2200, 'dps': 83, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 12, 'required_townhall': 14}, {'level': 9, 'hitpoints': 2300, 'dps': 85, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 10, 'hitpoints': 2400, 'dps': 87, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}, {'level': 11, 'hitpoints': 2500, 'dps': 89, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 15, 'required_townhall': 17}]},
    {'_id': 4000064, 'name': 'Super Valkyrie', 'info': "Not only are Super Valkyries superior to regular Valkyries in every way, they're also way more angry!", 'TID': {'name': 'TID_CHARACTER_SUPER_VALKYRIE', 'info': 'TID_CHARACTER_SUPER_VALKYRIE_INFO'}, 'production_building': 'Dark Barracks', 'production_building_level': 3, 'upgrade_resource': 'Dark Elixir', 'is_flying': False, 'is_air_targeting': False, 'is_ground_targeting': True, 'movement_speed': 300, 'attack_speed': 1100, 'attack_range': 50, 'housing_space': 20, 'village': 'home', 'super_troop': {'original_id': 4000012, 'original_min_level': 6}, 'levels': [{'level': 1, 'hitpoints': 1200, 'dps': 100, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 1, 'required_townhall': 3}, {'level': 2, 'hitpoints': 1400, 'dps': 125, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 6, 'required_townhall': 8}, {'level': 3, 'hitpoints': 1600, 'dps': 150, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 4, 'hitpoints': 1800, 'dps': 175, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 5, 'hitpoints': 2000, 'dps': 200, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 6, 'hitpoints': 2200, 'dps': 225, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 7, 'hitpoints': 2400, 'dps': 250, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 8, 'hitpoints': 2700, 'dps': 300, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 9, 'hitpoints': 2900, 'dps': 325, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 12, 'required_townhall': 14}, {'level': 10, 'hitpoints': 3400, 'dps': 350, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 11, 'hitpoints': 3900, 'dps': 375, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}]},
    {'_id': 4000066, 'name': 'Super Witch', 'info': 'Focused magic creates focused results. Instead of summoning hordes of tiny skeletons, Super Witch summons just one really big skeleton with very formidable bone density.', 'TID': {'name': 'TID_CHARACTER_SUPER_WITCH', 'info': 'TID_CHARACTER_SUPER_WITCH_INFO'}, 'production_building': 'Dark Barracks', 'production_building_level': 5, 'upgrade_resource': 'Dark Elixir', 'is_flying': False, 'is_air_targeting': True, 'is_ground_targeting': True, 'movement_speed': 150, 'attack_speed': 700, 'attack_range': 400, 'housing_space': 40, 'village': 'home', 'super_troop': {'original_id': 4000015, 'original_min_level': 4}, 'levels': [{'level': 1, 'hitpoints': 2400, 'dps': 240, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 1, 'required_townhall': 3}, {'level': 2, 'hitpoints': 2600, 'dps': 270, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 3, 'hitpoints': 2800, 'dps': 300, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 4, 'hitpoints': 3000, 'dps': 330, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 5, 'hitpoints': 3200, 'dps': 360, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 6, 'hitpoints': 3400, 'dps': 390, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 7, 'hitpoints': 3600, 'dps': 420, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}]},
    {'_id': 4000076, 'name': 'Ice Hound', 'info': 'Free from all that lava-induced indigestion, the Ice Hound is ready to freeze the flow of battle. Chill out, or else.', 'TID': {'name': 'TID_ICE_HOUND', 'info': 'TID_ICE_HOUND_INFO'}, 'production_building': 'Dark Barracks', 'production_building_level': 6, 'upgrade_resource': 'Dark Elixir', 'is_flying': True, 'is_air_targeting': False, 'is_ground_targeting': True, 'movement_speed': 250, 'attack_speed': 2000, 'attack_range': 25, 'housing_space': 40, 'village': 'home', 'super_troop': {'original_id': 4000017, 'original_min_level': 4}, 'levels': [{'level': 1, 'hitpoints': 7500, 'dps': 2, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 1, 'required_townhall': 3}, {'level': 2, 'hitpoints': 8000, 'dps': 4, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 3, 'hitpoints': 8500, 'dps': 6, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 4, 'hitpoints': 9000, 'dps': 8, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 5, 'hitpoints': 9500, 'dps': 10, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 6, 'hitpoints': 10000, 'dps': 15, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 7, 'hitpoints': 10500, 'dps': 20, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}]},
    {'_id': 4000080, 'name': 'Super Bowler', 'info': "Super Bowler now has everything he's ever wanted: a grippier glove, more comfortable footwear, and even more ridiculously massive boulders to toss.", 'TID': {'name': 'TID_SUPER_BOWLER', 'info': 'TID_SUPER_BOWLER_INFO'}, 'production_building': 'Dark Barracks', 'production_building_level': 7, 'upgrade_resource': 'Dark Elixir', 'is_flying': False, 'is_air_targeting': False, 'is_ground_targeting': True, 'movement_speed': 175, 'attack_speed': 2200, 'attack_range': 300, 'housing_space': 30, 'village': 'home', 'super_troop': {'original_id': 4000022, 'original_min_level': 3}, 'levels': [{'level': 1, 'hitpoints': 1000, 'dps': 125, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 1, 'required_townhall': 3}, {'level': 2, 'hitpoints': 1200, 'dps': 140, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 3, 'hitpoints': 1400, 'dps': 155, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 4, 'hitpoints': 1600, 'dps': 170, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 5, 'hitpoints': 1800, 'dps': 185, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 6, 'hitpoints': 2000, 'dps': 200, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 12, 'required_townhall': 14}, {'level': 7, 'hitpoints': 2300, 'dps': 220, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 8, 'hitpoints': 2600, 'dps': 240, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}, {'level': 9, 'hitpoints': 3000, 'dps': 270, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 15, 'required_townhall': 17}, {'level': 10, 'hitpoints': 3600, 'dps': 300, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 16, 'required_townhall': 18}]},
    {'_id': 4000081, 'name': 'Super Dragon', 'info': "Sometimes having a fire inside of you isn't enough. The Super Dragon has fires on the inside, outside, and if he gets to do his thing, all around him!", 'TID': {'name': 'TID_SUPER_DRAGON', 'info': 'TID_SUPER_DRAGON_INFO'}, 'production_building': 'Barracks', 'production_building_level': 9, 'upgrade_resource': 'Elixir', 'is_flying': True, 'is_air_targeting': True, 'is_ground_targeting': True, 'movement_speed': 175, 'attack_speed': 1800, 'attack_range': 300, 'housing_space': 40, 'village': 'home', 'super_troop': {'original_id': 4000008, 'original_min_level': 6}, 'levels': [{'level': 3, 'hitpoints': 3900, 'dps': 60, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 6, 'required_townhall': 8}, {'level': 4, 'hitpoints': 4500, 'dps': 65, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 5, 'hitpoints': 5100, 'dps': 70, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 6, 'hitpoints': 5600, 'dps': 75, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 7, 'hitpoints': 6100, 'dps': 80, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 8, 'hitpoints': 6400, 'dps': 85, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 9, 'hitpoints': 6700, 'dps': 90, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 12, 'required_townhall': 14}, {'level': 10, 'hitpoints': 7200, 'dps': 95, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 11, 'hitpoints': 7600, 'dps': 99, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}, {'level': 12, 'hitpoints': 8000, 'dps': 103, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 15, 'required_townhall': 17}]},
    {'_id': 4000083, 'name': 'Super Wizard', 'info': "Super Wizard is positively charged with magical energy! He's either the smartest person in the room... or else he blows the whole room to bits.", 'TID': {'name': 'TID_SUPER_WIZARD', 'info': 'TID_SUPER_WIZARD_INFO'}, 'production_building': 'Barracks', 'production_building_level': 7, 'upgrade_resource': 'Elixir', 'is_flying': False, 'is_air_targeting': True, 'is_ground_targeting': True, 'movement_speed': 250, 'attack_speed': 2000, 'attack_range': 350, 'housing_space': 10, 'village': 'home', 'super_troop': {'original_id': 4000006, 'original_min_level': 8}, 'levels': [{'level': 5, 'hitpoints': 250, 'dps': 140, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 6, 'required_townhall': 8}, {'level': 6, 'hitpoints': 300, 'dps': 160, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 7, 'hitpoints': 350, 'dps': 180, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 8, 'hitpoints': 400, 'dps': 200, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 9, 'hitpoints': 450, 'dps': 220, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 10, 'hitpoints': 500, 'dps': 240, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 11, 'hitpoints': 540, 'dps': 265, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 12, 'hitpoints': 580, 'dps': 285, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}, {'level': 13, 'hitpoints': 620, 'dps': 305, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 15, 'required_townhall': 17}, {'level': 14, 'hitpoints': 700, 'dps': 335, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 16, 'required_townhall': 18}]},
    {'_id': 4000084, 'name': 'Super Minion', 'info': "Super Minion's big forehead isn't just for show: sniping enemy defenses from a safe distance is simply a brainy move! Especially when you've grown too big to avoid Seeking Air Mines.", 'TID': {'name': 'TID_SUPER_MINION', 'info': 'TID_CHARACTER_INFO_SUPER_MINION'}, 'production_building': 'Dark Barracks', 'production_building_level': 1, 'upgrade_resource': 'Dark Elixir', 'is_flying': True, 'is_air_targeting': True, 'is_ground_targeting': True, 'movement_speed': 200, 'attack_speed': 1000, 'attack_range': 350, 'housing_space': 12, 'village': 'home', 'super_troop': {'original_id': 4000010, 'original_min_level': 7}, 'levels': [{'level': 4, 'hitpoints': 1100, 'dps': 200, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 6, 'required_townhall': 8}, {'level': 5, 'hitpoints': 1200, 'dps': 225, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 6, 'hitpoints': 1300, 'dps': 250, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 7, 'hitpoints': 1400, 'dps': 275, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 8, 'hitpoints': 1500, 'dps': 300, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 9, 'hitpoints': 1600, 'dps': 325, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 10, 'hitpoints': 1700, 'dps': 350, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 12, 'required_townhall': 14}, {'level': 11, 'hitpoints': 1800, 'dps': 360, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 12, 'hitpoints': 1900, 'dps': 370, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}, {'level': 13, 'hitpoints': 2100, 'dps': 385, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 15, 'required_townhall': 17}, {'level': 14, 'hitpoints': 2300, 'dps': 400, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 16, 'required_townhall': 18}]},
    {'_id': 4000098, 'name': 'Super Hog Rider', 'info': 'This dangerous duo of Hog and Rider are even more superb now. They ride together, they split up and keep fighting together.', 'TID': {'name': 'TID_CHARACTER_SUPER_HOG_RIDER', 'info': 'TID_CHARACTER_SUPER_HOG_RIDER_INFO'}, 'production_building': 'Dark Barracks', 'production_building_level': 2, 'upgrade_resource': 'Dark Elixir', 'is_flying': False, 'is_air_targeting': False, 'is_ground_targeting': True, 'movement_speed': 300, 'attack_speed': 1000, 'attack_range': 60, 'housing_space': 12, 'village': 'home', 'super_troop': {'original_id': 4000011, 'original_min_level': 9}, 'levels': [{'level': 4, 'hitpoints': 800, 'dps': 100, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 6, 'required_townhall': 8}, {'level': 5, 'hitpoints': 900, 'dps': 115, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 7, 'required_townhall': 9}, {'level': 6, 'hitpoints': 1100, 'dps': 130, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 8, 'required_townhall': 10}, {'level': 7, 'hitpoints': 1200, 'dps': 145, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 9, 'required_townhall': 11}, {'level': 8, 'hitpoints': 1300, 'dps': 160, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 9, 'hitpoints': 1400, 'dps': 175, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 10, 'hitpoints': 1500, 'dps': 190, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 11, 'hitpoints': 1600, 'dps': 210, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 12, 'required_townhall': 14}, {'level': 12, 'hitpoints': 1750, 'dps': 230, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 13, 'hitpoints': 1900, 'dps': 250, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}, {'level': 14, 'hitpoints': 2100, 'dps': 270, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 15, 'required_townhall': 17}]},
    {'_id': 4000147, 'name': 'Super Yeti', 'info': 'This mysterious masked Yeti is charged up! His electrical little buddies spring into action when he takes damage and zap the closest Building to spark a devastating chain reaction!', 'TID': {'name': 'TID_CHARACTER_SUPER_YETI', 'info': 'TID_CHARACTER_INFO_SUPER_YETI'}, 'production_building': 'Barracks', 'production_building_level': 14, 'upgrade_resource': 'Elixir', 'is_flying': False, 'is_air_targeting': False, 'is_ground_targeting': True, 'movement_speed': 150, 'attack_speed': 1000, 'attack_range': 80, 'housing_space': 35, 'village': 'home', 'super_troop': {'original_id': 4000053, 'original_min_level': 2}, 'levels': [{'level': 1, 'hitpoints': 4600, 'dps': 360, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 1, 'required_townhall': 3}, {'level': 2, 'hitpoints': 5000, 'dps': 390, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 10, 'required_townhall': 12}, {'level': 3, 'hitpoints': 5400, 'dps': 415, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 11, 'required_townhall': 13}, {'level': 4, 'hitpoints': 5800, 'dps': 440, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 12, 'required_townhall': 14}, {'level': 5, 'hitpoints': 6200, 'dps': 465, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 13, 'required_townhall': 15}, {'level': 6, 'hitpoints': 6600, 'dps': 495, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 14, 'required_townhall': 16}, {'level': 7, 'hitpoints': 7000, 'dps': 525, 'upgrade_time': 0, 'upgrade_cost': 0, 'required_lab_level': 15, 'required_townhall': 17}]},
]

HOME_TROOP_ORDER = HV_TROOP_ORDER + SIEGE_MACHINE_ORDER

SEASONAL_TROOP_ORDER = [
    'Ice Wizard',
    'Battle Ram',
    'Royal Ghost',
    'Pumpkin Barbarian',
    'Giant Skeleton',
    'Skeleton Barrel',
    'M.E.C.H.A',
    'Party Wizard',
    'Ram Rider',
    'Barcher',
    'Witch Golem',
    'Hog Wizard',
    'Lavaloon',
    'C.O.O.K.I.E',
    'Firecracker',
    'Azure Dragon',
    'Barbarian Kicker',
    'Giant Thrower',
    'Broom Witch',
    'Ice Minion',
    'Debt Collector',
    'Snake Barrel',
    'Giant Giant',
    'K.A.N.E',
    'The Disarmer',
    'YEETer',
    'YEETer',
    'The Disarmer',
    'Meteor Golem',
]

BUILDER_TROOPS_ORDER = [
    'Raged Barbarian',
    'Sneaky Archer',
    'Beta Minion',
    'Boxer Giant',
    'Bomber',
    'Power P.E.K.K.A',
    'Cannon Cart',
    'Drop Ship',
    'Baby Dragon',
    'Night Witch',
    'Hog Glider',
    'Electrofire Wizard',
]

ELIXIR_SPELL_ORDER = [
    'Lightning Spell',
    'Healing Spell',
    'Rage Spell',
    'Jump Spell',
    'Freeze Spell',
    'Clone Spell',
    'Invisibility Spell',
    'Recall Spell',
    'Revive Spell',
    'Totem Spell',
]

DARK_ELIXIR_SPELL_ORDER = [
    'Poison Spell',
    'Earthquake Spell',
    'Haste Spell',
    'Skeleton Spell',
    'Bat Spell',
    'Overgrowth Spell',
    'Ice Block Spell',
]

SEASONAL_SPELL_ORDER = [
    "Santa's Surprise",
    'Bag of Frostmites',
]

SPELL_ORDER = ELIXIR_SPELL_ORDER + DARK_ELIXIR_SPELL_ORDER

HOME_BASE_HERO_ORDER = [
    'Barbarian King',
    'Archer Queen',
    'Grand Warden',
    'Royal Champion',
    'Minion Prince',
]

BUILDER_BASE_HERO_ORDER = [
    'Battle Machine',
    'Battle Copter',
]

HERO_ORDER = HOME_BASE_HERO_ORDER + BUILDER_BASE_HERO_ORDER

PETS_ORDER = [
    'L.A.S.S.I',
    'Mighty Yak',
    'Electro Owl',
    'Unicorn',
    'Phoenix',
    'Poison Lizard',
    'Diggy',
    'Frosty',
    'Spirit Fox',
    'Angry Jelly',
    'Sneezy',
]

EQUIPMENT = [
    'Barbarian Puppet',
    'Rage Vial',
    'Archer Puppet',
    'Invisibility Vial',
    'Eternal Tome',
    'Life Gem',
    'Seeking Shield',
    'Royal Gem',
    'Earthquake Boots',
    'Hog Rider Puppet',
    'Giant Gauntlet',
    'Vampstache',
    'Haste Vial',
    'Rocket Spear',
    'Spiky Ball',
    'Frozen Arrow',
    'Giant Arrow',
    'Heroic Torch',
    'Healer Puppet',
    'Fireball',
    'Rage Gem',
    'Snake Bracelet',
    'Healing Tome',
    'Dark Crown',
    'Magic Mirror',
    'Electro Boots',
    'Lavaloon Puppet',
    'Henchmen Puppet',
    'Dark Orb',
    'Metal Pants',
    'Noble Iron',
    'Action Figure',
    'Meteor Staff',
    'Frost Flake',
    'Stick Horse',
]

HV_BUILDINGS = [
    'Army Camp',
    'Town Hall',
    'Elixir Collector',
    'Elixir Storage',
    'Gold Mine',
    'Gold Storage',
    'Barracks',
    'Laboratory',
    'Cannon',
    'Archer Tower',
    'Wall',
    'Wizard Tower',
    'Air Defense',
    'Mortar',
    'Clan Castle',
    "Builder's Hut",
    'Hidden Tesla',
    'Spell Factory',
    'X-Bow',
    'Dark Elixir Drill',
    'Dark Elixir Storage',
    'Dark Barracks',
    'Inferno Tower',
    'Air Sweeper',
    'Dark Spell Factory',
    'Eagle Artillery',
    'Bomb Tower',
    'Workshop',
    "B.O.B's Hut",
    'Scattershot',
    'Pet House',
    'Blacksmith',
    'Hero Hall',
    'Spell Tower',
    'Monolith',
    'Multi-Gear Tower',
    'Sour Elixir Cauldron',
    'Multi-Archer Tower',
    'Ricochet Cannon',
    'Revenge Tower',
    'Firespitter',
    'Helper Hut',
    'Crafting Station',
    'Super Wizard Tower',
]

ACHIEVEMENT_ORDER = [
    'Bigger Coffers',
    'Get those Goblins!',
    'Bigger & Better',
    'Nice and Tidy',
    'Discover New Troops',
    'Gold Grab',
    'Elixir Escapade',
    'Sweet Victory!',
    'Empire Builder',
    'Wall Buster',
    'Humiliator',
    'Union Buster',
    'Conqueror',
    'Unbreakable',
    'Friend in Need',
    'Mortar Mauler',
    'Heroic Heist',
    'League All-Star',
    'X-Bow Exterminator',
    'Firefighter',
    'War Hero',
    'Clan War Wealth',
    'Anti-Artillery',
    'Sharing is caring',
    'Keep Your Account Safe!',
    'Master Engineering',
    'Next Generation Model',
    'Un-Build It',
    'Champion Builder',
    'High Gear',
    'Hidden Treasures',
    'Games Champion',
    'Get those other Goblins!',
    'Dragon Slayer',
    'War League Legend',
    'Well Seasoned',
    'Shattered and Scattered',
    'Not So Easy This Time',
    'Bust This!',
    'Superb Work',
    'Siege Sharer',
    'Aggressive Capitalism',
    'Most Valuable Clanmate',
    'Get even more Goblins!',
    'Counterspell',
    'Monolith Masher',
    'Ungrateful Child',
    'Supercharger',
    'Multi-Archer Tower Terminator',
    'Ricochet Cannon Crusher',
    'Firespitter Finisher',
    'Multi-Gear Tower Trampler',
    'Crafting Connoisseur',
    'Crafter’s Nightmare',
    'League Follower',
    'League Enthusiast',
    'League Superfan',
    'League Fanatic',
    'League Master',
]

