MOCK_CURRENT_WAR_IN_WAR = {
    "body": {"state": "inWar", "teamSize": 5, "attacksPerMember": 1, "preparationStartTime": "20230528T144240.000Z",
             "startTime": "20230528T144740.000Z", "endTime": "20230528T153240.000Z",
             "clan": {"tag": "#2GPVRU0C0", "name": "G.A.M.T", "badgeUrls": {
                 "small": "https://api-assets.clashofclans.com/badges/70/DcHcgP14dK0OPmf_G77JtangGL7_5u6oAOWUbbXP8Yw.png",
                 "large": "https://api-assets.clashofclans.com/badges/512/DcHcgP14dK0OPmf_G77JtangGL7_5u6oAOWUbbXP8Yw.png",
                 "medium": "https://api-assets.clashofclans.com/badges/200/DcHcgP14dK0OPmf_G77JtangGL7_5u6oAOWUbbXP8Yw.png"},
                      "clanLevel": 1, "attacks": 5, "stars": 10, "destructionPercentage": 90.2, "members": [
                     {"tag": "#2PRU8RPCP", "name": "\u2b50\ufe0fsncmaxi\u2b50\ufe0f", "townhallLevel": 12,
                      "mapPosition": 1, "attacks": [
                         {"attackerTag": "#2PRU8RPCP", "defenderTag": "#28R9YGPLP", "stars": 2,
                          "destructionPercentage": 94, "order": 7, "duration": 179}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#28R9YGPLP", "defenderTag": "#2PRU8RPCP", "stars": 3,
                                             "destructionPercentage": 100, "order": 4, "duration": 156}},
                     {"tag": "#YLYR8VVY", "name": "FMT I Rakhman", "townhallLevel": 12, "mapPosition": 2, "attacks": [
                         {"attackerTag": "#YLYR8VVY", "defenderTag": "#9R08QRUU2", "stars": 2,
                          "destructionPercentage": 93, "order": 3, "duration": 179}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#YP80RGJUG", "defenderTag": "#YLYR8VVY", "stars": 2,
                                             "destructionPercentage": 96, "order": 6, "duration": 168}},
                     {"tag": "#QP8UP8UV", "name": "Das Chaos", "townhallLevel": 12, "mapPosition": 5, "attacks": [
                         {"attackerTag": "#QP8UP8UV", "defenderTag": "#VRRPG0RQ", "stars": 1,
                          "destructionPercentage": 71, "order": 5, "duration": 119}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#VRRPG0RQ", "defenderTag": "#QP8UP8UV", "stars": 2,
                                             "destructionPercentage": 72, "order": 8, "duration": 179}},
                     {"tag": "#P0C9UJLPP", "name": "YoSoyGod\u2764\ufe0f\u1d40\u1d34\u00b9\u00b2\u2081",
                      "townhallLevel": 12, "mapPosition": 3, "attacks": [
                         {"attackerTag": "#P0C9UJLPP", "defenderTag": "#YP80RGJUG", "stars": 3,
                          "destructionPercentage": 100, "order": 1, "duration": 160}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#PLGGC0L02", "defenderTag": "#P0C9UJLPP", "stars": 3,
                                             "destructionPercentage": 100, "order": 10, "duration": 171}},
                     {"tag": "#PCQ992GYV", "name": "Bill", "townhallLevel": 12, "mapPosition": 4, "attacks": [
                         {"attackerTag": "#PCQ992GYV", "defenderTag": "#PLGGC0L02", "stars": 2,
                          "destructionPercentage": 93, "order": 9, "duration": 179}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#9R08QRUU2", "defenderTag": "#PCQ992GYV", "stars": 3,
                                             "destructionPercentage": 100, "order": 2, "duration": 157}}]},
             "opponent": {"tag": "#2QCVRQCQR", "name": "\u2122 Galaxy", "badgeUrls": {
                 "small": "https://api-assets.clashofclans.com/badges/70/AEaHm0FmstsRRGTqajAhcz1Mi7ceR2ys7g5PL7p2mvk.png",
                 "large": "https://api-assets.clashofclans.com/badges/512/AEaHm0FmstsRRGTqajAhcz1Mi7ceR2ys7g5PL7p2mvk.png",
                 "medium": "https://api-assets.clashofclans.com/badges/200/AEaHm0FmstsRRGTqajAhcz1Mi7ceR2ys7g5PL7p2mvk.png"},
                          "clanLevel": 1, "attacks": 5, "stars": 13, "destructionPercentage": 93.6, "members": [
                     {"tag": "#9R08QRUU2", "name": "\u767c\uff2e\uff29\uff34\uff29\uff33\uff28\u2757",
                      "townhallLevel": 12, "mapPosition": 1, "attacks": [
                         {"attackerTag": "#9R08QRUU2", "defenderTag": "#PCQ992GYV", "stars": 3,
                          "destructionPercentage": 100, "order": 2, "duration": 157}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#YLYR8VVY", "defenderTag": "#9R08QRUU2", "stars": 2,
                                             "destructionPercentage": 93, "order": 3, "duration": 179}},
                     {"tag": "#VRRPG0RQ", "name": "lalo.exe", "townhallLevel": 12, "mapPosition": 2, "attacks": [
                         {"attackerTag": "#VRRPG0RQ", "defenderTag": "#QP8UP8UV", "stars": 2,
                          "destructionPercentage": 72, "order": 8, "duration": 179}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#QP8UP8UV", "defenderTag": "#VRRPG0RQ", "stars": 1,
                                             "destructionPercentage": 71, "order": 5, "duration": 119}},
                     {"tag": "#YP80RGJUG", "name": "Ayush", "townhallLevel": 12, "mapPosition": 3, "attacks": [
                         {"attackerTag": "#YP80RGJUG", "defenderTag": "#YLYR8VVY", "stars": 2,
                          "destructionPercentage": 96, "order": 6, "duration": 168}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#P0C9UJLPP", "defenderTag": "#YP80RGJUG", "stars": 3,
                                             "destructionPercentage": 100, "order": 1, "duration": 160}},
                     {"tag": "#PLGGC0L02", "name": "\uff2b\u5de5\u3057\u3057\u30e2\u5c3a \u30e0", "townhallLevel": 12,
                      "mapPosition": 5, "attacks": [
                         {"attackerTag": "#PLGGC0L02", "defenderTag": "#P0C9UJLPP", "stars": 3,
                          "destructionPercentage": 100, "order": 10, "duration": 171}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#PCQ992GYV", "defenderTag": "#PLGGC0L02", "stars": 2,
                                             "destructionPercentage": 93, "order": 9, "duration": 179}},
                     {"tag": "#28R9YGPLP", "name": "\uff27\uff28\uff2f\uff33\uff34\u00a0\uff26\uff32\uff25\uff21\uff2b",
                      "townhallLevel": 12, "mapPosition": 4, "attacks": [
                         {"attackerTag": "#28R9YGPLP", "defenderTag": "#2PRU8RPCP", "stars": 3,
                          "destructionPercentage": 100, "order": 4, "duration": 156}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#2PRU8RPCP", "defenderTag": "#28R9YGPLP", "stars": 2,
                                             "destructionPercentage": 94, "order": 7, "duration": 179}}]}},
    "headers": {"cache-control": "max-age=120", "content-type": "application/json; charset=utf-8"},
    "response_code": 200}

MOCK_CURRENT_WAR_WAR_ENDED = {
    "body": {"state": "warEnded", "teamSize": 5, "attacksPerMember": 1, "preparationStartTime": "20230528T154814.000Z",
             "startTime": "20230528T155314.000Z", "endTime": "20230528T163814.000Z",
             "clan": {"tag": "#2GPVRU0C0", "name": "G.A.M.T", "badgeUrls": {
                 "small": "https://api-assets.clashofclans.com/badges/70/DcHcgP14dK0OPmf_G77JtangGL7_5u6oAOWUbbXP8Yw.png",
                 "large": "https://api-assets.clashofclans.com/badges/512/DcHcgP14dK0OPmf_G77JtangGL7_5u6oAOWUbbXP8Yw.png",
                 "medium": "https://api-assets.clashofclans.com/badges/200/DcHcgP14dK0OPmf_G77JtangGL7_5u6oAOWUbbXP8Yw.png"},
                      "clanLevel": 1, "attacks": 5, "stars": 11, "destructionPercentage": 87.6, "members": [
                     {"tag": "#Y09PQVCC", "name": "✨Aqueedaon✨Th12", "townhallLevel": 12, "mapPosition": 1, "attacks": [
                         {"attackerTag": "#Y09PQVCC", "defenderTag": "#9R08QRUU2", "stars": 1,
                          "destructionPercentage": 67, "order": 10, "duration": 111}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#PLGGC0L02", "defenderTag": "#Y09PQVCC", "stars": 3,
                                             "destructionPercentage": 100, "order": 7, "duration": 155}},
                     {"tag": "#2PRU8RPCP", "name": "⭐️sncmaxi⭐️", "townhallLevel": 12, "mapPosition": 2, "attacks": [
                         {"attackerTag": "#2PRU8RPCP", "defenderTag": "#28R9YGPLP", "stars": 1,
                          "destructionPercentage": 71, "order": 8, "duration": 178}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#28R9YGPLP", "defenderTag": "#2PRU8RPCP", "stars": 3,
                                             "destructionPercentage": 100, "order": 3, "duration": 133}},
                     {"tag": "#YLYR8VVY", "name": "FMT I Rakhman", "townhallLevel": 12, "mapPosition": 3, "attacks": [
                         {"attackerTag": "#YLYR8VVY", "defenderTag": "#VRRPG0RQ", "stars": 3,
                          "destructionPercentage": 100, "order": 4, "duration": 143}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#VRRPG0RQ", "defenderTag": "#YLYR8VVY", "stars": 2,
                                             "destructionPercentage": 98, "order": 5, "duration": 179}},
                     {"tag": "#QP8UP8UV", "name": "Das Chaos", "townhallLevel": 12, "mapPosition": 5, "attacks": [
                         {"attackerTag": "#QP8UP8UV", "defenderTag": "#PLGGC0L02", "stars": 3,
                          "destructionPercentage": 100, "order": 6, "duration": 146}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#29LPYJ0LQ", "defenderTag": "#QP8UP8UV", "stars": 3,
                                             "destructionPercentage": 100, "order": 9, "duration": 163}},
                     {"tag": "#P0C9UJLPP", "name": "YoSoyGod❤️ᵀᴴ¹²₁", "townhallLevel": 12, "mapPosition": 4,
                      "attacks": [{"attackerTag": "#P0C9UJLPP", "defenderTag": "#29LPYJ0LQ", "stars": 3,
                                   "destructionPercentage": 100, "order": 2, "duration": 144}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#9R08QRUU2", "defenderTag": "#P0C9UJLPP", "stars": 2,
                                             "destructionPercentage": 82, "order": 1, "duration": 165}}]},
             "opponent": {"tag": "#2QCVRQCQR", "name": "™ Galaxy", "badgeUrls": {
                 "small": "https://api-assets.clashofclans.com/badges/70/AEaHm0FmstsRRGTqajAhcz1Mi7ceR2ys7g5PL7p2mvk.png",
                 "large": "https://api-assets.clashofclans.com/badges/512/AEaHm0FmstsRRGTqajAhcz1Mi7ceR2ys7g5PL7p2mvk.png",
                 "medium": "https://api-assets.clashofclans.com/badges/200/AEaHm0FmstsRRGTqajAhcz1Mi7ceR2ys7g5PL7p2mvk.png"},
                          "clanLevel": 1, "attacks": 5, "stars": 13, "destructionPercentage": 96, "members": [
                     {"tag": "#9R08QRUU2", "name": "發ＮＩＴＩＳＨ❗", "townhallLevel": 12, "mapPosition": 1, "attacks": [
                         {"attackerTag": "#9R08QRUU2", "defenderTag": "#P0C9UJLPP", "stars": 2,
                          "destructionPercentage": 82, "order": 1, "duration": 165}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#Y09PQVCC", "defenderTag": "#9R08QRUU2", "stars": 1,
                                             "destructionPercentage": 67, "order": 10, "duration": 111}},
                     {"tag": "#VRRPG0RQ", "name": "lalo.exe", "townhallLevel": 12, "mapPosition": 2, "attacks": [
                         {"attackerTag": "#VRRPG0RQ", "defenderTag": "#YLYR8VVY", "stars": 2,
                          "destructionPercentage": 98, "order": 5, "duration": 179}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#YLYR8VVY", "defenderTag": "#VRRPG0RQ", "stars": 3,
                                             "destructionPercentage": 100, "order": 4, "duration": 143}},
                     {"tag": "#PLGGC0L02", "name": "Ｋ工ししモ尺 ム", "townhallLevel": 12, "mapPosition": 5, "attacks": [
                         {"attackerTag": "#PLGGC0L02", "defenderTag": "#Y09PQVCC", "stars": 3,
                          "destructionPercentage": 100, "order": 7, "duration": 155}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#QP8UP8UV", "defenderTag": "#PLGGC0L02", "stars": 3,
                                             "destructionPercentage": 100, "order": 6, "duration": 146}},
                     {"tag": "#28R9YGPLP", "name": "ＧＨＯＳＴ ＦＲＥＡＫ", "townhallLevel": 12, "mapPosition": 3, "attacks": [
                         {"attackerTag": "#28R9YGPLP", "defenderTag": "#2PRU8RPCP", "stars": 3,
                          "destructionPercentage": 100, "order": 3, "duration": 133}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#2PRU8RPCP", "defenderTag": "#28R9YGPLP", "stars": 1,
                                             "destructionPercentage": 71, "order": 8, "duration": 178}},
                     {"tag": "#29LPYJ0LQ", "name": "Viper", "townhallLevel": 12, "mapPosition": 4, "attacks": [
                         {"attackerTag": "#29LPYJ0LQ", "defenderTag": "#QP8UP8UV", "stars": 3,
                          "destructionPercentage": 100, "order": 9, "duration": 163}], "opponentAttacks": 1,
                      "bestOpponentAttack": {"attackerTag": "#P0C9UJLPP", "defenderTag": "#29LPYJ0LQ", "stars": 3,
                                             "destructionPercentage": 100, "order": 2, "duration": 144}}]}},
    "headers": {"cache-control": "max-age=120", "content-type": "application/json; charset=utf-8"},
    "response_code": 200}

MOCK_CURRENT_WAR_NOT_IN_WAR = {
    "body": {"state": "notInWar", "clan": {"badgeUrls": {
    "small": "https://api-assets.clashofclans.com/badges/70/H39b_-WLZGtZVWQ0hqTkE-Tn2AaQnQWy_Iz4yBlvL0M.png",
    "large": "https://api-assets.clashofclans.com/badges/512/H39b_-WLZGtZVWQ0hqTkE-Tn2AaQnQWy_Iz4yBlvL0M.png",
    "medium": "https://api-assets.clashofclans.com/badges/200/H39b_-WLZGtZVWQ0hqTkE-Tn2AaQnQWy_Iz4yBlvL0M.png"},
    "clanLevel": 0, "attacks": 0, "stars": 0, "destructionPercentage": 0}, "opponent": {"badgeUrls": {
    "small": "https://api-assets.clashofclans.com/badges/70/H39b_-WLZGtZVWQ0hqTkE-Tn2AaQnQWy_Iz4yBlvL0M.png",
    "large": "https://api-assets.clashofclans.com/badges/512/H39b_-WLZGtZVWQ0hqTkE-Tn2AaQnQWy_Iz4yBlvL0M.png",
    "medium": "https://api-assets.clashofclans.com/badges/200/H39b_-WLZGtZVWQ0hqTkE-Tn2AaQnQWy_Iz4yBlvL0M.png"},
    "clanLevel": 0, "attacks": 0, "stars": 0, "destructionPercentage": 0}},
    "headers": {"cache-control": "max-age=120", "content-type": "application/json; charset=utf-8"},
    "response_code": 200}

MOCK_CURRENT_WAR_ACCESS_DENIED = {
    "body": {"reason": "accessDenied"},
    "headers": {"cache-control": "max-age=120", "content-type": "application/json"},
    "response_code": 403
}

MOCK_CURRENT_WAR_PREPARATION = {
    "body": {"state": "preparation", "teamSize": 50, "attacksPerMember": 2,
    "preparationStartTime": "20230528T082208.000Z", "startTime": "20230529T072208.000Z",
    "endTime": "20230530T072208.000Z", "clan": {"tag": "#RY8GYCLY", "name": "FRIENDS FOREVER", "badgeUrls": {
        "small": "https://api-assets.clashofclans.com/badges/70/2avGGTGMjQ_nxnE5ZZlB6Xk6ujYkm91o7uCqEx37Ox0.png",
        "large": "https://api-assets.clashofclans.com/badges/512/2avGGTGMjQ_nxnE5ZZlB6Xk6ujYkm91o7uCqEx37Ox0.png",
        "medium": "https://api-assets.clashofclans.com/badges/200/2avGGTGMjQ_nxnE5ZZlB6Xk6ujYkm91o7uCqEx37Ox0.png"},
        "clanLevel": 22, "attacks": 0, "stars": 0, "destructionPercentage": 0, "members": [
            {"tag": "#PR0PQ0GG", "name": "joeycipp", "townhallLevel": 15, "mapPosition": 17, "opponentAttacks": 0},
            {"tag": "#LL8029PPP", "name": "xX_ROCKY_Xx", "townhallLevel": 13, "mapPosition": 45, "opponentAttacks": 0},
            {"tag": "#YPPJYYYRU", "name": "MUDIT THE MAN", "townhallLevel": 14, "mapPosition": 28,
                "opponentAttacks": 0},
            {"tag": "#98JVLU2Q2", "name": "Mythresh", "townhallLevel": 15, "mapPosition": 6, "opponentAttacks": 0},
            {"tag": "#2JL0YV280", "name": "Luca9750", "townhallLevel": 13, "mapPosition": 44, "opponentAttacks": 0},
            {"tag": "#8008VPRV9", "name": "BadaBoom", "townhallLevel": 14, "mapPosition": 25, "opponentAttacks": 0},
            {"tag": "#88992QUL", "name": "rushabh", "townhallLevel": 13, "mapPosition": 46, "opponentAttacks": 0},
            {"tag": "#800LL8JLL", "name": "• ZERO •", "townhallLevel": 15, "mapPosition": 5, "opponentAttacks": 0},
            {"tag": "#89PRR8890", "name": "AzureBlu", "townhallLevel": 14, "mapPosition": 29, "opponentAttacks": 0},
            {"tag": "#P8CCVL80J", "name": "✝️尺ㄖ爪么几 乇爪卩工尺乇✝", "townhallLevel": 15, "mapPosition": 22,
                "opponentAttacks": 0},
            {"tag": "#2VLGPUG2Y", "name": "utk", "townhallLevel": 15, "mapPosition": 11, "opponentAttacks": 0},
            {"tag": "#8G8UJ9RQG", "name": "☦King☦Swaggy_", "townhallLevel": 15, "mapPosition": 7, "opponentAttacks": 0},
            {"tag": "#PQ9CJLPQ", "name": "Rohaan the gr8", "townhallLevel": 14, "mapPosition": 32,
                "opponentAttacks": 0},
            {"tag": "#P9CLVG9VY", "name": "xX_RAEES_Xx", "townhallLevel": 13, "mapPosition": 43, "opponentAttacks": 0},
            {"tag": "#Y2PPJLP2C", "name": "Lͥegͣeͫnd❄️Snow", "townhallLevel": 15, "mapPosition": 18,
                "opponentAttacks": 0},
            {"tag": "#QC229Q2R0", "name": "✧山 ɪ ɴ ᴛ ᴇ ʀ✧", "townhallLevel": 12, "mapPosition": 50,
                "opponentAttacks": 0},
            {"tag": "#2Y9G09CY8", "name": "shin", "townhallLevel": 15, "mapPosition": 1, "opponentAttacks": 0},
            {"tag": "#988U0V8PG", "name": "sori", "townhallLevel": 14, "mapPosition": 24, "opponentAttacks": 0},
            {"tag": "#P8J8PYCCP", "name": "..Nick..", "townhallLevel": 15, "mapPosition": 13, "opponentAttacks": 0},
            {"tag": "#289CYLCJ", "name": "CAPTAIN YAMI", "townhallLevel": 15, "mapPosition": 10, "opponentAttacks": 0},
            {"tag": "#Y9CQRYRU", "name": "⚡️JARROD⚡️", "townhallLevel": 14, "mapPosition": 26, "opponentAttacks": 0},
            {"tag": "#Y20URCGJ8", "name": "Saliq", "townhallLevel": 14, "mapPosition": 34, "opponentAttacks": 0},
            {"tag": "#2C0JYRV99", "name": "aden!", "townhallLevel": 15, "mapPosition": 8, "opponentAttacks": 0},
            {"tag": "#8CCU28R0Q", "name": "Vinayak", "townhallLevel": 15, "mapPosition": 15, "opponentAttacks": 0},
            {"tag": "#90LJVL8PU", "name": "PRANAY PELAY", "townhallLevel": 14, "mapPosition": 33, "opponentAttacks": 0},
            {"tag": "#P809RCV8P", "name": "EshAn", "townhallLevel": 14, "mapPosition": 30, "opponentAttacks": 0},
            {"tag": "#809CLQRRY", "name": "TIGER", "townhallLevel": 15, "mapPosition": 2, "opponentAttacks": 0},
            {"tag": "#PJRUVUCJJ", "name": "Darren", "townhallLevel": 15, "mapPosition": 37, "opponentAttacks": 0},
            {"tag": "#9VCYV08P9", "name": "AMMY VIRK", "townhallLevel": 12, "mapPosition": 49, "opponentAttacks": 0},
            {"tag": "#2C0CLVPYL", "name": "Shi Vu", "townhallLevel": 14, "mapPosition": 31, "opponentAttacks": 0},
            {"tag": "#8VLCY0JC8", "name": "``Shy Panda’’", "townhallLevel": 15, "mapPosition": 4, "opponentAttacks": 0},
            {"tag": "#UP00G0GY", "name": "Nishant", "townhallLevel": 13, "mapPosition": 41, "opponentAttacks": 0},
            {"tag": "#2UV8CC82R", "name": "Jade", "townhallLevel": 12, "mapPosition": 48, "opponentAttacks": 0},
            {"tag": "#PYRVUP2V0", "name": "MR.MËÊT GÃÑGÅÑÏ", "townhallLevel": 12, "mapPosition": 47,
                "opponentAttacks": 0},
            {"tag": "#LYCY0QPRY", "name": "IMMORTAL NG", "townhallLevel": 13, "mapPosition": 35, "opponentAttacks": 0},
            {"tag": "#8Y2JYY2P", "name": "KINGSMAN", "townhallLevel": 15, "mapPosition": 3, "opponentAttacks": 0},
            {"tag": "#YY0V0YPVY", "name": "PRINCE MUDIT", "townhallLevel": 15, "mapPosition": 14, "opponentAttacks": 0},
            {"tag": "#2GC0YC902", "name": "aden", "townhallLevel": 15, "mapPosition": 12, "opponentAttacks": 0},
            {"tag": "#P2PCQ9YV9", "name": "FIRE DRAGON", "townhallLevel": 15, "mapPosition": 19, "opponentAttacks": 0},
            {"tag": "#P9808C2GR", "name": "NAKUL EMPEROR", "townhallLevel": 13, "mapPosition": 36,
                "opponentAttacks": 0},
            {"tag": "#P2PCRJVG8", "name": "ÆŽHÆŘ", "townhallLevel": 13, "mapPosition": 38, "opponentAttacks": 0},
            {"tag": "#8CPCUGCPL", "name": "✌NARESH✌", "townhallLevel": 14, "mapPosition": 23, "opponentAttacks": 0},
            {"tag": "#9R0YYV9GL", "name": "☦King☦Kaushal_", "townhallLevel": 13, "mapPosition": 39,
                "opponentAttacks": 0},
            {"tag": "#LUUCQV9JJ", "name": "Ｉ ｍｉｓｓ ｕ ｎａｍｍｕ", "townhallLevel": 13, "mapPosition": 42,
                "opponentAttacks": 0},
            {"tag": "#8L8228PLC", "name": "MAYANK", "townhallLevel": 15, "mapPosition": 9, "opponentAttacks": 0},
            {"tag": "#9QV80Q8PQ", "name": "D A D D Y", "townhallLevel": 15, "mapPosition": 16, "opponentAttacks": 0},
            {"tag": "#U8PRJRUY", "name": "TH€_R@VI", "townhallLevel": 15, "mapPosition": 20, "opponentAttacks": 0},
            {"tag": "#20CGCULUP", "name": "⚡ÄBRÂR⚡", "townhallLevel": 13, "mapPosition": 40, "opponentAttacks": 0},
            {"tag": "#2VRJY8QVG", "name": "♠️DareDevil♠️", "townhallLevel": 15, "mapPosition": 21,
                "opponentAttacks": 0},
            {"tag": "#80YGCRJYP", "name": "⚡ÅBRĂR⚡", "townhallLevel": 15, "mapPosition": 27, "opponentAttacks": 0}]},
    "opponent": {"tag": "#29GQ9PRUV", "name": "Altar of Minis", "badgeUrls": {
        "small": "https://api-assets.clashofclans.com/badges/70/tluolhanc7kUTVr-qWJduCWiNPYKPtzvrhJGTTUdUHA.png",
        "large": "https://api-assets.clashofclans.com/badges/512/tluolhanc7kUTVr-qWJduCWiNPYKPtzvrhJGTTUdUHA.png",
        "medium": "https://api-assets.clashofclans.com/badges/200/tluolhanc7kUTVr-qWJduCWiNPYKPtzvrhJGTTUdUHA.png"},
        "clanLevel": 21, "attacks": 0, "stars": 0, "destructionPercentage": 0, "members": [
            {"tag": "#YPLRPPVJ", "name": "mikeyp_123", "townhallLevel": 15, "mapPosition": 3, "opponentAttacks": 0},
            {"tag": "#LP0LQUQL", "name": "1tuana2", "townhallLevel": 15, "mapPosition": 10, "opponentAttacks": 0},
            {"tag": "#QV2Y8UR", "name": "Roro9728", "townhallLevel": 15, "mapPosition": 8, "opponentAttacks": 0},
            {"tag": "#98U0QUJYP", "name": "Interstellar", "townhallLevel": 13, "mapPosition": 41, "opponentAttacks": 0},
            {"tag": "#9JLJLQGR", "name": "-Stubby-", "townhallLevel": 14, "mapPosition": 25, "opponentAttacks": 0},
            {"tag": "#80QYV0JQC", "name": "URVISH 007", "townhallLevel": 15, "mapPosition": 16, "opponentAttacks": 0},
            {"tag": "#LR0JPLLCP", "name": "Tobi", "townhallLevel": 15, "mapPosition": 19, "opponentAttacks": 0},
            {"tag": "#PU98LU800", "name": "FROST DRAGON", "townhallLevel": 15, "mapPosition": 20, "opponentAttacks": 0},
            {"tag": "#Y90C0V", "name": "al3xndrTheGreat", "townhallLevel": 14, "mapPosition": 22, "opponentAttacks": 0},
            {"tag": "#8Q09UGLJ", "name": "Sid", "townhallLevel": 15, "mapPosition": 4, "opponentAttacks": 0},
            {"tag": "#2G9C0GCRL", "name": "ɑditɑRiti", "townhallLevel": 12, "mapPosition": 42, "opponentAttacks": 0},
            {"tag": "#Q9VUJPLVP", "name": "Nthny", "townhallLevel": 14, "mapPosition": 43, "opponentAttacks": 0},
            {"tag": "#QYU8LLP2P", "name": "Nthny", "townhallLevel": 14, "mapPosition": 45, "opponentAttacks": 0},
            {"tag": "#QPJPR0RCY", "name": "Mohammad Rajo", "townhallLevel": 13, "mapPosition": 37,
                "opponentAttacks": 0},
            {"tag": "#QRULYCJG9", "name": "blank___", "townhallLevel": 12, "mapPosition": 47, "opponentAttacks": 0},
            {"tag": "#QJYQ9UCGR", "name": "NullPixel 96", "townhallLevel": 12, "mapPosition": 48, "opponentAttacks": 0},
            {"tag": "#P0LGUYP9Y", "name": "SainiTaran..", "townhallLevel": 13, "mapPosition": 49, "opponentAttacks": 0},
            {"tag": "#CVCUCR99", "name": "tobster", "townhallLevel": 13, "mapPosition": 36, "opponentAttacks": 0},
            {"tag": "#8J9VRRUVU", "name": "LOVELY LOKESH", "townhallLevel": 15, "mapPosition": 2, "opponentAttacks": 0},
            {"tag": "#L9JY0L98Y", "name": "Manoj", "townhallLevel": 15, "mapPosition": 28, "opponentAttacks": 0},
            {"tag": "#289PYLU22", "name": "Anthony", "townhallLevel": 15, "mapPosition": 1, "opponentAttacks": 0},
            {"tag": "#QL98JR0RU", "name": "Nthny", "townhallLevel": 14, "mapPosition": 46, "opponentAttacks": 0},
            {"tag": "#2LP2CY9UU", "name": "SIMARJOT", "townhallLevel": 15, "mapPosition": 17, "opponentAttacks": 0},
            {"tag": "#2UCQVC9PV", "name": "✴Sagor✴", "townhallLevel": 14, "mapPosition": 34, "opponentAttacks": 0},
            {"tag": "#YLVG9V0Q2", "name": "Abdul Rahman", "townhallLevel": 15, "mapPosition": 27, "opponentAttacks": 0},
            {"tag": "#2U2VLU80Y", "name": "Loucentelle", "townhallLevel": 13, "mapPosition": 32, "opponentAttacks": 0},
            {"tag": "#Q8VJRCGJR", "name": "Nthny", "townhallLevel": 14, "mapPosition": 39, "opponentAttacks": 0},
            {"tag": "#Q08LQP8JJ", "name": "Nthny", "townhallLevel": 15, "mapPosition": 11, "opponentAttacks": 0},
            {"tag": "#PL28VL8RR", "name": "SHAMOON 2.0", "townhallLevel": 15, "mapPosition": 15, "opponentAttacks": 0},
            {"tag": "#PV2QPQ8R2", "name": "EVIL", "townhallLevel": 15, "mapPosition": 26, "opponentAttacks": 0},
            {"tag": "#9VCR0P2QJ", "name": "Phen0menal AJ", "townhallLevel": 12, "mapPosition": 44,
                "opponentAttacks": 0},
            {"tag": "#8R88GL82C", "name": "TEJ BANNA", "townhallLevel": 15, "mapPosition": 7, "opponentAttacks": 0},
            {"tag": "#9928PVLRY", "name": "Gagsdid", "townhallLevel": 13, "mapPosition": 30, "opponentAttacks": 0},
            {"tag": "#22JYPC0UQ", "name": "♥️Piku_Oreo♥️", "townhallLevel": 15, "mapPosition": 6, "opponentAttacks": 0},
            {"tag": "#992YP2RPY", "name": "ViveK", "townhallLevel": 15, "mapPosition": 9, "opponentAttacks": 0},
            {"tag": "#9822VVQJV", "name": "TY ! Conqueror", "townhallLevel": 13, "mapPosition": 38,
                "opponentAttacks": 0},
            {"tag": "#2LGQGC0V8", "name": "Yugam uppal", "townhallLevel": 12, "mapPosition": 40, "opponentAttacks": 0},
            {"tag": "#8UGCRQV2G", "name": "Aryan", "townhallLevel": 15, "mapPosition": 12, "opponentAttacks": 0},
            {"tag": "#QRR89YY92", "name": "MD Hasan", "townhallLevel": 11, "mapPosition": 50, "opponentAttacks": 0},
            {"tag": "#VLVJP980", "name": "JAY KAREKAR 5", "townhallLevel": 13, "mapPosition": 31, "opponentAttacks": 0},
            {"tag": "#99VPLC9GP", "name": "Md hassan khan", "townhallLevel": 14, "mapPosition": 24,
                "opponentAttacks": 0},
            {"tag": "#289RQ8UC2", "name": "NIMESH", "townhallLevel": 13, "mapPosition": 35, "opponentAttacks": 0},
            {"tag": "#9CYPQPGC9", "name": "VîVêK 2.0", "townhallLevel": 14, "mapPosition": 29, "opponentAttacks": 0},
            {"tag": "#88URYQ8JG", "name": "Ｐｙｄｒｏｘ", "townhallLevel": 14, "mapPosition": 23, "opponentAttacks": 0},
            {"tag": "#PLLJ9PR8P", "name": "_Lørd_Abdul_", "townhallLevel": 13, "mapPosition": 33, "opponentAttacks": 0},
            {"tag": "#89V0YQ0PY", "name": "DevilElite", "townhallLevel": 14, "mapPosition": 21, "opponentAttacks": 0},
            {"tag": "#9QV9LP899", "name": "Nebulae", "townhallLevel": 15, "mapPosition": 18, "opponentAttacks": 0},
            {"tag": "#8P2RUUCQR", "name": "_-Samu-_", "townhallLevel": 15, "mapPosition": 14, "opponentAttacks": 0},
            {"tag": "#920UGYLU0", "name": "★★LegenD★★BoY★★", "townhallLevel": 15, "mapPosition": 13,
                "opponentAttacks": 0},
            {"tag": "#22Q2GCQGY", "name": "Nishant", "townhallLevel": 15, "mapPosition": 5, "opponentAttacks": 0}]}},
    "headers": {"cache-control": "max-age=120", "content-type": "application/json; charset=utf-8"}, "response_code": 200}